package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematicirpt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-12-12T10:23:24.625+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", name = "PagamentiTelematiciRPT")
@XmlSeeAlso({gov.telematici.pagamenti.ws.ppthead.ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, gov.telematici.pagamenti.ws.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciRPT {

    @WebResult(name = "nodoInviaRispostaRevocaRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRispostaRevoca", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRispostaRevocaRisposta")
    @WebMethod(action = "nodoInviaRispostaRevoca")
    public gov.telematici.pagamenti.ws.NodoInviaRispostaRevocaRisposta nodoInviaRispostaRevoca(
        @WebParam(partName = "parameters", name = "nodoInviaRispostaRevoca", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoInviaRispostaRevoca parameters
    );

    @WebResult(name = "nodoInviaCarrelloRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaCarrelloRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaCarrelloRPTRisposta")
    @WebMethod(action = "nodoInviaCarrelloRPT")
    public gov.telematici.pagamenti.ws.NodoInviaCarrelloRPTRisposta nodoInviaCarrelloRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoInviaCarrelloRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoInviaCarrelloRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazioneCarrelloPPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazioneCarrelloPPT header
    );

    @WebResult(name = "nodoChiediQuadraturaPARisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediQuadraturaPARichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediQuadraturaPARisposta")
    @WebMethod(action = "nodoChiediQuadraturaPA")
    public gov.telematici.pagamenti.ws.NodoChiediQuadraturaPARisposta nodoChiediQuadraturaPA(
        @WebParam(partName = "parameters", name = "nodoChiediQuadraturaPA", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediQuadraturaPA parameters
    );

    @WebResult(name = "nodoInviaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRPTRisposta")
    @WebMethod(action = "nodoInviaRPT")
    public gov.telematici.pagamenti.ws.NodoInviaRPTRisposta nodoInviaRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoInviaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoInviaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );

    @WebResult(name = "nodoInviaRichiestaStornoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRichiestaStorno", output = "http://ws.pagamenti.telematici.gov/PPT/nodoInviaRichiestaStornoRisposta")
    @WebMethod(action = "nodoInviaRichiestaStorno")
    public gov.telematici.pagamenti.ws.NodoInviaRichiestaStornoRisposta nodoInviaRichiestaStorno(
        @WebParam(partName = "parameters", name = "nodoInviaRichiestaStorno", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoInviaRichiestaStorno parameters
    );

    @WebResult(name = "nodoChiediElencoQuadraturePARisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoQuadraturePARichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoQuadraturePARisposta")
    @WebMethod(action = "nodoChiediElencoQuadraturePA")
    public gov.telematici.pagamenti.ws.NodoChiediElencoQuadraturePARisposta nodoChiediElencoQuadraturePA(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediElencoQuadraturePA", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediElencoQuadraturePA bodyrichiesta
    );

    @WebResult(name = "nodoChiediListaPendentiRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediListaPendentiRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediListaPendentiRPTRisposta")
    @WebMethod(action = "nodoChiediListaPendentiRPT")
    public gov.telematici.pagamenti.ws.NodoChiediListaPendentiRPTRisposta nodoChiediListaPendentiRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediListaPendentiRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediListaPendentiRPT bodyrichiesta
    );

    @WebResult(name = "nodoChiediSceltaWISPRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediSceltaWISPRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediSceltaWISPRisposta")
    @WebMethod(action = "nodoChiediSceltaWISP")
    public gov.telematici.pagamenti.ws.NodoChiediSceltaWISPRisposta nodoChiediSceltaWISP(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediSceltaWISP", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediSceltaWISP bodyrichiesta
    );

    @WebResult(name = "nodoPAChiediInformativaPARisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoPAChiediInformativaPARichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoPAChiediInformativaPARisposta")
    @WebMethod(action = "nodoPAChiediInformativaPA")
    public gov.telematici.pagamenti.ws.NodoPAChiediInformativaPARisposta nodoPAChiediInformativaPA(
        @WebParam(partName = "bodyrichiesta", name = "nodoPAChiediInformativaPA", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoPAChiediInformativaPA bodyrichiesta
    );

    @WebResult(name = "nodoChiediCopiaRTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediCopiaRTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediCopiaRTRisposta")
    @WebMethod(action = "nodoChiediCopiaRT")
    public gov.telematici.pagamenti.ws.NodoChiediCopiaRTRisposta nodoChiediCopiaRT(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediCopiaRT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediCopiaRT bodyrichiesta
    );

    @WebResult(name = "nodoChiediElencoFlussiRendicontazioneRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoFlussiRendicontazioneRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediElencoFlussiRendicontazioneRisposta")
    @WebMethod(action = "nodoChiediElencoFlussiRendicontazione")
    public gov.telematici.pagamenti.ws.NodoChiediElencoFlussiRendicontazioneRisposta nodoChiediElencoFlussiRendicontazione(
        @WebParam(partName = "parameters", name = "nodoChiediElencoFlussiRendicontazione", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediElencoFlussiRendicontazione parameters
    );

    @WebResult(name = "nodoChiediInformativaPSPRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediInformativaPSPRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediInformativaPSPRisposta")
    @WebMethod(action = "nodoChiediInformativaPSP")
    public gov.telematici.pagamenti.ws.NodoChiediInformativaPSPRisposta nodoChiediInformativaPSP(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediInformativaPSP", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediInformativaPSP bodyrichiesta
    );

    @WebResult(name = "nodoChiediStatoRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediStatoRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediStatoRPTRisposta")
    @WebMethod(action = "nodoChiediStatoRPT")
    public gov.telematici.pagamenti.ws.NodoChiediStatoRPTRisposta nodoChiediStatoRPT(
        @WebParam(partName = "bodyrichiesta", name = "nodoChiediStatoRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediStatoRPT bodyrichiesta
    );

    @WebResult(name = "nodoChiediFlussoRendicontazioneRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "parameters")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediFlussoRendicontazioneRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/nodoChiediFlussoRendicontazioneRisposta")
    @WebMethod(action = "nodoChiediFlussoRendicontazione")
    public gov.telematici.pagamenti.ws.NodoChiediFlussoRendicontazioneRisposta nodoChiediFlussoRendicontazione(
        @WebParam(partName = "parameters", name = "nodoChiediFlussoRendicontazione", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.NodoChiediFlussoRendicontazione parameters
    );
}
