-- Eseguire come superuser questo script per creare 
-- i databses necessari a mypay ed i relativi utenti.
--
-- database :
--	mypay.pa
--	mypay.nodo-regionale-fesp
--	mybox
--	myprofile
--	mydictionary
--	mypivot
--
-- su questa macchina e' possibile lanciare lo script come:
-- psql --user sysdba --host /opt/mypay/postgres/9.5/socket postgres < db.sql
--
SET client_min_messages = warning;

CREATE ROLE "__TAG_MYPAY_PA_DB_USERNAME__" LOGIN
  PASSWORD '__TAG_MYPAY_PA_DB_PASSWORD__'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_USERNAME__" LOGIN
  PASSWORD '__TAG_MYPAY_NODO_REGIONALE_FESP_DB_PASSWORD__'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


CREATE ROLE "__TAG_MYBOX_DB_USERNAME__" LOGIN
  PASSWORD '__TAG_MYBOX_DB_PASSWORD__'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "__TAG_MYPROFILE_DB_USERNAME__" LOGIN
  PASSWORD '__TAG_MYPROFILE_DB_PASSWORD__'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "__TAG_MYDICTIONARY_DB_USERNAME__" LOGIN
  PASSWORD '__TAG_MYDICTIONARY_DB_PASSWORD__'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "__TAG_MYPIVOT_DB_USERNAME__" LOGIN
  PASSWORD '__TAG_MYPIVOT_DB_PASSWORD__'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE "__TAG_MYPAY_PA_DB_NAME__"
  WITH OWNER = "__TAG_MYPAY_PA_DB_USERNAME__"
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

CREATE DATABASE "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_NAME__"
  WITH OWNER = "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_USERNAME__"
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

CREATE DATABASE "__TAG_MYBOX_DB_NAME__"
  WITH OWNER = "__TAG_MYBOX_DB_USERNAME__"
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

CREATE DATABASE "__TAG_MYPROFILE_DB_NAME__"
  WITH OWNER = "__TAG_MYPROFILE_DB_USERNAME__"
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

CREATE DATABASE "__TAG_MYDICTIONARY_DB_NAME__"
  WITH OWNER = "__TAG_MYPROFILE_DB_USERNAME__"
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

CREATE DATABASE "__TAG_MYPIVOT_DB_NAME__"
  WITH OWNER = "__TAG_MYPIVOT_DB_USERNAME__"
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;


\connect "__TAG_MYPAY_PA_DB_NAME__";
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS "__TAG_MYPAY_PA_DB_SCHEMA__" AUTHORIZATION "__TAG_MYPAY_PA_DB_USERNAME__";
GRANT ALL on SCHEMA "__TAG_MYPAY_PA_DB_SCHEMA__" to "__TAG_MYPAY_PA_DB_USERNAME__";

\connect "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_NAME__";
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_SCHEMA__" AUTHORIZATION "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_USERNAME__";
GRANT ALL on SCHEMA "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_SCHEMA__" to "__TAG_MYPAY_NODO_REGIONALE_FESP_DB_USERNAME__";

\connect "__TAG_MYBOX_DB_NAME__";
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS "__TAG_MYBOX_DB_SCHEMA__" AUTHORIZATION "__TAG_MYBOX_DB_USERNAME__";
GRANT ALL on SCHEMA "__TAG_MYBOX_DB_SCHEMA__" to "__TAG_MYBOX_DB_USERNAME__";

\connect "__TAG_MYDICTIONARY_DB_NAME__";
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS "__TAG_MYDICTIONARY_DB_SCHEMA__" AUTHORIZATION "__TAG_MYDICTIONARY_DB_USERNAME__";
GRANT ALL on SCHEMA "__TAG_MYDICTIONARY_DB_SCHEMA__" to "__TAG_MYDICTIONARY_DB_USERNAME__";

\connect "__TAG_MYPROFILE_DB_NAME__";
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS "__TAG_MYPROFILE_DB_SCHEMA__" AUTHORIZATION "__TAG_MYPROFILE_DB_USERNAME__";
GRANT ALL on SCHEMA "__TAG_MYPROFILE_DB_SCHEMA__" to "__TAG_MYPROFILE_DB_USERNAME__";

\connect "__TAG_MYPIVOT_DB_NAME__";
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS "__TAG_MYPIVOT_DB_SCHEMA__" AUTHORIZATION "__TAG_MYPIVOT_DB_USERNAME__";
GRANT ALL on SCHEMA "__TAG_MYPIVOT_DB_SCHEMA__" to "__TAG_MYPIVOT_DB_USERNAME__";
