package it.toscana.rete.cart.servizi.iris_1_1.ws.idpconfigurazione;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-02-14T17:50:13.783+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", name = "ConfigurazioneIDP")
@XmlSeeAlso({it.toscana.rete.cart.servizi.iris_1_1.idpheader.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpconfigurazione.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.idpconfigurazione.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.idpesito.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.idpinclude.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConfigurazioneIDP {

    @WebMethod(operationName = "IdpConfigurazioneEnte", action = "IdpConfigurazioneEnte")
    @WebResult(name = "IdpConfigurazioneEnte.Esito", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", partName = "IdpConfigurazioneEnte.Esito")
    public it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpconfigurazione.IdpConfigurazioneEnteEsito idpConfigurazioneEnte(
        @WebParam(partName = "IdpConfigurazioneEnte", name = "IdpConfigurazioneEnte", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy")
        it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpconfigurazione.IdpConfigurazioneEnte idpConfigurazioneEnte
    );

    @WebMethod(operationName = "IdpConfigurazioneTributi", action = "IdpConfigurazioneTributi")
    @WebResult(name = "IdpConfigurazioneTributi.Esito", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", partName = "IdpConfigurazioneTribut.Esito")
    public it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpconfigurazione.IdpConfigurazioneTributiEsito idpConfigurazioneTributi(
        @WebParam(partName = "IdpConfigurazioneTributi", name = "IdpConfigurazioneTributi", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy")
        it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpconfigurazione.IdpConfigurazioneTributi idpConfigurazioneTributi
    );
}
