package it.regioneveneto.mygov.payment.mypivot.utils;

/**
 * 
 * @author Cristiano Perin
 *
 */
public class FaultConstants {

	public static final String PIVOT_ENTE_NON_VALIDO = "PIVOT_ENTE_NON_VALIDO";
	public static final String PIVOT_DATE_FROM_NON_VALIDO = "PIVOT_DATE_FROM_NON_VALIDO";
	public static final String PIVOT_DATE_TO_NON_VALIDO = "PIVOT_DATE_TO_NON_VALIDO";
	public static final String PIVOT_INTERVALLO_DATE_NON_VALIDO = "PIVOT_INTERVALLO_DATE_NON_VALIDO";
	public static final String PIVOT_IDENTIFICATIVO_TIPO_DOVUTO_NON_VALIDO = "PIVOT_IDENTIFICATIVO_TIPO_DOVUTO_NON_VALIDO";
	public static final String PIVOT_CLASSIFICAZIONE_NON_VALIDA = "PIVOT_CLASSIFICAZIONE_NON_VALIDA";
	public static final String PIVOT_CLASSIFICAZIONE_NON_ABILITATA = "PIVOT_CLASSIFICAZIONE_NON_ABILITATA";
	public static final String PIVOT_REQUEST_TOKEN_NON_VALIDO = "PIVOT_REQUEST_TOKEN_NON_VALIDO";
	public static final String PIVOT_VERSIONE_TRACCIATO_EXPORT_NON_VALIDA = "PIVOT_VERSIONE_TRACCIATO_EXPORT_NON_VALIDA";
	public static final String PIVOT_CLASSIFICAZIONE_COMPLETEZZA_NON_VALIDA = "PIVOT_CLASSIFICAZIONE_COMPLETEZZA_NON_VALIDA";
	
	
	public static final String PIVOT_RICHIESTA_CON_PARAMETRI_MULTIPLI = "PIVOT_RICHIESTA_CON_PARAMETRI_MULTIPLI";
	public static final String PIVOT_PARAMETRO_ANNO_BOLLETTA_NULLO = "PIVOT_PARAMETRO_ANNO_BOLLETTA_NULLO";
	public static final String PIVOT_PARAMETRO_NUMERO_BOLLETTA_NULLO = "PIVOT_PARAMETRO_NUMERO_BOLLETTA_NULLO";
	public static final String PIVOT_PARAMETRO_IUF_NULLO = "PIVOT_PARAMETRO_IUF_NULLO";
	public static final String PIVOT_BOLLETTA_NON_TROVATA = "PIVOT_BOLLETTA_NON_TROVATA";
	public static final String PIVOT_BOLLETTA_NON_PAGOPA = "PIVOT_BOLLETTA_NON_PAGOPA";
	public static final String PIVOT_NESSUNA_RENDICONTAZIONE_TROVATA = "PIVOT_NESSUNA_RENDICONTAZIONE_TROVATA";
	public static final String PIVOT_NESSUNA_RICEVUTA_TROVATA = "PIVOT_NESSUNA_RICEVUTA_TROVATA";
	public static final String PIVOT_DETTAGLIO_NON_PRESENTE = "PIVOT_DETTAGLIO_NON_PRESENTE";

}
