package it.regioneveneto.mygov.payment.mypivot.utils;

public class SessionVariables {

	public static String SCELTA_ENTE_PG = "SCELTA_ENTE_PG";
	public static String SCELTA_ENTE_PG_SIZE = "SCELTA_ENTE_PG_SIZE";
	public static String SCELTA_ENTE_F_SEARCH = "SCELTA_ENTE_F_SEARCH";

	public static final String EXPORT_RENDICONTAZIONE_PG = "EXPORT_RENDICONTAZIONE_PG";
	public static final String EXPORT_RENDICONTAZIONE_PG_SIZE = "EXPORT_RENDICONTAZIONE_PG_SIZE";
	public static final String EXPORT_RENDICONTAZIONE_CODICE_IUD = "EXPORT_RENDICONTAZIONE_CODICE_IUD";
	public static final String EXPORT_RENDICONTAZIONE_CODICE_IUV = "EXPORT_RENDICONTAZIONE_CODICE_IUV";
	public static final String EXPORT_RENDICONTAZIONE_DENOMINAZIONE_ATTESTANTE = "EXPORT_RENDICONTAZIONE_DENOMINAZIONE_ATTESTANTE";
	public static final String EXPORT_RENDICONTAZIONE_IDENTIFICATIVO_UNIVOCO_RISCOSSIONE = "EXPORT_RENDICONTAZIONE_IDENTIFICATIVO_UNIVOCO_RISCOSSIONE";
	public static final String EXPORT_RENDICONTAZIONE_CODICE_IDENTIFICATIVO_UNIVOCO_VERSANTE = "EXPORT_RENDICONTAZIONE_CODICE_IDENTIFICATIVO_UNIVOCO_VERSANTE";
	public static final String EXPORT_RENDICONTAZIONE_ANAGRAFICA_VERSANTE = "EXPORT_RENDICONTAZIONE_ANAGRAFICA_VERSANTE";
	public static final String EXPORT_RENDICONTAZIONE_CODICE_IDENTIFICATIVO_UNIVOCO_PAGATORE = "EXPORT_RENDICONTAZIONE_CODICE_IDENTIFICATIVO_UNIVOCO_PAGATORE";
	public static final String EXPORT_RENDICONTAZIONE_ANAGRAFICA_PAGATORE = "EXPORT_RENDICONTAZIONE_ANAGRAFICA_PAGATORE";
	public static final String EXPORT_RENDICONTAZIONE_CAUSALE_VERSAMENTO = "EXPORT_RENDICONTAZIONE_CAUSALE_VERSAMENTO";
	public static final String EXPORT_RENDICONTAZIONE_DATA_ESITO_SINGOLO_PAGAMENTO_DA = "EXPORT_RENDICONTAZIONE_DATA_ESITO_SINGOLO_PAGAMENTO_DA";
	public static final String EXPORT_RENDICONTAZIONE_DATA_ESITO_SINGOLO_PAGAMENTO_A = "EXPORT_RENDICONTAZIONE_DATA_ESITO_SINGOLO_PAGAMENTO_A";
	public static final String EXPORT_RENDICONTAZIONE_IDENTIFICATIVO_FLUSSO_RENDICONTAZIONE = "EXPORT_RENDICONTAZIONE_IDENTIFICATIVO_FLUSSO_RENDICONTAZIONE";
	public static final String EXPORT_RENDICONTAZIONE_IDENTIFICATIVO_UNIVOCO_REGOLAMENTO = "EXPORT_RENDICONTAZIONE_IDENTIFICATIVO_UNIVOCO_REGOLAMENTO";
	public static final String EXPORT_RENDICONTAZIONE_DATA_REGOLAMENTO_DA = "EXPORT_RENDICONTAZIONE_DATA_REGOLAMENTO_DA";
	public static final String EXPORT_RENDICONTAZIONE_DATA_REGOLAMENTO_A = "EXPORT_RENDICONTAZIONE_DATA_REGOLAMENTO_A";
	public static final String EXPORT_RENDICONTAZIONE_DATA_VALUTA_DA = "EXPORT_RENDICONTAZIONE_DATA_VALUTA_DA";
	public static final String EXPORT_RENDICONTAZIONE_DATA_VALUTA_A = "EXPORT_RENDICONTAZIONE_DATA_VALUTA_A";
	public static final String EXPORT_RENDICONTAZIONE_COD_TIPO_DOVUTO = "EXPORT_RENDICONTAZIONE_COD_TIPO_DOVUTO";
	public static final String EXPORT_TOTALE_RECORD = "EXPORT_TOTALE_RECORD";
	
	
	
	
	
	
	public static final String EXPORT_TESORERIA_PG = "EXPORT_TESORERIA_PG";
	public static final String EXPORT_TESORERIA_PG_SIZE = "EXPORT_TESORERIA_PG_SIZE";
	public static final String EXPORT_TESORERIA_COD_OR1 = "EXPORT_TESORERIA_COD_OR1";
	public static final String EXPORT_TESORERIA_CODICE_IUD = "EXPORT_TESORERIA_CODICE_IUD";
	public static final String EXPORT_TESORERIA_CODICE_IUV = "EXPORT_TESORERIA_CODICE_IUV";
	public static final String EXPORT_TESORERIA_DENOMINAZIONE_ATTESTANTE = "EXPORT_TESORERIA_DENOMINAZIONE_ATTESTANTE";
	public static final String EXPORT_TESORERIA_IDENTIFICATIVO_UNIVOCO_RISCOSSIONE = "EXPORT_TESORERIA_IDENTIFICATIVO_UNIVOCO_RISCOSSIONE";
	public static final String EXPORT_TESORERIA_CODICE_IDENTIFICATIVO_UNIVOCO_VERSANTE = "EXPORT_TESORERIA_CODICE_IDENTIFICATIVO_UNIVOCO_VERSANTE";
	public static final String EXPORT_TESORERIA_CONTO = "EXPORT_TESORERIA_CONTO";
	public static final String EXPORT_TESORERIA_ANAGRAFICA_VERSANTE = "EXPORT_TESORERIA_ANAGRAFICA_VERSANTE";
	public static final String EXPORT_TESORERIA_CODICE_IDENTIFICATIVO_UNIVOCO_PAGATORE = "EXPORT_TESORERIA_CODICE_IDENTIFICATIVO_UNIVOCO_PAGATORE";
	public static final String EXPORT_TESORERIA_ANAGRAFICA_PAGATORE = "EXPORT_TESORERIA_ANAGRAFICA_PAGATORE";
	public static final String EXPORT_TESORERIA_CAUSALE_VERSAMENTO = "EXPORT_TESORERIA_CAUSALE_VERSAMENTO";
	public static final String EXPORT_TESORERIA_DATA_ESECUZIONE_SINGOLO_PAGAMENTO_DA = "EXPORT_TESORERIA_DATA_ESECUZIONE_SINGOLO_PAGAMENTO_DA";
	public static final String EXPORT_TESORERIA_DATA_ESECUZIONE_SINGOLO_PAGAMENTO_A = "EXPORT_TESORERIA_DATA_ESECUZIONE_SINGOLO_PAGAMENTO_A";
	public static final String EXPORT_TESORERIA_DATA_ESITO_SINGOLO_PAGAMENTO_DA = "EXPORT_TESORERIA_DATA_ESITO_SINGOLO_PAGAMENTO_DA";
	public static final String EXPORT_TESORERIA_DATA_ESITO_SINGOLO_PAGAMENTO_A = "EXPORT_TESORERIA_DATA_ESITO_SINGOLO_PAGAMENTO_A";
	public static final String EXPORT_TESORERIA_IDENTIFICATIVO_FLUSSO_TESORERIA = "EXPORT_TESORERIA_IDENTIFICATIVO_FLUSSO_TESORERIA";
	public static final String EXPORT_TESORERIA_IDENTIFICATIVO_UNIVOCO_REGOLAMENTO = "EXPORT_TESORERIA_IDENTIFICATIVO_UNIVOCO_REGOLAMENTO";
	public static final String EXPORT_TESORERIA_DATA_REGOLAMENTO_DA = "EXPORT_TESORERIA_DATA_REGOLAMENTO_DA";
	public static final String EXPORT_TESORERIA_DATA_REGOLAMENTO_A = "EXPORT_TESORERIA_DATA_REGOLAMENTO_A";
	public static final String EXPORT_TESORERIA_DATA_VALUTA_CHECK = "EXPORT_TESORERIA_DATA_VALUTA_CHECK";
	public static final String EXPORT_TESORERIA_DATA_ESECUZIONE_CHECK = "EXPORT_TESORERIA_DATA_ESECUZIONE_CHECK";
	public static final String EXPORT_TESORERIA_DATA_ESITO_CHECK = "EXPORT_TESORERIA_DATA_ESITO_CHECK";
	public static final String EXPORT_TESORERIA_DATA_REGOLAMENTO_CHECK = "EXPORT_TESORERIA_DATA_REGOLAMENTO_CHECK";
	public static final String EXPORT_TESORERIA_DATA_CONTABILE_CHECK = "EXPORT_TESORERIA_DATA_CONTABILE_CHECK";
	public static final String EXPORT_TESORERIA_COD_TIPO_DOVUTO = "EXPORT_TESORERIA_COD_TIPO_DOVUTO";
	public static final String EXPORT_TESORERIA_IMPORTO = "EXPORT_TESORERIA_IMPORTO";
	public static final String EXPORT_TESORERIA_ONLY_ERRORS_CHECK = "EXPORT_TESORERIA_ONLY_ERRORS_CHECK";
	public static final String EXPORT_TESORERIA_ERROR_CODE = "EXPORT_TESORERIA_ERROR_CODE";
	
	public static final String EXPORT_TESORERIA_TIPO_VISUALIZZAZIONE = "EXPORT_TESORERIA_TIPO_VISUALIZZAZIONE";
	
	
	public static final String ACTION_VISUALIZZA = "ACTION_VISUALIZZA";
	public static final String ACTION_VISUALIZZA_TESORERIA = "ACTION_VISUALIZZA_TESORERIA";
	
	public static final String EXPORT_TESORERIA_DATA_CONTABILE_A = "EXPORT_TESORERIA_DATA_CONTABILE_A";
	public static final String EXPORT_TESORERIA_DATA_CONTABILE_DA = "EXPORT_TESORERIA_DATA_CONTABILE_DA";
	public static final String EXPORT_TESORERIA_DATA_VALUTA_DA = "EXPORT_TESORERIA_DATA_VALUTA_DA";
	public static final String EXPORT_TESORERIA_DATA_VALUTA_A = "EXPORT_TESORERIA_DATA_VALUTA_A";
	public static final String FLUSSI_UPLOAD_PG = "FLUSSI_UPLOAD_PG";
	public static final String FLUSSI_UPLOAD_PG_SIZE = "FLUSSI_UPLOAD_PG_SIZE";
	public static final String FLUSSI_UPLOAD_DT_FROM = "FLUSSI_UPLOAD_DT_FROM";
	public static final String FLUSSI_UPLOAD_DT_TO = "FLUSSI_UPLOAD_DT_TO";
	public static final String FLUSSI_UPLOAD_F_SEARCH = "FLUSSI_UPLOAD_F_SEARCH";
	
	public static final String FLUSSI_EXPORT_RICONCILIAZIONE_PG = "FLUSSI_EXPORT_RICONCILIAZIONE_PG";
	public static final String FLUSSI_EXPORT_RICONCILIAZIONE_PG_SIZE = "FLUSSI_EXPORT_RICONCILIAZIONE_PG_SIZE";
	public static final String FLUSSI_EXPORT_RICONCILIAZIONE_DT_FROM = "FLUSSI_EXPORT_RICONCILIAZIONE_DT_FROM";
	public static final String FLUSSI_EXPORT_RICONCILIAZIONE_DT_TO = "FLUSSI_EXPORT_RICONCILIAZIONE_DT_TO";
	public static final String FLUSSI_EXPORT_RICONCILIAZIONE_F_SEARCH = "FLUSSI_EXPORT_RICONCILIAZIONE_F_SEARCH";
	
	public static final String EXPORT_RICONCILIAZIONE_DATA_ULTIMO_AGGIORNAMENTO_DA = "EXPORT_RICONCILIAZIONE_DATA_ULTIMO_AGGIORNAMENTO_DA";
	public static final String EXPORT_RICONCILIAZIONE_DATA_ULTIMO_AGGIORNAMENTO_A = "EXPORT_RICONCILIAZIONE_DATA_ULTIMO_AGGIORNAMENTO_A";
	public static final String EXPORT_RICONCILIAZIONE_DATA_ULTIMO_AGGIORNAMENTO_CHECK = "EXPORT_RICONCILIAZIONE_DATA_ULTIMO_AGGIORNAMENTO_CHECK";

	public static final String EXPORT_SEGNALAZIONI_VISUALIZZA_NASCOSTI = "EXPORT_SEGNALAZIONI_VISUALIZZA_NASCOSTI";

	/**
	 * Key per recuparare l'ggetto contenente i filtri di ricerca della view di ricerca degli Accertamenti
	 */
	public static final String ACTION_ACCERTAMENTO_RICERCA 					= "ACTION_ACCERTAMENTO_RICERCA";
	/**
	 * Key per recuparare l'ggetto contenente i filtri di ricerca della view di ricerca dei pagamenti che possono essere aggiunti in accertamento.
	 */
	public static final String ACTION_ACCERTAMENTO_RICERCA_PAGAMENTI_ADD 	= "ACTION_ACCERTAMENTO_RICERCA_PAGAMENTI_ADD";
	/**
	 * Key per recuparare l'ggetto contenente i filtri di ricerca della view di ricerca dei pagamenti che possono essere eliminati dall'accertamento.
	 */
	public static final String ACTION_ACCERTAMENTO_RICERCA_PAGAMENTI_DELETE = "ACTION_ACCERTAMENTO_RICERCA_PAGAMENTI_DELETE";
	/**
	 * Key per recuparare l'ggetto contenente i filtri di ricerca della view di ricerca dei pagamenti che sono già in accertamento(Dettaglio).
	 */
	public static final String ACTION_ACCERTAMENTO_RICERCA_PAGAMENTI 		= "ACTION_ACCERTAMENTO_RICERCA_PAGAMENTI";
	/**
	 * Filtri della form di ricerca accertamento.
	 */
	public static final String ACCERTAMENTO_CODICE_TIPO_DOVUTO 		 		= "ACCERTAMENTO_COD_TIPO_DOVUTO";
	public static final String ACCERTAMENTO_CODICE_STATO 			 		= "ACCERTAMENTO_COD_STATO";
	public static final String ACCERTAMENTO_NOME_ACCERTAMENTO 		 		= "ACCERTAMENTO_NOME_ACCERTAMENTO";
	public static final String ACCERTAMENTO_CODICE_IUV 				 		= "ACCERTAMENTO_CODICE_IUV";
	public static final String ACCERTAMENTO_CODICE_IUD				 		= "ACCERTAMENTO_CODICE_IUD";
	public static final String ACCERTAMENTO_PAGE 					 		= "ACCERTAMENTO_PAGE";
	public static final String ACCERTAMENTO_PAGE_SIZE 				 		= "ACCERTAMENTO_PAGE_SIZE";
	public static final String ACCERTAMENTO_COD_IDENT_UNIVOCO_PAGATORE		= "ACCERTAMENTO_CODICE_IDENTIFICATIVO_UNIVOCO_PAGATORE";
	
	public static final String ACCERTAMENTO_CHECK_DATA_ESITO_SINGOLO_PAG 	= "ACCERTAMENTO_CHECK_DATA_ESITO_SINGOLO_PAGAMENTO";
	public static final String ACCERTAMENTO_DATA_ESITO_SINGOLO_PAG_DAL 		= "ACCERTAMENTO_DATA_ESITO_SINGOLO_PAGAMENTO_DAL";
	public static final String ACCERTAMENTO_DATA_ESITO_SINGOLO_PAG_AL 		= "ACCERTAMENTO_DATA_ESITO_SINGOLO_PAGAMENTO_AL";
	
	public static final String ACCERTAMENTO_CHECK_DATA_AGG 					= "ACCERTAMENTO_CHECK_DATA_AGGIORNAMENTO";
	public static final String ACCERTAMENTO_DATA_AGG_DAL 	 				= "ACCERTAMENTO_DATA_AGGIORNAMENTO_DAL";
	public static final String ACCERTAMENTO_DATA_AGG_AL 					= "ACCERTAMENTO_DATA_AGGIORNAMENTO_AL";
	
	/**
	 * Filtri per la visualizzazione del flusso di tesoreria
	 */
	public static final String ACTION_VISUALIZZA_FLUSSO_TESORERIA 		= "ACTION_VISUALIZZA_FLUSSO_TESORERIA";
	
	public static final String FTES_DATA_CONTABILE_CHECK 				= "FTES_DATA_CONTABILE_CHECK";
	public static final String FTES_DATA_CONTABILE_DA 					= "FTES_DATA_CONTABILE_DA";
	public static final String FTES_DATA_CONTABILE_A 					= "FTES_DATA_CONTABILE_A";
	
	public static final String FTES_DATA_VALUTA_CHECK 					= "FTES_DATA_VALUTA_CHECK";
	public static final String FTES_DATA_VALUTA_DA 						= "FTES_DATA_VALUTA_DA";
	public static final String FTES_DATA_VALUTA_A 						= "FTES_DATA_VALUTA_A";
	
	public static final String FTES_ANNO_BOLLETTA 						= "FTES_ANNO_BOLLETTA";
	public static final String FTES_CODICE_BOLLETTA 					= "FTES_CODICE_BOLLETTA";
	public static final String FTES_IMPORTO			 					= "FTES_IMPORTO";
	public static final String FTES_CODICE_CONTO						= "FTES_CODICE_CONTO";
	public static final String FTES_CODICE_ORDINANTE					= "FTES_CODICE_ORDINANTE";
	public static final String FTES_CODICE_IUV							= "FTES_CODICE_IUV";
	public static final String FTES_CODICE_IUF							= "FTES_CODICE_IUF";
	public static final String FTES_PG 									= "FTES_PG";
	public static final String FTES_PG_SIZE 							= "FTES_PG_SIZE";
	public static final String FTES_TOTAL_RECORDS						= "FTES_TOTAL_RECORDS";
	
	/**
	 * Filtri per la visualizzazione del flusso di rendicontazione
	 */
	public static final String ACTION_VISUALIZZA_FLUSSO_RENDICONTAZIONE		= "ACTION_VISUALIZZA_FLUSSO_RENDICONTAZIONE";
	
	public static final String FREND_DATA_REGOLAMENTO_CHECK 				= "FREND_DATA_REGOLAMENTO_CHECK";
	public static final String FREND_DATA_REGOLAMENTO_DA 					= "FREND_DATA_REGOLAMENTO_DA";
	public static final String FREND_DATA_REGOLAMENTO_A 					= "FREND_DATA_REGOLAMENTO_A";
	
	public static final String FREND_CODICE_IUF								= "FREND_CODICE_IUF";
	public static final String FREND_ID_UNIVOCO_REGOLAMENTO					= "FREND_ID_UNIVOCO_REGOLAMENTO";
	public static final String FREND_PG 									= "FREND_PG";
	public static final String FREND_PG_SIZE 								= "FREND_PG_SIZE";
	public static final String FREND_TOTAL_RECORDS							= "FREND_TOTAL_RECORDS";
	
	/**
	 * Filtri per la visualizzazione del flusso di ricevute
	 */
	public static final String ACTION_VISUALIZZA_FLUSSO_RICEVUTA		= "ACTION_VISUALIZZA_FLUSSO_RICEVUTA";
	
	public static final String FRIC_DATA_ESITO_CHECK	 				= "FRIC_DATA_ESITO_CHECK";
	public static final String FRIC_DATA_ESITO_DA	 					= "FRIC_DATA_ESITO_DA";
	public static final String FRIC_DATA_ESITO_A 						= "FRIC_DATA_ESITO_A";
	
	public static final String FRIC_CODICE_IUD							= "FRIC_CODICE_IUD";
	public static final String FRIC_CODICE_IUV							= "FRIC_CODICE_IUV";
	public static final String FRIC_CODICE_IUF							= "FRIC_CODICE_IUF";
	public static final String FRIC_DENOMINAZIONE_ATTESTANTE			= "FRIC_DENOMINAZIONE_ATTESTANTE";
	public static final String FRIC_ID_UNIVOCO_RISCOSSIONE				= "FRIC_ID_UNIVOCO_RISCOSSIONE";
	public static final String FRIC_COD_ID_UNIVOCO_PAGATORE				= "FRIC_COD_ID_UNIVOCO_PAGATORE";
	public static final String FRIC_ANAGRAFICA_PAGATORE					= "FRIC_ANAGRAFICA_PAGATORE";
	public static final String FRIC_COD_ID_UNIVOCO_VERSANTE				= "FRIC_COD_ID_UNIVOCO_VERSANTE";
	public static final String FRIC_ANAGRAFICA_VERSANTE					= "FRIC_ANAGRAFICA_VERSANTE";
	public static final String FRIC_COD_TIPO_DOVUTO						= "FRIC_COD_TIPO_DOVUTO";
	public static final String FRIC_PG 									= "FRIC_PG";
	public static final String FRIC_PG_SIZE 							= "FRIC_PG_SIZE";
	public static final String FRIC_TOTAL_RECORDS						= "FRIC_TOTAL_RECORDS";

	/**
	 * Filtri della form di ricerca anagrafica ufficio- capitolo - accertamento.
	 */
	public static final String ANAGRAFICA_UCA_PAGE_SIZE						= "ANAGRAFICA_UCA_PAGE_SIZE";
	public static final String ANAGRAFICA_UCA_PAGE							= "ANAGRAFICA_UCA_PAGE";
	public static final String ANAGRAFICA_UCA_CODICE_TIPO_DOVUTO			= "ANAGRAFICA_UCA_CODICE_TIPO_DOVUTO";
	public static final String ANAGRAFICA_UCA_CODICE_UFFICIO				= "ANAGRAFICA_UCA_CODICE_UFFICIO";
	public static final String ANAGRAFICA_UCA_DENOMINAZIONE_UFFICIO			= "ANAGRAFICA_UCA_DENOMINAZIONE_UFFICIO";
	public static final String ANAGRAFICA_UCA_CODICE_CAPITOLO				= "ANAGRAFICA_UCA_CODICE_CAPITOLO";
	public static final String ANAGRAFICA_UCA_DENOMINAZIONE_CAPITOLO		= "ANAGRAFICA_UCA_DENOMINAZIONE_CAPITOLO";
	public static final String ANAGRAFICA_UCA_CODICE_ACCERTAMENTO			= "ANAGRAFICA_UCA_CODICE_ACCERTAMENTO";
	public static final String ANAGRAFICA_UCA_DENOMINAZIONE_ACCERTAMENTO	= "ANAGRAFICA_UCA_DENOMINAZIONE_ACCERTAMENTO";
	public static final String ANAGRAFICA_UCA_FLG_ATTIVO					= "ANAGRAFICA_UCA_FLG_ATTIVO";
	public static final String ANAGRAFICA_UCA_ANNO_ESERCIZIO				= "ANAGRAFICA_UCA_ANNO_ESERCIZIO";
	
	public static final String ACTION_ANAGRAFICA_UCA_RICERCA 				= "ACTION_ANAGRAFICA_UCA_RICERCA";

	/**
	 * Key per recuparare l'ggetto contenente i filtri in sessione della view di ricerca dei "Totali per Anno/Mese/Giorno"
	 */
	public static final String ACTION_STATISTICA_AMG 		  = "ACTION_STATISTICA_ANNO_MESE_GIORNO";
	/**
	 * Key per recuparare l'ggetto contenente i filtri in sessione della view di ricerca dei "Totali ripartiti per Ufficio"
	 */
	public static final String ACTION_STATISTICA_UFFICI 	  = "ACTION_STATISTICA_UFFICI";
	/**
	 * Key per recuparare l'ggetto contenente i filtri in sessione della view di ricerca dei "Totali ripartiti per Tipi Dovuto"
	 */
	public static final String ACTION_STATISTICA_TIPI_DOVUTO  = "ACTION_STATISTICA_TIPI_DOVUTO";
	/**
	 * Key per recuparare l'ggetto contenente i filtri in sessione della view di ricerca dei "Totali ripartiti per Capitoli"
	 */
	public static final String ACTION_STATISTICA_CAPITOLI  = "ACTION_STATISTICA_CAPITOLI";
	/**
	 * Key per recuparare l'ggetto contenente i filtri in sessione della view di ricerca dei "Totali ripartiti per Accertamenti"
	 */
	public static final String ACTION_STATISTICA_ACCERTAMENTI = "ACTION_STATISTICA_ACCERTAMENTI";
	/**
	 * Key per recuparare l'ggetto contenente i filtri in sessione della view di dettaglio del cruscotto.
	 */
	public static final String ACTION_STATISTICA_DETTAGLIO_CRUSCOTTO = "ACTION_STATISTICA_DETTAGLIO_CRUSCOTTO";
	/**
	 * Filtri delle form di ricerca delle statistiche.
	 */
	public static final String STATISTICHE_TIPOLOGIA 				= "STATISTICHE_TIPOLOGIA";
	public static final String STATISTICHE_CHECK_IMPORTI_PAGATI 	= "STATISTICHE_CHECK_IMPORTI_PAGATI";
	public static final String STATISTICHE_CHECK_IMPORTI_REND 		= "STATISTICHE_CHECK_IMPORTI_RENDICONTATI";
	public static final String STATISTICHE_CHECK_IMPORTI_INCA 		= "STATISTICHE_CHECK_IMPORTI_INCASSATI";
	public static final String STATISTICHE_CHECK_ANNO 				= "STATISTICHE_CHECK_ANNO";
	public static final String STATISTICHE_CHECK_ANNO_MESE 			= "STATISTICHE_CHECK_ANNO_MESE";
	public static final String STATISTICHE_CHECK_ANNO_MESE_GIORNO 	= "STATISTICHE_CHECK_ANNO_MESE_GIORNO";
	public static final String STATISTICHE_LISTA_ANNI 				= "STATISTICHE_LISTA_ANNI";
	public static final String STATISTICHE_LISTA_MESI 				= "STATISTICHE_LISTA_MESI";
	public static final String STATISTICHE_GIORNO_DAL 				= "STATISTICHE_GIORNO_DAL";
	public static final String STATISTICHE_GIORNO_AL 				= "STATISTICHE_GIORNO_AL";
	public static final String STATISTICHE_ANNO 					= "STATISTICHE_ANNO";
	public static final String STATISTICHE_MESE 					= "STATISTICHE_MESE";
	public static final String STATISTICHE_GIORNO 					= "STATISTICHE_GIORNO";
	public static final String STATISTICHE_CODICE_TIPO_DOVUTO 		= "STATISTICHE_CODICE_TIPO_DOVUTO";
	public static final String STATISTICHE_CODICE_UFFICIO 			= "STATISTICHE_CODICE_UFFICIO";
	public static final String STATISTICHE_CODICE_CAPITOLO 			= "STATISTICHE_CODICE_CAPITOLO";
	public static final String STATISTICHE_LISTA_IUD 				= "STATISTICHE_LISTA_IUD";
}
