package it.tasgroup.idp.notification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-11T14:51:37.894+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://idp.tasgroup.it/Notification/", name = "NotificationService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NotificationService {

    @WebResult(name = "countNotificheResponse", targetNamespace = "http://idp.tasgroup.it/Notification/", partName = "parameters")
    @WebMethod(action = "http://idp.tasgroup.it/Notification/countNotifiche")
    public CountNotificheResponse countNotifiche(
        @WebParam(partName = "parameters", name = "countNotificheRequest", targetNamespace = "http://idp.tasgroup.it/Notification/")
        CountNotificheRequest parameters
    );

    @WebResult(name = "getFileNotificaResponse", targetNamespace = "http://idp.tasgroup.it/Notification/", partName = "parameters")
    @WebMethod(action = "http://idp.tasgroup.it/Notification/getFileNotifica")
    public GetFileNotificaResponse getFileNotifica(
        @WebParam(partName = "parameters", name = "getFileNotificaRequest", targetNamespace = "http://idp.tasgroup.it/Notification/")
        GetFileNotificaRequest parameters
    );

    @WebResult(name = "listaNotificheResponse", targetNamespace = "http://idp.tasgroup.it/Notification/", partName = "parameters")
    @WebMethod(action = "http://idp.tasgroup.it/Notification/listaNotifiche")
    public ListaNotificheResponse listaNotifiche(
        @WebParam(partName = "parameters", name = "listaNotificheRequest", targetNamespace = "http://idp.tasgroup.it/Notification/")
        ListaNotificheRequest parameters
    );

    @WebResult(name = "ackFileResponse", targetNamespace = "http://idp.tasgroup.it/Notification/", partName = "parameters")
    @WebMethod
    public AckFileResponse ackFileNotifica(
        @WebParam(partName = "parameters", name = "ackFileRequest", targetNamespace = "http://idp.tasgroup.it/Notification/")
        AckFileRequest parameters
    );
}
