package it.tasgroup.idp.xmlbillerservices.ws.notificapagamento;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-16T16:07:01.829+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "NotificaPagamento", 
                  wsdlLocation = "classpath:wsdl/NotificaPagamento.wsdl",
                  targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/NotificaPagamento/") 
public class NotificaPagamento_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idp.tasgroup.it/xmlbillerservices/ws/NotificaPagamento/", "NotificaPagamento");
    public final static QName NotificaPagamentoPort = new QName("http://idp.tasgroup.it/xmlbillerservices/ws/NotificaPagamento/", "NotificaPagamentoPort");
    static {
        URL url = NotificaPagamento_Service.class.getClassLoader().getResource("wsdl/NotificaPagamento.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(NotificaPagamento_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/NotificaPagamento.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public NotificaPagamento_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificaPagamento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificaPagamento_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns NotificaPagamentoPortType
     */
    @WebEndpoint(name = "NotificaPagamentoPort")
    public NotificaPagamentoPortType getNotificaPagamentoPort() {
        return super.getPort(NotificaPagamentoPort, NotificaPagamentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificaPagamentoPortType
     */
    @WebEndpoint(name = "NotificaPagamentoPort")
    public NotificaPagamentoPortType getNotificaPagamentoPort(WebServiceFeature... features) {
        return super.getPort(NotificaPagamentoPort, NotificaPagamentoPortType.class, features);
    }

}
