package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * EnteTipoDovuto generated by hbm2java
 */
@Entity
@Table(name = "mygov_ente_tipo_dovuto")
public class EnteTipoDovuto implements java.io.Serializable {

	private static final long serialVersionUID = -7205416441290609779L;
	private Long id;
	private Ente ente;
	private String codTipo;
	private String deTipo;

	public EnteTipoDovuto() {
	}

	public EnteTipoDovuto(Ente ente) {
		this.ente = ente;
	}

	public EnteTipoDovuto(Ente ente, String codTipo, String deTipo) {
		this.ente = ente;
		this.codTipo = codTipo;
		this.deTipo = deTipo;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_ente_tipo_dovuto_mygov_ente_tipo_dovuto_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "mygov_ente_tipo_dovuto_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_ente_id", nullable = false)
	public Ente getEnte() {
		return this.ente;
	}

	public void setEnte(Ente ente) {
		this.ente = ente;
	}

	@Column(name = "cod_tipo", length = 64)
	public String getCodTipo() {
		return this.codTipo;
	}

	public void setCodTipo(String codTipo) {
		this.codTipo = codTipo;
	}

	@Column(name = "de_tipo", length = 256)
	public String getDeTipo() {
		return this.deTipo;
	}

	public void setDeTipo(String deTipo) {
		this.deTipo = deTipo;
	}

}
