package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 3:08:30 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ente generated by hbm2java
 */
@Entity
@Table(name = "mygov_ente", uniqueConstraints = @UniqueConstraint(columnNames = "cod_ipa_ente"))
public class Ente implements java.io.Serializable {

	private Long id;
	private String codIpaEnte;
	private String codiceFiscaleEnte;
	private String deNomeEnte;
	private String emailAmministratore;
	private Date dtCreazione;
	private Date dtUltimaModifica;
	private String myboxClientKey;
	private String myboxClientSecret;
	private int numGiorniPagamentoPresunti;
	private boolean flgPagati;
	private boolean flgTesoreria;

	public Ente() {
	}

	public Ente(String codIpaEnte, String codiceFiscaleEnte, String deNomeEnte, Date dtCreazione, Date dtUltimaModifica,
			int numGiorniPagamentoPresunti, boolean flgPagati, boolean flgTesoreria) {
		this.codIpaEnte = codIpaEnte;
		this.codiceFiscaleEnte = codiceFiscaleEnte;
		this.deNomeEnte = deNomeEnte;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.numGiorniPagamentoPresunti = numGiorniPagamentoPresunti;
		this.flgPagati = flgPagati;
		this.flgTesoreria = flgTesoreria;
	}

	public Ente(String codIpaEnte, String codiceFiscaleEnte, String deNomeEnte, String emailAmministratore,
			Date dtCreazione, Date dtUltimaModifica, String myboxClientKey, String myboxClientSecret,
			int numGiorniPagamentoPresunti, boolean flgPagati, boolean flgTesoreria) {
		this.codIpaEnte = codIpaEnte;
		this.codiceFiscaleEnte = codiceFiscaleEnte;
		this.deNomeEnte = deNomeEnte;
		this.emailAmministratore = emailAmministratore;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.myboxClientKey = myboxClientKey;
		this.myboxClientSecret = myboxClientSecret;
		this.numGiorniPagamentoPresunti = numGiorniPagamentoPresunti;
		this.flgPagati = flgPagati;
		this.flgTesoreria = flgTesoreria;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_ente_mygov_ente_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_ente_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "cod_ipa_ente", unique = true, nullable = false, length = 80)
	public String getCodIpaEnte() {
		return this.codIpaEnte;
	}

	public void setCodIpaEnte(String codIpaEnte) {
		this.codIpaEnte = codIpaEnte;
	}

	@Column(name = "codice_fiscale_ente", nullable = false, length = 11)
	public String getCodiceFiscaleEnte() {
		return this.codiceFiscaleEnte;
	}

	public void setCodiceFiscaleEnte(String codiceFiscaleEnte) {
		this.codiceFiscaleEnte = codiceFiscaleEnte;
	}

	@Column(name = "de_nome_ente", nullable = false, length = 100)
	public String getDeNomeEnte() {
		return this.deNomeEnte;
	}

	public void setDeNomeEnte(String deNomeEnte) {
		this.deNomeEnte = deNomeEnte;
	}

	@Column(name = "email_amministratore", length = 50)
	public String getEmailAmministratore() {
		return this.emailAmministratore;
	}

	public void setEmailAmministratore(String emailAmministratore) {
		this.emailAmministratore = emailAmministratore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@Column(name = "mybox_client_key", length = 256)
	public String getMyboxClientKey() {
		return this.myboxClientKey;
	}

	public void setMyboxClientKey(String myboxClientKey) {
		this.myboxClientKey = myboxClientKey;
	}

	@Column(name = "mybox_client_secret", length = 256)
	public String getMyboxClientSecret() {
		return this.myboxClientSecret;
	}

	public void setMyboxClientSecret(String myboxClientSecret) {
		this.myboxClientSecret = myboxClientSecret;
	}

	@Column(name = "num_giorni_pagamento_presunti", nullable = false)
	public int getNumGiorniPagamentoPresunti() {
		return this.numGiorniPagamentoPresunti;
	}

	public void setNumGiorniPagamentoPresunti(int numGiorniPagamentoPresunti) {
		this.numGiorniPagamentoPresunti = numGiorniPagamentoPresunti;
	}

	@Column(name = "flg_pagati", nullable = false)
	public boolean isFlgPagati() {
		return this.flgPagati;
	}

	public void setFlgPagati(boolean flgPagati) {
		this.flgPagati = flgPagati;
	}

	@Column(name = "flg_tesoreria", nullable = false)
	public boolean isFlgTesoreria() {
		return this.flgTesoreria;
	}

	public void setFlgTesoreria(boolean flgTesoreria) {
		this.flgTesoreria = flgTesoreria;
	}
}
