package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Dec 12, 2017 10:01:03 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * FlussoTesoreria generated by hbm2java
 */
@Entity
@Table(name = "mygov_flusso_tesoreria", uniqueConstraints = @UniqueConstraint(columnNames = { "mygov_ente_id",
		"de_anno_bolletta", "cod_bolletta" }))
public class FlussoTesoreria implements java.io.Serializable {

	private Long id;
	private Ente ente;
	private String deAnnoBolletta;
	private String codBolletta;
	private String codConto;
	private String codIdDominio;
	private String codTipoMovimento;
	private String codCausale;
	private String deCausale;
	private BigDecimal numIpBolletta;
	private Date dtBolletta;
	private Date dtRicezione;
	private String deAnnoDocumento;
	private String codDocumento;
	private String codBollo;
	private String deCognome;
	private String deNome;
	private String deVia;
	private String deCap;
	private String deCitta;
	private String codCodiceFiscale;
	private String codPartitaIva;
	private String codAbi;
	private String codCab;
	private String codContoAnagrafica;
	private String deAeProvvisorio;
	private String codProvvisorio;
	private String codIban;
	private Character codTipoConto;
	private String codProcesso;
	private String codPgEsecuzione;
	private String codPgTrasferimento;
	private Long numPgProcesso;
	private Date dtDataValutaRegione;
	private String codIdUnivocoFlusso;
	private String codIdUnivocoVersamento;
	private Date dtCreazione;
	private Date dtUltimaModifica;
	private boolean flgRegolarizzata;
	private Date dtEffettivaSospeso;
	private String codiceGestionaleProvvisorio;

	public FlussoTesoreria() {
	}

	public FlussoTesoreria(Ente ente, String deAnnoBolletta, String codBolletta, String deCausale,
			BigDecimal numIpBolletta, Date dtBolletta, String deCognome, Date dtDataValutaRegione,
			boolean flgRegolarizzata) {
		this.ente = ente;
		this.deAnnoBolletta = deAnnoBolletta;
		this.codBolletta = codBolletta;
		this.deCausale = deCausale;
		this.numIpBolletta = numIpBolletta;
		this.dtBolletta = dtBolletta;
		this.deCognome = deCognome;
		this.dtDataValutaRegione = dtDataValutaRegione;
		this.flgRegolarizzata = flgRegolarizzata;
	}	

	public FlussoTesoreria(Ente ente, String deAnnoBolletta, String codBolletta, String codConto, String codIdDominio,
			String codTipoMovimento, String codCausale, String deCausale, BigDecimal numIpBolletta, Date dtBolletta,
			Date dtRicezione, String deAnnoDocumento, String codDocumento, String codBollo, String deCognome,
			String deNome, String deVia, String deCap, String deCitta, String codCodiceFiscale, String codPartitaIva,
			String codAbi, String codCab, String codContoAnagrafica, String deAeProvvisorio, String codProvvisorio,
			String codIban, Character codTipoConto, String codProcesso, String codPgEsecuzione,
			String codPgTrasferimento, Long numPgProcesso, Date dtDataValutaRegione, String codIdUnivocoFlusso,
			String codIdUnivocoVersamento, Date dtCreazione, Date dtUltimaModifica, boolean flgRegolarizzata,
			Date dtEffettivaSospeso, String codiceGestionaleProvvisorio) {
		this.ente = ente;
		this.deAnnoBolletta = deAnnoBolletta;
		this.codBolletta = codBolletta;
		this.codConto = codConto;
		this.codIdDominio = codIdDominio;
		this.codTipoMovimento = codTipoMovimento;
		this.codCausale = codCausale;
		this.deCausale = deCausale;
		this.numIpBolletta = numIpBolletta;
		this.dtBolletta = dtBolletta;
		this.dtRicezione = dtRicezione;
		this.deAnnoDocumento = deAnnoDocumento;
		this.codDocumento = codDocumento;
		this.codBollo = codBollo;
		this.deCognome = deCognome;
		this.deNome = deNome;
		this.deVia = deVia;
		this.deCap = deCap;
		this.deCitta = deCitta;
		this.codCodiceFiscale = codCodiceFiscale;
		this.codPartitaIva = codPartitaIva;
		this.codAbi = codAbi;
		this.codCab = codCab;
		this.codContoAnagrafica = codContoAnagrafica;
		this.deAeProvvisorio = deAeProvvisorio;
		this.codProvvisorio = codProvvisorio;
		this.codIban = codIban;
		this.codTipoConto = codTipoConto;
		this.codProcesso = codProcesso;
		this.codPgEsecuzione = codPgEsecuzione;
		this.codPgTrasferimento = codPgTrasferimento;
		this.numPgProcesso = numPgProcesso;
		this.dtDataValutaRegione = dtDataValutaRegione;
		this.codIdUnivocoFlusso = codIdUnivocoFlusso;
		this.codIdUnivocoVersamento = codIdUnivocoVersamento;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.flgRegolarizzata = flgRegolarizzata;
		this.dtEffettivaSospeso = dtEffettivaSospeso;
		this.codiceGestionaleProvvisorio = codiceGestionaleProvvisorio;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_flusso_tesoreria_mygov_flusso_tesoreria_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_flusso_tesoreria_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_ente_id", nullable = false)
	public Ente getEnte() {
		return this.ente;
	}

	public void setEnte(Ente ente) {
		this.ente = ente;
	}

	@Column(name = "de_anno_bolletta", nullable = false, length = 4)
	public String getDeAnnoBolletta() {
		return this.deAnnoBolletta;
	}

	public void setDeAnnoBolletta(String deAnnoBolletta) {
		this.deAnnoBolletta = deAnnoBolletta;
	}

	@Column(name = "cod_bolletta", nullable = false, length = 7)
	public String getCodBolletta() {
		return this.codBolletta;
	}

	public void setCodBolletta(String codBolletta) {
		this.codBolletta = codBolletta;
	}

	@Column(name = "cod_conto", length = 7)
	public String getCodConto() {
		return this.codConto;
	}

	public void setCodConto(String codConto) {
		this.codConto = codConto;
	}

	@Column(name = "cod_id_dominio", length = 7)
	public String getCodIdDominio() {
		return this.codIdDominio;
	}

	public void setCodIdDominio(String codIdDominio) {
		this.codIdDominio = codIdDominio;
	}

	@Column(name = "cod_tipo_movimento", length = 3)
	public String getCodTipoMovimento() {
		return this.codTipoMovimento;
	}

	public void setCodTipoMovimento(String codTipoMovimento) {
		this.codTipoMovimento = codTipoMovimento;
	}

	@Column(name = "cod_causale", length = 3)
	public String getCodCausale() {
		return this.codCausale;
	}

	public void setCodCausale(String codCausale) {
		this.codCausale = codCausale;
	}

	@Column(name = "de_causale", nullable = false, length = 2000)
	public String getDeCausale() {
		return this.deCausale;
	}

	public void setDeCausale(String deCausale) {
		this.deCausale = deCausale;
	}

	@Column(name = "num_ip_bolletta", nullable = false, precision = 17)
	public BigDecimal getNumIpBolletta() {
		return this.numIpBolletta;
	}

	public void setNumIpBolletta(BigDecimal numIpBolletta) {
		this.numIpBolletta = numIpBolletta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_bolletta", nullable = false, length = 13)
	public Date getDtBolletta() {
		return this.dtBolletta;
	}

	public void setDtBolletta(Date dtBolletta) {
		this.dtBolletta = dtBolletta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ricezione", length = 29)
	public Date getDtRicezione() {
		return this.dtRicezione;
	}

	public void setDtRicezione(Date dtRicezione) {
		this.dtRicezione = dtRicezione;
	}

	@Column(name = "de_anno_documento", length = 4)
	public String getDeAnnoDocumento() {
		return this.deAnnoDocumento;
	}

	public void setDeAnnoDocumento(String deAnnoDocumento) {
		this.deAnnoDocumento = deAnnoDocumento;
	}

	@Column(name = "cod_documento", length = 7)
	public String getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	@Column(name = "cod_bollo", length = 6)
	public String getCodBollo() {
		return this.codBollo;
	}

	public void setCodBollo(String codBollo) {
		this.codBollo = codBollo;
	}

	@Column(name = "de_cognome", nullable = false, length = 30)
	public String getDeCognome() {
		return this.deCognome;
	}

	public void setDeCognome(String deCognome) {
		this.deCognome = deCognome;
	}

	@Column(name = "de_nome", length = 30)
	public String getDeNome() {
		return this.deNome;
	}

	public void setDeNome(String deNome) {
		this.deNome = deNome;
	}

	@Column(name = "de_via", length = 50)
	public String getDeVia() {
		return this.deVia;
	}

	public void setDeVia(String deVia) {
		this.deVia = deVia;
	}

	@Column(name = "de_cap", length = 5)
	public String getDeCap() {
		return this.deCap;
	}

	public void setDeCap(String deCap) {
		this.deCap = deCap;
	}

	@Column(name = "de_citta", length = 40)
	public String getDeCitta() {
		return this.deCitta;
	}

	public void setDeCitta(String deCitta) {
		this.deCitta = deCitta;
	}

	@Column(name = "cod_codice_fiscale", length = 16)
	public String getCodCodiceFiscale() {
		return this.codCodiceFiscale;
	}

	public void setCodCodiceFiscale(String codCodiceFiscale) {
		this.codCodiceFiscale = codCodiceFiscale;
	}

	@Column(name = "cod_partita_iva", length = 12)
	public String getCodPartitaIva() {
		return this.codPartitaIva;
	}

	public void setCodPartitaIva(String codPartitaIva) {
		this.codPartitaIva = codPartitaIva;
	}

	@Column(name = "cod_abi", length = 5)
	public String getCodAbi() {
		return this.codAbi;
	}

	public void setCodAbi(String codAbi) {
		this.codAbi = codAbi;
	}

	@Column(name = "cod_cab", length = 5)
	public String getCodCab() {
		return this.codCab;
	}

	public void setCodCab(String codCab) {
		this.codCab = codCab;
	}

	@Column(name = "cod_conto_anagrafica", length = 25)
	public String getCodContoAnagrafica() {
		return this.codContoAnagrafica;
	}

	public void setCodContoAnagrafica(String codContoAnagrafica) {
		this.codContoAnagrafica = codContoAnagrafica;
	}

	@Column(name = "de_ae_provvisorio", length = 4)
	public String getDeAeProvvisorio() {
		return this.deAeProvvisorio;
	}

	public void setDeAeProvvisorio(String deAeProvvisorio) {
		this.deAeProvvisorio = deAeProvvisorio;
	}

	@Column(name = "cod_provvisorio", length = 6)
	public String getCodProvvisorio() {
		return this.codProvvisorio;
	}

	public void setCodProvvisorio(String codProvvisorio) {
		this.codProvvisorio = codProvvisorio;
	}

	@Column(name = "cod_iban", length = 34)
	public String getCodIban() {
		return this.codIban;
	}

	public void setCodIban(String codIban) {
		this.codIban = codIban;
	}

	@Column(name = "cod_tipo_conto", length = 1)
	public Character getCodTipoConto() {
		return this.codTipoConto;
	}

	public void setCodTipoConto(Character codTipoConto) {
		this.codTipoConto = codTipoConto;
	}

	@Column(name = "cod_processo", length = 10)
	public String getCodProcesso() {
		return this.codProcesso;
	}

	public void setCodProcesso(String codProcesso) {
		this.codProcesso = codProcesso;
	}

	@Column(name = "cod_pg_esecuzione", length = 4)
	public String getCodPgEsecuzione() {
		return this.codPgEsecuzione;
	}

	public void setCodPgEsecuzione(String codPgEsecuzione) {
		this.codPgEsecuzione = codPgEsecuzione;
	}

	@Column(name = "cod_pg_trasferimento", length = 4)
	public String getCodPgTrasferimento() {
		return this.codPgTrasferimento;
	}

	public void setCodPgTrasferimento(String codPgTrasferimento) {
		this.codPgTrasferimento = codPgTrasferimento;
	}

	@Column(name = "num_pg_processo", precision = 17, scale = 0)
	public Long getNumPgProcesso() {
		return this.numPgProcesso;
	}

	public void setNumPgProcesso(Long numPgProcesso) {
		this.numPgProcesso = numPgProcesso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_valuta_regione", nullable = false, length = 13)
	public Date getDtDataValutaRegione() {
		return this.dtDataValutaRegione;
	}

	public void setDtDataValutaRegione(Date dtDataValutaRegione) {
		this.dtDataValutaRegione = dtDataValutaRegione;
	}

	@Column(name = "cod_id_univoco_flusso", length = 35)
	public String getCodIdUnivocoFlusso() {
		return this.codIdUnivocoFlusso;
	}

	public void setCodIdUnivocoFlusso(String codIdUnivocoFlusso) {
		this.codIdUnivocoFlusso = codIdUnivocoFlusso;
	}

	@Column(name = "cod_id_univoco_versamento", length = 35)
	public String getCodIdUnivocoVersamento() {
		return this.codIdUnivocoVersamento;
	}

	public void setCodIdUnivocoVersamento(String codIdUnivocoVersamento) {
		this.codIdUnivocoVersamento = codIdUnivocoVersamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@Column(name = "flg_regolarizzata", nullable = false)
	public boolean isFlgRegolarizzata() {
		return this.flgRegolarizzata;
	}

	public void setFlgRegolarizzata(boolean flgRegolarizzata) {
		this.flgRegolarizzata = flgRegolarizzata;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_effettiva_sospeso", length = 13)
	public Date getDtEffettivaSospeso() {
		return dtEffettivaSospeso;
	}

	public void setDtEffettivaSospeso(Date dtEffettivaSospeso) {
		this.dtEffettivaSospeso = dtEffettivaSospeso;
	}

	@Column(name = "codice_gestionale_provvisorio", length = 10)
	public String getCodiceGestionaleProvvisorio() {
		return codiceGestionaleProvvisorio;
	}

	public void setCodiceGestionaleProvvisorio(String codiceGestionaleProvvisorio) {
		this.codiceGestionaleProvvisorio = codiceGestionaleProvvisorio;
	}

}
