package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * FlussoRendicontazione generated by hbm2java
 */
@Entity
@Table(name = "mygov_flusso_rendicontazione")
public class FlussoRendicontazione implements java.io.Serializable {

	private FlussoRendicontazioneId id;
	private int version;
	private ManageFlusso manageFlusso;
	private Ente ente;
	private Date dtCreazione;
	private Date dtUltimaModifica;
	private String identificativoPsp;
	private String versioneOggetto;
	private String codIdentificativoFlusso;
	private Date dtDataOraFlusso;
	private String codIdentificativoUnivocoRegolamento;
	private Date dtDataRegolamento;
	private char codIstMittIdUnivMittTipoIdentificativoUnivoco;
	private String codIstMittIdUnivMittCodiceIdentificativoUnivoco;
	private String deIstMittDenominazioneMittente;
	private Character codIstRicevIdUnivRicevTipoIdentificativoUnivoco;
	private String codIstRicevIdUnivRicevCodiceIdentificativoUnivoco;
	private String deIstRicevDenominazioneRicevente;
	private long numNumeroTotalePagamenti;
	private BigDecimal numImportoTotalePagamenti;
	private BigDecimal numDatiSingPagamSingoloImportoPagato;
	private String codDatiSingPagamCodiceEsitoSingoloPagamento;
	private Date dtDatiSingPagamDataEsitoSingoloPagamento;
	private Date dtAcquisizione;
	private String codiceBicBancaDiRiversamento;

	public FlussoRendicontazione() {
	}

	public FlussoRendicontazione(FlussoRendicontazioneId id, ManageFlusso manageFlusso, Ente ente, Date dtCreazione,
			Date dtUltimaModifica, String identificativoPsp, String versioneOggetto, String codIdentificativoFlusso,
			Date dtDataOraFlusso, String codIdentificativoUnivocoRegolamento, Date dtDataRegolamento,
			char codIstMittIdUnivMittTipoIdentificativoUnivoco, String codIstMittIdUnivMittCodiceIdentificativoUnivoco,
			long numNumeroTotalePagamenti, BigDecimal numImportoTotalePagamenti,
			BigDecimal numDatiSingPagamSingoloImportoPagato, String codDatiSingPagamCodiceEsitoSingoloPagamento,
			Date dtDatiSingPagamDataEsitoSingoloPagamento, Date dtAcquisizione) {
		this.id = id;
		this.manageFlusso = manageFlusso;
		this.ente = ente;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.identificativoPsp = identificativoPsp;
		this.versioneOggetto = versioneOggetto;
		this.codIdentificativoFlusso = codIdentificativoFlusso;
		this.dtDataOraFlusso = dtDataOraFlusso;
		this.codIdentificativoUnivocoRegolamento = codIdentificativoUnivocoRegolamento;
		this.dtDataRegolamento = dtDataRegolamento;
		this.codIstMittIdUnivMittTipoIdentificativoUnivoco = codIstMittIdUnivMittTipoIdentificativoUnivoco;
		this.codIstMittIdUnivMittCodiceIdentificativoUnivoco = codIstMittIdUnivMittCodiceIdentificativoUnivoco;
		this.numNumeroTotalePagamenti = numNumeroTotalePagamenti;
		this.numImportoTotalePagamenti = numImportoTotalePagamenti;
		this.numDatiSingPagamSingoloImportoPagato = numDatiSingPagamSingoloImportoPagato;
		this.codDatiSingPagamCodiceEsitoSingoloPagamento = codDatiSingPagamCodiceEsitoSingoloPagamento;
		this.dtDatiSingPagamDataEsitoSingoloPagamento = dtDatiSingPagamDataEsitoSingoloPagamento;
		this.dtAcquisizione = dtAcquisizione;
	}

	public FlussoRendicontazione(FlussoRendicontazioneId id, ManageFlusso manageFlusso, Ente ente, Date dtCreazione,
			Date dtUltimaModifica, String identificativoPsp, String versioneOggetto, String codIdentificativoFlusso,
			Date dtDataOraFlusso, String codIdentificativoUnivocoRegolamento, Date dtDataRegolamento,
			char codIstMittIdUnivMittTipoIdentificativoUnivoco, String codIstMittIdUnivMittCodiceIdentificativoUnivoco,
			String deIstMittDenominazioneMittente, Character codIstRicevIdUnivRicevTipoIdentificativoUnivoco,
			String codIstRicevIdUnivRicevCodiceIdentificativoUnivoco, String deIstRicevDenominazioneRicevente,
			long numNumeroTotalePagamenti, BigDecimal numImportoTotalePagamenti,
			BigDecimal numDatiSingPagamSingoloImportoPagato, String codDatiSingPagamCodiceEsitoSingoloPagamento,
			Date dtDatiSingPagamDataEsitoSingoloPagamento, Date dtAcquisizione, String codiceBicBancaDiRiversamento) {
		this.id = id;
		this.manageFlusso = manageFlusso;
		this.ente = ente;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.identificativoPsp = identificativoPsp;
		this.versioneOggetto = versioneOggetto;
		this.codIdentificativoFlusso = codIdentificativoFlusso;
		this.dtDataOraFlusso = dtDataOraFlusso;
		this.codIdentificativoUnivocoRegolamento = codIdentificativoUnivocoRegolamento;
		this.dtDataRegolamento = dtDataRegolamento;
		this.codIstMittIdUnivMittTipoIdentificativoUnivoco = codIstMittIdUnivMittTipoIdentificativoUnivoco;
		this.codIstMittIdUnivMittCodiceIdentificativoUnivoco = codIstMittIdUnivMittCodiceIdentificativoUnivoco;
		this.deIstMittDenominazioneMittente = deIstMittDenominazioneMittente;
		this.codIstRicevIdUnivRicevTipoIdentificativoUnivoco = codIstRicevIdUnivRicevTipoIdentificativoUnivoco;
		this.codIstRicevIdUnivRicevCodiceIdentificativoUnivoco = codIstRicevIdUnivRicevCodiceIdentificativoUnivoco;
		this.deIstRicevDenominazioneRicevente = deIstRicevDenominazioneRicevente;
		this.numNumeroTotalePagamenti = numNumeroTotalePagamenti;
		this.numImportoTotalePagamenti = numImportoTotalePagamenti;
		this.numDatiSingPagamSingoloImportoPagato = numDatiSingPagamSingoloImportoPagato;
		this.codDatiSingPagamCodiceEsitoSingoloPagamento = codDatiSingPagamCodiceEsitoSingoloPagamento;
		this.dtDatiSingPagamDataEsitoSingoloPagamento = dtDatiSingPagamDataEsitoSingoloPagamento;
		this.dtAcquisizione = dtAcquisizione;
		this.codiceBicBancaDiRiversamento = codiceBicBancaDiRiversamento;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mygovEnteId", column = @Column(name = "mygov_ente_id", nullable = false)),
			@AttributeOverride(name = "codDatiSingPagamIdentificativoUnivocoVersamento", column = @Column(name = "cod_dati_sing_pagam_identificativo_univoco_versamento", nullable = false, length = 35)),
			@AttributeOverride(name = "codDatiSingPagamIdentificativoUnivocoRiscossione", column = @Column(name = "cod_dati_sing_pagam_identificativo_univoco_riscossione", nullable = false, length = 35)),
			@AttributeOverride(name = "indiceDatiSingoloPagamento", column = @Column(name = "indice_dati_singolo_pagamento", nullable = false)) })
	public FlussoRendicontazioneId getId() {
		return this.id;
	}

	public void setId(FlussoRendicontazioneId id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_manage_flusso_id", nullable = false)
	public ManageFlusso getManageFlusso() {
		return this.manageFlusso;
	}

	public void setManageFlusso(ManageFlusso manageFlusso) {
		this.manageFlusso = manageFlusso;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_ente_id", nullable = false, insertable = false, updatable = false)
	public Ente getEnte() {
		return this.ente;
	}

	public void setEnte(Ente ente) {
		this.ente = ente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@Column(name = "identificativo_psp", nullable = false, length = 35)
	public String getIdentificativoPsp() {
		return this.identificativoPsp;
	}

	public void setIdentificativoPsp(String identificativoPsp) {
		this.identificativoPsp = identificativoPsp;
	}

	@Column(name = "versione_oggetto", nullable = false, length = 16)
	public String getVersioneOggetto() {
		return this.versioneOggetto;
	}

	public void setVersioneOggetto(String versioneOggetto) {
		this.versioneOggetto = versioneOggetto;
	}

	@Column(name = "cod_identificativo_flusso", nullable = false, length = 35)
	public String getCodIdentificativoFlusso() {
		return this.codIdentificativoFlusso;
	}

	public void setCodIdentificativoFlusso(String codIdentificativoFlusso) {
		this.codIdentificativoFlusso = codIdentificativoFlusso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_data_ora_flusso", nullable = false, length = 29)
	public Date getDtDataOraFlusso() {
		return this.dtDataOraFlusso;
	}

	public void setDtDataOraFlusso(Date dtDataOraFlusso) {
		this.dtDataOraFlusso = dtDataOraFlusso;
	}

	@Column(name = "cod_identificativo_univoco_regolamento", nullable = false, length = 35)
	public String getCodIdentificativoUnivocoRegolamento() {
		return this.codIdentificativoUnivocoRegolamento;
	}

	public void setCodIdentificativoUnivocoRegolamento(String codIdentificativoUnivocoRegolamento) {
		this.codIdentificativoUnivocoRegolamento = codIdentificativoUnivocoRegolamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_regolamento", nullable = false, length = 13)
	public Date getDtDataRegolamento() {
		return this.dtDataRegolamento;
	}

	public void setDtDataRegolamento(Date dtDataRegolamento) {
		this.dtDataRegolamento = dtDataRegolamento;
	}

	@Column(name = "cod_ist_mitt_id_univ_mitt_tipo_identificativo_univoco", nullable = false, length = 1)
	public char getCodIstMittIdUnivMittTipoIdentificativoUnivoco() {
		return this.codIstMittIdUnivMittTipoIdentificativoUnivoco;
	}

	public void setCodIstMittIdUnivMittTipoIdentificativoUnivoco(char codIstMittIdUnivMittTipoIdentificativoUnivoco) {
		this.codIstMittIdUnivMittTipoIdentificativoUnivoco = codIstMittIdUnivMittTipoIdentificativoUnivoco;
	}

	@Column(name = "cod_ist_mitt_id_univ_mitt_codice_identificativo_univoco", nullable = false, length = 35)
	public String getCodIstMittIdUnivMittCodiceIdentificativoUnivoco() {
		return this.codIstMittIdUnivMittCodiceIdentificativoUnivoco;
	}

	public void setCodIstMittIdUnivMittCodiceIdentificativoUnivoco(
			String codIstMittIdUnivMittCodiceIdentificativoUnivoco) {
		this.codIstMittIdUnivMittCodiceIdentificativoUnivoco = codIstMittIdUnivMittCodiceIdentificativoUnivoco;
	}

	@Column(name = "de_ist_mitt_denominazione_mittente", length = 70)
	public String getDeIstMittDenominazioneMittente() {
		return this.deIstMittDenominazioneMittente;
	}

	public void setDeIstMittDenominazioneMittente(String deIstMittDenominazioneMittente) {
		this.deIstMittDenominazioneMittente = deIstMittDenominazioneMittente;
	}

	@Column(name = "cod_ist_ricev_id_univ_ricev_tipo_identificativo_univoco", length = 1)
	public Character getCodIstRicevIdUnivRicevTipoIdentificativoUnivoco() {
		return this.codIstRicevIdUnivRicevTipoIdentificativoUnivoco;
	}

	public void setCodIstRicevIdUnivRicevTipoIdentificativoUnivoco(
			Character codIstRicevIdUnivRicevTipoIdentificativoUnivoco) {
		this.codIstRicevIdUnivRicevTipoIdentificativoUnivoco = codIstRicevIdUnivRicevTipoIdentificativoUnivoco;
	}

	@Column(name = "cod_ist_ricev_id_univ_ricev_codice_identificativo_univoco", length = 35)
	public String getCodIstRicevIdUnivRicevCodiceIdentificativoUnivoco() {
		return this.codIstRicevIdUnivRicevCodiceIdentificativoUnivoco;
	}

	public void setCodIstRicevIdUnivRicevCodiceIdentificativoUnivoco(
			String codIstRicevIdUnivRicevCodiceIdentificativoUnivoco) {
		this.codIstRicevIdUnivRicevCodiceIdentificativoUnivoco = codIstRicevIdUnivRicevCodiceIdentificativoUnivoco;
	}

	@Column(name = "de_ist_ricev_denominazione_ricevente", length = 70)
	public String getDeIstRicevDenominazioneRicevente() {
		return this.deIstRicevDenominazioneRicevente;
	}

	public void setDeIstRicevDenominazioneRicevente(String deIstRicevDenominazioneRicevente) {
		this.deIstRicevDenominazioneRicevente = deIstRicevDenominazioneRicevente;
	}

	@Column(name = "num_numero_totale_pagamenti", nullable = false, precision = 15, scale = 0)
	public long getNumNumeroTotalePagamenti() {
		return this.numNumeroTotalePagamenti;
	}

	public void setNumNumeroTotalePagamenti(long numNumeroTotalePagamenti) {
		this.numNumeroTotalePagamenti = numNumeroTotalePagamenti;
	}

	@Column(name = "num_importo_totale_pagamenti", nullable = false, precision = 18)
	public BigDecimal getNumImportoTotalePagamenti() {
		return this.numImportoTotalePagamenti;
	}

	public void setNumImportoTotalePagamenti(BigDecimal numImportoTotalePagamenti) {
		this.numImportoTotalePagamenti = numImportoTotalePagamenti;
	}

	@Column(name = "num_dati_sing_pagam_singolo_importo_pagato", nullable = false, precision = 12)
	public BigDecimal getNumDatiSingPagamSingoloImportoPagato() {
		return this.numDatiSingPagamSingoloImportoPagato;
	}

	public void setNumDatiSingPagamSingoloImportoPagato(BigDecimal numDatiSingPagamSingoloImportoPagato) {
		this.numDatiSingPagamSingoloImportoPagato = numDatiSingPagamSingoloImportoPagato;
	}

	@Column(name = "cod_dati_sing_pagam_codice_esito_singolo_pagamento", nullable = false, length = 1)
	public String getCodDatiSingPagamCodiceEsitoSingoloPagamento() {
		return this.codDatiSingPagamCodiceEsitoSingoloPagamento;
	}

	public void setCodDatiSingPagamCodiceEsitoSingoloPagamento(String codDatiSingPagamCodiceEsitoSingoloPagamento) {
		this.codDatiSingPagamCodiceEsitoSingoloPagamento = codDatiSingPagamCodiceEsitoSingoloPagamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_dati_sing_pagam_data_esito_singolo_pagamento", nullable = false, length = 13)
	public Date getDtDatiSingPagamDataEsitoSingoloPagamento() {
		return this.dtDatiSingPagamDataEsitoSingoloPagamento;
	}

	public void setDtDatiSingPagamDataEsitoSingoloPagamento(Date dtDatiSingPagamDataEsitoSingoloPagamento) {
		this.dtDatiSingPagamDataEsitoSingoloPagamento = dtDatiSingPagamDataEsitoSingoloPagamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_acquisizione", nullable = false, length = 13)
	public Date getDtAcquisizione() {
		return this.dtAcquisizione;
	}

	public void setDtAcquisizione(Date dtAcquisizione) {
		this.dtAcquisizione = dtAcquisizione;
	}

	@Column(name = "codice_bic_banca_di_riversamento", length = 35)
	public String getCodiceBicBancaDiRiversamento() {
		return this.codiceBicBancaDiRiversamento;
	}

	public void setCodiceBicBancaDiRiversamento(String codiceBicBancaDiRiversamento) {
		this.codiceBicBancaDiRiversamento = codiceBicBancaDiRiversamento;
	}

}
