package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlussoExportId generated by hbm2java
 */
@Embeddable
public class FlussoExportId implements java.io.Serializable {

	private long mygovEnteId;
	private String codRpSilinviarpIdUnivocoVersamento;
	private String codEDatiPagDatiSingPagIdUnivocoRiscoss;
	private int indiceDatiSingoloPagamento;

	public FlussoExportId() {
	}

	public FlussoExportId(long mygovEnteId, String codRpSilinviarpIdUnivocoVersamento,
			String codEDatiPagDatiSingPagIdUnivocoRiscoss, int indiceDatiSingoloPagamento) {
		this.mygovEnteId = mygovEnteId;
		this.codRpSilinviarpIdUnivocoVersamento = codRpSilinviarpIdUnivocoVersamento;
		this.codEDatiPagDatiSingPagIdUnivocoRiscoss = codEDatiPagDatiSingPagIdUnivocoRiscoss;
		this.indiceDatiSingoloPagamento = indiceDatiSingoloPagamento;
	}

	@Column(name = "mygov_ente_id", nullable = false)
	public long getMygovEnteId() {
		return this.mygovEnteId;
	}

	public void setMygovEnteId(long mygovEnteId) {
		this.mygovEnteId = mygovEnteId;
	}

	@Column(name = "cod_rp_silinviarp_id_univoco_versamento", nullable = false, length = 35)
	public String getCodRpSilinviarpIdUnivocoVersamento() {
		return this.codRpSilinviarpIdUnivocoVersamento;
	}

	public void setCodRpSilinviarpIdUnivocoVersamento(String codRpSilinviarpIdUnivocoVersamento) {
		this.codRpSilinviarpIdUnivocoVersamento = codRpSilinviarpIdUnivocoVersamento;
	}

	@Column(name = "cod_e_dati_pag_dati_sing_pag_id_univoco_riscoss", nullable = false, length = 35)
	public String getCodEDatiPagDatiSingPagIdUnivocoRiscoss() {
		return this.codEDatiPagDatiSingPagIdUnivocoRiscoss;
	}

	public void setCodEDatiPagDatiSingPagIdUnivocoRiscoss(String codEDatiPagDatiSingPagIdUnivocoRiscoss) {
		this.codEDatiPagDatiSingPagIdUnivocoRiscoss = codEDatiPagDatiSingPagIdUnivocoRiscoss;
	}

	@Column(name = "indice_dati_singolo_pagamento", nullable = false)
	public int getIndiceDatiSingoloPagamento() {
		return this.indiceDatiSingoloPagamento;
	}

	public void setIndiceDatiSingoloPagamento(int indiceDatiSingoloPagamento) {
		this.indiceDatiSingoloPagamento = indiceDatiSingoloPagamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlussoExportId))
			return false;
		FlussoExportId castOther = (FlussoExportId) other;

		return (this.getMygovEnteId() == castOther.getMygovEnteId())
				&& ((this.getCodRpSilinviarpIdUnivocoVersamento() == castOther.getCodRpSilinviarpIdUnivocoVersamento())
						|| (this.getCodRpSilinviarpIdUnivocoVersamento() != null
								&& castOther.getCodRpSilinviarpIdUnivocoVersamento() != null
								&& this.getCodRpSilinviarpIdUnivocoVersamento()
										.equals(castOther.getCodRpSilinviarpIdUnivocoVersamento())))
				&& ((this.getCodEDatiPagDatiSingPagIdUnivocoRiscoss() == castOther
						.getCodEDatiPagDatiSingPagIdUnivocoRiscoss())
						|| (this.getCodEDatiPagDatiSingPagIdUnivocoRiscoss() != null
								&& castOther.getCodEDatiPagDatiSingPagIdUnivocoRiscoss() != null
								&& this.getCodEDatiPagDatiSingPagIdUnivocoRiscoss()
										.equals(castOther.getCodEDatiPagDatiSingPagIdUnivocoRiscoss())))
				&& (this.getIndiceDatiSingoloPagamento() == castOther.getIndiceDatiSingoloPagamento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMygovEnteId();
		result = 37 * result + (getCodRpSilinviarpIdUnivocoVersamento() == null ? 0
				: this.getCodRpSilinviarpIdUnivocoVersamento().hashCode());
		result = 37 * result + (getCodEDatiPagDatiSingPagIdUnivocoRiscoss() == null ? 0
				: this.getCodEDatiPagDatiSingPagIdUnivocoRiscoss().hashCode());
		result = 37 * result + this.getIndiceDatiSingoloPagamento();
		return result;
	}

}
