package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImportExportRendicontazioneTesoreriaId generated by hbm2java
 */
@Embeddable
public class ImportExportRendicontazioneTesoreriaId implements java.io.Serializable {

	private String codiceIpaEnte;
	private String codiceIuv;
	private String identificativoUnivocoRiscossione;
	private String identificativoFlussoRendicontazione;
	private String classificazioneCompletezza;

	public ImportExportRendicontazioneTesoreriaId() {
	}

	public ImportExportRendicontazioneTesoreriaId(String codiceIpaEnte, String codiceIuv,
			String identificativoUnivocoRiscossione, String identificativoFlussoRendicontazione,
			String classificazioneCompletezza) {
		this.codiceIpaEnte = codiceIpaEnte;
		this.codiceIuv = codiceIuv;
		this.identificativoUnivocoRiscossione = identificativoUnivocoRiscossione;
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
		this.classificazioneCompletezza = classificazioneCompletezza;
	}

	@Column(name = "codice_ipa_ente", length = 80)
	public String getCodiceIpaEnte() {
		return this.codiceIpaEnte;
	}

	public void setCodiceIpaEnte(String codiceIpaEnte) {
		this.codiceIpaEnte = codiceIpaEnte;
	}

	@Column(name = "codice_iuv", length = 35)
	public String getCodiceIuv() {
		return this.codiceIuv;
	}

	public void setCodiceIuv(String codiceIuv) {
		this.codiceIuv = codiceIuv;
	}

	@Column(name = "identificativo_univoco_riscossione", length = 35)
	public String getIdentificativoUnivocoRiscossione() {
		return this.identificativoUnivocoRiscossione;
	}

	public void setIdentificativoUnivocoRiscossione(String identificativoUnivocoRiscossione) {
		this.identificativoUnivocoRiscossione = identificativoUnivocoRiscossione;
	}

	@Column(name = "identificativo_flusso_rendicontazione", length = 35)
	public String getIdentificativoFlussoRendicontazione() {
		return this.identificativoFlussoRendicontazione;
	}

	public void setIdentificativoFlussoRendicontazione(String identificativoFlussoRendicontazione) {
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
	}

	@Column(name = "classificazione_completezza", length = 20)
	public String getClassificazioneCompletezza() {
		return this.classificazioneCompletezza;
	}

	public void setClassificazioneCompletezza(String classificazioneCompletezza) {
		this.classificazioneCompletezza = classificazioneCompletezza;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImportExportRendicontazioneTesoreriaId))
			return false;
		ImportExportRendicontazioneTesoreriaId castOther = (ImportExportRendicontazioneTesoreriaId) other;

		return ((this.getCodiceIpaEnte() == castOther.getCodiceIpaEnte())
				|| (this.getCodiceIpaEnte() != null && castOther.getCodiceIpaEnte() != null
						&& this.getCodiceIpaEnte().equals(castOther.getCodiceIpaEnte())))
				&& ((this.getCodiceIuv() == castOther.getCodiceIuv()) || (this.getCodiceIuv() != null
						&& castOther.getCodiceIuv() != null && this.getCodiceIuv().equals(castOther.getCodiceIuv())))
				&& ((this.getIdentificativoUnivocoRiscossione() == castOther.getIdentificativoUnivocoRiscossione())
						|| (this.getIdentificativoUnivocoRiscossione() != null
								&& castOther.getIdentificativoUnivocoRiscossione() != null
								&& this.getIdentificativoUnivocoRiscossione()
										.equals(castOther.getIdentificativoUnivocoRiscossione())))
				&& ((this.getIdentificativoFlussoRendicontazione() == castOther
						.getIdentificativoFlussoRendicontazione())
						|| (this.getIdentificativoFlussoRendicontazione() != null
								&& castOther.getIdentificativoFlussoRendicontazione() != null
								&& this.getIdentificativoFlussoRendicontazione()
										.equals(castOther.getIdentificativoFlussoRendicontazione())))
				&& ((this.getClassificazioneCompletezza() == castOther.getClassificazioneCompletezza())
						|| (this.getClassificazioneCompletezza() != null
								&& castOther.getClassificazioneCompletezza() != null
								&& this.getClassificazioneCompletezza()
										.equals(castOther.getClassificazioneCompletezza())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodiceIpaEnte() == null ? 0 : this.getCodiceIpaEnte().hashCode());
		result = 37 * result + (getCodiceIuv() == null ? 0 : this.getCodiceIuv().hashCode());
		result = 37 * result + (getIdentificativoUnivocoRiscossione() == null ? 0
				: this.getIdentificativoUnivocoRiscossione().hashCode());
		result = 37 * result + (getIdentificativoFlussoRendicontazione() == null ? 0
				: this.getIdentificativoFlussoRendicontazione().hashCode());
		result = 37 * result
				+ (getClassificazioneCompletezza() == null ? 0 : this.getClassificazioneCompletezza().hashCode());
		return result;
	}

}
