package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * InfoFlussoPosteWeb generated by hbm2java
 */
@Entity
@Table(name = "mygov_info_flusso_poste_web")
public class InfoFlussoPosteWeb implements java.io.Serializable {

	private Long id;
	private int version;
	private ManageFlusso manageFlusso;
	private String codIdentificativoUnivocoRegolamento;
	private Date dtDataRegolamento;
	private BigDecimal numImportoTotalePagamenti;
	private Date dtCreazione;
	private Date dtUltimaModifica;

	public InfoFlussoPosteWeb() {
	}

	public InfoFlussoPosteWeb(ManageFlusso manageFlusso, Date dtCreazione, Date dtUltimaModifica) {
		this.manageFlusso = manageFlusso;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	public InfoFlussoPosteWeb(ManageFlusso manageFlusso, String codIdentificativoUnivocoRegolamento,
			Date dtDataRegolamento, BigDecimal numImportoTotalePagamenti, Date dtCreazione, Date dtUltimaModifica) {
		this.manageFlusso = manageFlusso;
		this.codIdentificativoUnivocoRegolamento = codIdentificativoUnivocoRegolamento;
		this.dtDataRegolamento = dtDataRegolamento;
		this.numImportoTotalePagamenti = numImportoTotalePagamenti;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_info_flusso_poste_web_mygov_info_flusso_poste_web_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_info_flusso_poste_web_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_manage_flusso_id", nullable = false)
	public ManageFlusso getManageFlusso() {
		return this.manageFlusso;
	}

	public void setManageFlusso(ManageFlusso manageFlusso) {
		this.manageFlusso = manageFlusso;
	}

	@Column(name = "cod_identificativo_univoco_regolamento", length = 35)
	public String getCodIdentificativoUnivocoRegolamento() {
		return this.codIdentificativoUnivocoRegolamento;
	}

	public void setCodIdentificativoUnivocoRegolamento(String codIdentificativoUnivocoRegolamento) {
		this.codIdentificativoUnivocoRegolamento = codIdentificativoUnivocoRegolamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_regolamento", length = 13)
	public Date getDtDataRegolamento() {
		return this.dtDataRegolamento;
	}

	public void setDtDataRegolamento(Date dtDataRegolamento) {
		this.dtDataRegolamento = dtDataRegolamento;
	}

	@Column(name = "num_importo_totale_pagamenti", precision = 18)
	public BigDecimal getNumImportoTotalePagamenti() {
		return this.numImportoTotalePagamenti;
	}

	public void setNumImportoTotalePagamenti(BigDecimal numImportoTotalePagamenti) {
		this.numImportoTotalePagamenti = numImportoTotalePagamenti;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

}
