package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:48 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RendicontazioneTesoreriaSubset generated by hbm2java
 */
@Entity
@Table(name = "mygov_import_export_rendicontazione_tesoreria")
public class RendicontazioneTesoreriaSubset implements java.io.Serializable {

	private RendicontazioneTesoreriaSubsetId id;
	private Date dtDataEsecuzionePagamento;
	private String deDataEsecuzionePagamento;
	private String singoloImportoCommissioneCaricoPa;
	private String dataOraFlussoRendicontazione;
	private String identificativoUnivocoRegolamento;
	private Date dtDataRegolamento;
	private String deDataRegolamento;
	private String importoTotalePagamenti;
	private String codConto;
	private Date dtDataContabile;
	private String deDataContabile;
	private Date dtDataValuta;
	private String deDataValuta;
	private BigDecimal numImporto;
	private String deImporto;
	private String codOr1;
	private String deAnnoBolletta;
	private String codBolletta;
	private String codIdDominio;
	private Date dtRicezione;
	private String deDataRicezione;
	private String deAnnoDocumento;
	private String codDocumento;
	private String deAnnoProvvisorio;
	private String codProvvisorio;
	private String deCausaleT;
	private String classificazioneCompletezza;
	private Date dtDataUltimoAggiornamento;
	private String deDataUltimoAggiornamento;
	private String codIufKey;

	public RendicontazioneTesoreriaSubset() {
	}

	public RendicontazioneTesoreriaSubset(RendicontazioneTesoreriaSubsetId id) {
		this.id = id;
	}

	public RendicontazioneTesoreriaSubset(RendicontazioneTesoreriaSubsetId id, Date dtDataEsecuzionePagamento,
			String deDataEsecuzionePagamento, String singoloImportoCommissioneCaricoPa,
			String dataOraFlussoRendicontazione, String identificativoUnivocoRegolamento, Date dtDataRegolamento,
			String deDataRegolamento, String importoTotalePagamenti, String codConto, Date dtDataContabile,
			String deDataContabile, Date dtDataValuta, String deDataValuta, BigDecimal numImporto, String deImporto,
			String codOr1, String deAnnoBolletta, String codBolletta, String codIdDominio, Date dtRicezione,
			String deDataRicezione, String deAnnoDocumento, String codDocumento, String deAnnoProvvisorio,
			String codProvvisorio, String deCausaleT, String classificazioneCompletezza, Date dtDataUltimoAggiornamento,
			String deDataUltimoAggiornamento, String codIufKey) {
		this.id = id;
		this.dtDataEsecuzionePagamento = dtDataEsecuzionePagamento;
		this.deDataEsecuzionePagamento = deDataEsecuzionePagamento;
		this.singoloImportoCommissioneCaricoPa = singoloImportoCommissioneCaricoPa;
		this.dataOraFlussoRendicontazione = dataOraFlussoRendicontazione;
		this.identificativoUnivocoRegolamento = identificativoUnivocoRegolamento;
		this.dtDataRegolamento = dtDataRegolamento;
		this.deDataRegolamento = deDataRegolamento;
		this.importoTotalePagamenti = importoTotalePagamenti;
		this.codConto = codConto;
		this.dtDataContabile = dtDataContabile;
		this.deDataContabile = deDataContabile;
		this.dtDataValuta = dtDataValuta;
		this.deDataValuta = deDataValuta;
		this.numImporto = numImporto;
		this.deImporto = deImporto;
		this.codOr1 = codOr1;
		this.deAnnoBolletta = deAnnoBolletta;
		this.codBolletta = codBolletta;
		this.codIdDominio = codIdDominio;
		this.dtRicezione = dtRicezione;
		this.deDataRicezione = deDataRicezione;
		this.deAnnoDocumento = deAnnoDocumento;
		this.codDocumento = codDocumento;
		this.deAnnoProvvisorio = deAnnoProvvisorio;
		this.codProvvisorio = codProvvisorio;
		this.deCausaleT = deCausaleT;
		this.classificazioneCompletezza = classificazioneCompletezza;
		this.dtDataUltimoAggiornamento = dtDataUltimoAggiornamento;
		this.deDataUltimoAggiornamento = deDataUltimoAggiornamento;
		this.codIufKey = codIufKey;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codiceIpaEnte", column = @Column(name = "codice_ipa_ente", length = 80)),
			@AttributeOverride(name = "identificativoFlussoRendicontazione", column = @Column(name = "identificativo_flusso_rendicontazione", length = 35)) })
	public RendicontazioneTesoreriaSubsetId getId() {
		return this.id;
	}

	public void setId(RendicontazioneTesoreriaSubsetId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_esecuzione_pagamento", length = 13)
	public Date getDtDataEsecuzionePagamento() {
		return this.dtDataEsecuzionePagamento;
	}

	public void setDtDataEsecuzionePagamento(Date dtDataEsecuzionePagamento) {
		this.dtDataEsecuzionePagamento = dtDataEsecuzionePagamento;
	}

	@Column(name = "de_data_esecuzione_pagamento", length = 10)
	public String getDeDataEsecuzionePagamento() {
		return this.deDataEsecuzionePagamento;
	}

	public void setDeDataEsecuzionePagamento(String deDataEsecuzionePagamento) {
		this.deDataEsecuzionePagamento = deDataEsecuzionePagamento;
	}

	@Column(name = "singolo_importo_commissione_carico_pa", length = 15)
	public String getSingoloImportoCommissioneCaricoPa() {
		return this.singoloImportoCommissioneCaricoPa;
	}

	public void setSingoloImportoCommissioneCaricoPa(String singoloImportoCommissioneCaricoPa) {
		this.singoloImportoCommissioneCaricoPa = singoloImportoCommissioneCaricoPa;
	}

	@Column(name = "data_ora_flusso_rendicontazione", length = 19)
	public String getDataOraFlussoRendicontazione() {
		return this.dataOraFlussoRendicontazione;
	}

	public void setDataOraFlussoRendicontazione(String dataOraFlussoRendicontazione) {
		this.dataOraFlussoRendicontazione = dataOraFlussoRendicontazione;
	}

	@Column(name = "identificativo_univoco_regolamento", length = 35)
	public String getIdentificativoUnivocoRegolamento() {
		return this.identificativoUnivocoRegolamento;
	}

	public void setIdentificativoUnivocoRegolamento(String identificativoUnivocoRegolamento) {
		this.identificativoUnivocoRegolamento = identificativoUnivocoRegolamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_regolamento", length = 13)
	public Date getDtDataRegolamento() {
		return this.dtDataRegolamento;
	}

	public void setDtDataRegolamento(Date dtDataRegolamento) {
		this.dtDataRegolamento = dtDataRegolamento;
	}

	@Column(name = "de_data_regolamento")
	public String getDeDataRegolamento() {
		return this.deDataRegolamento;
	}

	public void setDeDataRegolamento(String deDataRegolamento) {
		this.deDataRegolamento = deDataRegolamento;
	}

	@Column(name = "importo_totale_pagamenti", length = 21)
	public String getImportoTotalePagamenti() {
		return this.importoTotalePagamenti;
	}

	public void setImportoTotalePagamenti(String importoTotalePagamenti) {
		this.importoTotalePagamenti = importoTotalePagamenti;
	}

	@Column(name = "cod_conto", length = 12)
	public String getCodConto() {
		return this.codConto;
	}

	public void setCodConto(String codConto) {
		this.codConto = codConto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_contabile", length = 13)
	public Date getDtDataContabile() {
		return this.dtDataContabile;
	}

	public void setDtDataContabile(Date dtDataContabile) {
		this.dtDataContabile = dtDataContabile;
	}

	@Column(name = "de_data_contabile", length = 10)
	public String getDeDataContabile() {
		return this.deDataContabile;
	}

	public void setDeDataContabile(String deDataContabile) {
		this.deDataContabile = deDataContabile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_valuta", length = 13)
	public Date getDtDataValuta() {
		return this.dtDataValuta;
	}

	public void setDtDataValuta(Date dtDataValuta) {
		this.dtDataValuta = dtDataValuta;
	}

	@Column(name = "de_data_valuta", length = 10)
	public String getDeDataValuta() {
		return this.deDataValuta;
	}

	public void setDeDataValuta(String deDataValuta) {
		this.deDataValuta = deDataValuta;
	}

	@Column(name = "num_importo", precision = 12)
	public BigDecimal getNumImporto() {
		return this.numImporto;
	}

	public void setNumImporto(BigDecimal numImporto) {
		this.numImporto = numImporto;
	}

	@Column(name = "de_importo", length = 15)
	public String getDeImporto() {
		return this.deImporto;
	}

	public void setDeImporto(String deImporto) {
		this.deImporto = deImporto;
	}

	@Column(name = "cod_or1")
	public String getCodOr1() {
		return this.codOr1;
	}

	public void setCodOr1(String codOr1) {
		this.codOr1 = codOr1;
	}

	@Column(name = "de_anno_bolletta", length = 4)
	public String getDeAnnoBolletta() {
		return this.deAnnoBolletta;
	}

	public void setDeAnnoBolletta(String deAnnoBolletta) {
		this.deAnnoBolletta = deAnnoBolletta;
	}

	@Column(name = "cod_bolletta", length = 7)
	public String getCodBolletta() {
		return this.codBolletta;
	}

	public void setCodBolletta(String codBolletta) {
		this.codBolletta = codBolletta;
	}

	@Column(name = "cod_id_dominio", length = 7)
	public String getCodIdDominio() {
		return this.codIdDominio;
	}

	public void setCodIdDominio(String codIdDominio) {
		this.codIdDominio = codIdDominio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ricezione", length = 29)
	public Date getDtRicezione() {
		return this.dtRicezione;
	}

	public void setDtRicezione(Date dtRicezione) {
		this.dtRicezione = dtRicezione;
	}

	@Column(name = "de_data_ricezione", length = 10)
	public String getDeDataRicezione() {
		return this.deDataRicezione;
	}

	public void setDeDataRicezione(String deDataRicezione) {
		this.deDataRicezione = deDataRicezione;
	}

	@Column(name = "de_anno_documento", length = 4)
	public String getDeAnnoDocumento() {
		return this.deAnnoDocumento;
	}

	public void setDeAnnoDocumento(String deAnnoDocumento) {
		this.deAnnoDocumento = deAnnoDocumento;
	}

	@Column(name = "cod_documento", length = 7)
	public String getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	@Column(name = "de_anno_provvisorio", length = 4)
	public String getDeAnnoProvvisorio() {
		return this.deAnnoProvvisorio;
	}

	public void setDeAnnoProvvisorio(String deAnnoProvvisorio) {
		this.deAnnoProvvisorio = deAnnoProvvisorio;
	}

	@Column(name = "cod_provvisorio", length = 6)
	public String getCodProvvisorio() {
		return this.codProvvisorio;
	}

	public void setCodProvvisorio(String codProvvisorio) {
		this.codProvvisorio = codProvvisorio;
	}

	@Column(name = "de_causale_t")
	public String getDeCausaleT() {
		return this.deCausaleT;
	}

	public void setDeCausaleT(String deCausaleT) {
		this.deCausaleT = deCausaleT;
	}

	@Column(name = "classificazione_completezza", length = 20)
	public String getClassificazioneCompletezza() {
		return this.classificazioneCompletezza;
	}

	public void setClassificazioneCompletezza(String classificazioneCompletezza) {
		this.classificazioneCompletezza = classificazioneCompletezza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_ultimo_aggiornamento", length = 13)
	public Date getDtDataUltimoAggiornamento() {
		return this.dtDataUltimoAggiornamento;
	}

	public void setDtDataUltimoAggiornamento(Date dtDataUltimoAggiornamento) {
		this.dtDataUltimoAggiornamento = dtDataUltimoAggiornamento;
	}

	@Column(name = "de_data_ultimo_aggiornamento", length = 10)
	public String getDeDataUltimoAggiornamento() {
		return this.deDataUltimoAggiornamento;
	}

	public void setDeDataUltimoAggiornamento(String deDataUltimoAggiornamento) {
		this.deDataUltimoAggiornamento = deDataUltimoAggiornamento;
	}

	@Column(name = "cod_iuf_key", length = 35)
	public String getCodIufKey() {
		return this.codIufKey;
	}

	public void setCodIufKey(String codIufKey) {
		this.codIufKey = codIufKey;
	}

}
