package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Segnalazione generated by hbm2java
 */
@Entity
@Table(name = "mygov_segnalazione")
public class Segnalazione implements java.io.Serializable {

	private Long id;
	private int version;
	private Ente ente;
	private Utente utente;
	private String classificazioneCompletezza;
	private String codIud;
	private String codIuv;
	private String codIuf;
	private String deNota;
	private boolean flgNascosto;
	private Boolean flgAttivo;
	private Date dtCreazione;
	private Date dtUltimaModifica;

	public Segnalazione() {
	}

	public Segnalazione(Ente ente, Utente utente, String classificazioneCompletezza, String deNota, boolean flgNascosto,
			Date dtCreazione, Date dtUltimaModifica) {
		this.ente = ente;
		this.utente = utente;
		this.classificazioneCompletezza = classificazioneCompletezza;
		this.deNota = deNota;
		this.flgNascosto = flgNascosto;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	public Segnalazione(Ente ente, Utente utente, String classificazioneCompletezza, String codIud, String codIuv,
			String codIuf, String deNota, boolean flgNascosto, Boolean flgAttivo, Date dtCreazione,
			Date dtUltimaModifica) {
		this.ente = ente;
		this.utente = utente;
		this.classificazioneCompletezza = classificazioneCompletezza;
		this.codIud = codIud;
		this.codIuv = codIuv;
		this.codIuf = codIuf;
		this.deNota = deNota;
		this.flgNascosto = flgNascosto;
		this.flgAttivo = flgAttivo;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_segnalazione_mygov_segnalazione_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_segnalazione_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_ente_id", nullable = false)
	public Ente getEnte() {
		return this.ente;
	}

	public void setEnte(Ente ente) {
		this.ente = ente;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_utente_id", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@Column(name = "classificazione_completezza", nullable = false, length = 20)
	public String getClassificazioneCompletezza() {
		return this.classificazioneCompletezza;
	}

	public void setClassificazioneCompletezza(String classificazioneCompletezza) {
		this.classificazioneCompletezza = classificazioneCompletezza;
	}

	@Column(name = "cod_iud", length = 35)
	public String getCodIud() {
		return this.codIud;
	}

	public void setCodIud(String codIud) {
		this.codIud = codIud;
	}

	@Column(name = "cod_iuv", length = 35)
	public String getCodIuv() {
		return this.codIuv;
	}

	public void setCodIuv(String codIuv) {
		this.codIuv = codIuv;
	}

	@Column(name = "cod_iuf", length = 35)
	public String getCodIuf() {
		return this.codIuf;
	}

	public void setCodIuf(String codIuf) {
		this.codIuf = codIuf;
	}

	@Column(name = "de_nota", nullable = false)
	public String getDeNota() {
		return this.deNota;
	}

	public void setDeNota(String deNota) {
		this.deNota = deNota;
	}

	@Column(name = "flg_nascosto", nullable = false)
	public boolean isFlgNascosto() {
		return this.flgNascosto;
	}

	public void setFlgNascosto(boolean flgNascosto) {
		this.flgNascosto = flgNascosto;
	}

	@Column(name = "flg_attivo")
	public Boolean getFlgAttivo() {
		return this.flgAttivo;
	}

	public void setFlgAttivo(Boolean flgAttivo) {
		this.flgAttivo = flgAttivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

}
