package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:45 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TesoreriaNoMatchSubsetId generated by hbm2java
 */
@Embeddable
public class TesoreriaNoMatchSubsetId implements java.io.Serializable {

	private String codiceIpaEnte;
	private String deAnnoBolletta;
	private String codBolletta;

	public TesoreriaNoMatchSubsetId() {
	}

	public TesoreriaNoMatchSubsetId(String codiceIpaEnte, String deAnnoBolletta, String codBolletta) {
		this.codiceIpaEnte = codiceIpaEnte;
		this.deAnnoBolletta = deAnnoBolletta;
		this.codBolletta = codBolletta;
	}

	@Column(name = "codice_ipa_ente", length = 80)
	public String getCodiceIpaEnte() {
		return this.codiceIpaEnte;
	}

	public void setCodiceIpaEnte(String codiceIpaEnte) {
		this.codiceIpaEnte = codiceIpaEnte;
	}

	@Column(name = "de_anno_bolletta", length = 4)
	public String getDeAnnoBolletta() {
		return this.deAnnoBolletta;
	}

	public void setDeAnnoBolletta(String deAnnoBolletta) {
		this.deAnnoBolletta = deAnnoBolletta;
	}

	@Column(name = "cod_bolletta", length = 7)
	public String getCodBolletta() {
		return this.codBolletta;
	}

	public void setCodBolletta(String codBolletta) {
		this.codBolletta = codBolletta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TesoreriaNoMatchSubsetId))
			return false;
		TesoreriaNoMatchSubsetId castOther = (TesoreriaNoMatchSubsetId) other;

		return ((this.getCodiceIpaEnte() == castOther.getCodiceIpaEnte())
				|| (this.getCodiceIpaEnte() != null && castOther.getCodiceIpaEnte() != null
						&& this.getCodiceIpaEnte().equals(castOther.getCodiceIpaEnte())))
				&& ((this.getDeAnnoBolletta() == castOther.getDeAnnoBolletta())
						|| (this.getDeAnnoBolletta() != null && castOther.getDeAnnoBolletta() != null
								&& this.getDeAnnoBolletta().equals(castOther.getDeAnnoBolletta())))
				&& ((this.getCodBolletta() == castOther.getCodBolletta())
						|| (this.getCodBolletta() != null && castOther.getCodBolletta() != null
								&& this.getCodBolletta().equals(castOther.getCodBolletta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodiceIpaEnte() == null ? 0 : this.getCodiceIpaEnte().hashCode());
		result = 37 * result + (getDeAnnoBolletta() == null ? 0 : this.getDeAnnoBolletta().hashCode());
		result = 37 * result + (getCodBolletta() == null ? 0 : this.getCodBolletta().hashCode());
		return result;
	}

}
