CREATE ROLE mybox LOGIN
  ENCRYPTED PASSWORD 'md5fc645d39b688ce4083d18a96d520c17f'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

  
CREATE DATABASE "mybox"
  WITH OWNER = "mybox"
       ENCODING = 'UTF8'
       CONNECTION LIMIT = -1;
