package it.toscana.rete.cart.servizi.iris_1_1.ws.idpallineamentopendenze;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2019-05-08T20:00:17.536+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", name = "ComunicazionePosizioniDebitorieOTF")
@XmlSeeAlso({it.toscana.rete.cart.servizi.iris_1_1.idpheader.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.idpallineamentopendenze.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.idpesito.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.idpinclude.ObjectFactory.class, it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpallineamentopendenze.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ComunicazionePosizioniDebitorieOTF {

    @WebResult(name = "IdpAllineamentoPendenzeEnteOTF.Esito", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", partName = "AllineamentoPendenzeEnteOTF.Esito")
    @WebMethod(operationName = "IdpAllineamentoPendenzeEnteOTF", action = "IdpAllineamentoPendenzeEnteOTF")
    public it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpallineamentopendenze.IdpAllineamentoPendenzeEnteOTFEsito idpAllineamentoPendenzeEnteOTF(
        @WebParam(partName = "AllineamentoPendenzeOTF", name = "IdpAllineamentoPendenzeEnteOTF", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy")
        it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpallineamentopendenze.IdpAllineamentoPendenzeEnteOTF allineamentoPendenzeOTF
    );

    @WebResult(name = "IdpAllineamentoPendenzeMultiEnteOTF.Esito", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", partName = "AllineamentoPendenzeEnteOTF.Esito")
    @WebMethod(operationName = "IdpAllineamentoPendenzeMultiEnteOTF", action = "IdpAllineamentoPendenzeMultiEnteOTF")
    public it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpallineamentopendenze.IdpAllineamentoPendenzeMultiEnteOTFEsito idpAllineamentoPendenzeMultiEnteOTF(
        @WebParam(partName = "AllineamentoPendenzeOTF", name = "IdpAllineamentoPendenzeMultiEnteOTF", targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy")
        it.toscana.rete.cart.servizi.iris_1_1.ws.proxy.idpallineamentopendenze.IdpAllineamentoPendenzeMultiEnteOTF allineamentoPendenzeOTF
    );
}
