package it.tasgroup.idp.cart.orm.monitoraggio;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import it.tasgroup.idp.cart.orm.monitoraggio.enums.EnumTipoMessaggio;

/**
 * The persistent class for the MESSAGGI_NON_GESTITI database table.
 * 
 */
@Entity
@Table(name="ssil_msg_non_gestiti")
public class MessaggiNonGestiti extends it.tasgroup.idp.domain.BaseIdEntity implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/***
	*
ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (NO CACHE),
	TIPO VARCHAR(255) NOT NULL,
	DATA_RICEZIONE TIMESTAMP NOT NULL,
	TIPO_MITTENTE VARCHAR(255),
	MITTENTE VARCHAR(255),
	ID_EGOV VARCHAR(255),
	COD_ERRORE VARCHAR(255),
	DESCR_ERRORE VARCHAR(255),

	OP_INSERIMENTO VARGRAPHIC(40) NOT NULL,
	TS_INSERIMENTO TIMESTAMP NOT NULL,
	OP_AGGIORNAMENTO VARGRAPHIC(40),
	TS_AGGIORNAMENTO TIMESTAMP,
	VERSION INTEGER NOT NULL DEFAULT 0
	 * 
	 */
	
	private EnumTipoMessaggio tipo;
	private String tipoMittente;
	private String mittente;
	private Date dataRicezione;
	private String idEgov;
	private String codErrore;
	private String descrErrore;
	
	
    /*** Id Mapping ***/
    /*** AUTO, works on DB2 with Identity ***/
    /*** AUTO + seqGenerator, works on Oracle with Sequences ***/
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
//    @GeneratedValue(
//                    strategy=GenerationType.AUTO,
//                    generator="messaggi_non_gestiti_pk_gen")
//    @SequenceGenerator(
//        name="messaggi_non_gestiti_pk_gen",
//        sequenceName="MESSAGGI_NON_GESTITI_ID_SEQ",
//        allocationSize=1)
    @Column(name="id")
    public Long getId() {
            return super.id;
    }
	
    @Column(name="tipo", nullable = false)
	@Enumerated(EnumType.STRING)
	public EnumTipoMessaggio getTipo() {
		return tipo;
	}
	public void setTipo(EnumTipoMessaggio tipo) {
		this.tipo = tipo;
	}
	
	@Column(name="tipo_mittente", nullable = false)
	public String getTipoMittente() {
		return tipoMittente;
	}
	public void setTipoMittente(String tipoMittente) {
		this.tipoMittente = tipoMittente;
	}
	
	@Column(name="mittente", nullable = false)
	public String getMittente() {
		return mittente;
	}
	public void setMittente(String mittente) {
		this.mittente = mittente;
	}
	
	@Column(name="data_ricezione", nullable = false)
	public Date getDataRicezione() {
		return dataRicezione;
	}
	public void setDataRicezione(Date dataRicezione) {
		this.dataRicezione = dataRicezione;
	}
	
	@Column(name="id_egov", nullable = true)
	public String getIdEgov() {
		return idEgov;
	}
	public void setIdEgov(String idEgov) {
		this.idEgov = idEgov;
	}
	
	@Column(name="cod_errore", nullable = false)
	public String getCodErrore() {
		return codErrore;
	}
	public void setCodErrore(String codErrore) {
		this.codErrore = codErrore;
	}
	
	@Column(name="descr_errore", nullable = false)
	public String getDescrErrore() {
		return descrErrore;
	}
	public void setDescrErrore(String descrErrore) {
		this.descrErrore = descrErrore;
	}

}
