package it.tasgroup.idp.xmlbillerservices.ws.verificapagamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-16T16:07:02.114+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento", name = "VerificaPagamentoPortType")
@XmlSeeAlso({it.tasgroup.idp.xmlbillerservices.header.ObjectFactory.class, ObjectFactory.class, it.tasgroup.idp.xmlbillerservices.informativapagamento.ObjectFactory.class, it.tasgroup.idp.xmlbillerservices.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VerificaPagamentoPortType {

    @WebResult(name = "VerificaPagamentoResponse", targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento", partName = "response")
    @WebMethod(operationName = "VerificaPagamento", action = "http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento/VerificaStatoPagamento")
    public VerificaPagamentoResponse verificaPagamento(
        @WebParam(partName = "request", name = "VerificaPagamento", targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento")
        VerificaPagamento request
    );
}
