package it.tasgroup.idp.xmlbillerservices.ws.verificapagamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-16T16:07:02.131+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "VerificaPagamentoService", 
                  wsdlLocation = "file:/home/user/projects/paytas-be/ebmonitor/IdpSchemiBillerServices/src/main/resources/wsdl/VerificaPagamento.wsdl",
                  targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento") 
public class VerificaPagamentoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento", "VerificaPagamentoService");
    public final static QName VerificaPagamentoPort = new QName("http://idp.tasgroup.it/xmlbillerservices/ws/VerificaPagamento", "VerificaPagamentoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/projects/paytas-be/ebmonitor/IdpSchemiBillerServices/src/main/resources/wsdl/VerificaPagamento.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VerificaPagamentoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/user/projects/paytas-be/ebmonitor/IdpSchemiBillerServices/src/main/resources/wsdl/VerificaPagamento.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VerificaPagamentoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VerificaPagamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificaPagamentoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns VerificaPagamentoPortType
     */
    @WebEndpoint(name = "VerificaPagamentoPort")
    public VerificaPagamentoPortType getVerificaPagamentoPort() {
        return super.getPort(VerificaPagamentoPort, VerificaPagamentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificaPagamentoPortType
     */
    @WebEndpoint(name = "VerificaPagamentoPort")
    public VerificaPagamentoPortType getVerificaPagamentoPort(WebServiceFeature... features) {
        return super.getPort(VerificaPagamentoPort, VerificaPagamentoPortType.class, features);
    }

}
