package it.nch.is.fo.pagamenti;

// Generated 14-ago-2009 15.50.22 by Hibernate Tools 3.2.4.GA

import it.nch.fwk.fo.dto.business.Pojo;
import it.tasgroup.iris.domain.BaseIdEntity;
import it.tasgroup.iris.domain.Pagamenti;

import java.sql.Timestamp;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Jltsil generated by hbm2java
 */
@Entity
@Table(name="MULTE")
@NamedQueries(
{
@NamedQuery(
		name="getMultaByTargaAndNumeroVerbale",
		query="select multa from Multe multa where targa = :targa and numeroVerbale = :numeroVerbale")
	}
)
public class Multe extends BaseIdEntity implements java.io.Serializable,Pojo{


    private String targa;
    private String numeroVerbale;
    private Timestamp dataVerbale;
    private String annoVerbale;
    private String serie;
    private String note;
    private String tipoverbale;
    private String opInserimento;
    private Timestamp tsInserimento;
    private String opAggiornamento;
    private Timestamp tsAggiornamento;
    
    private Pagamenti pagamento;
    
	private Long id;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO,generator="multe_pk_gen")	
	@SequenceGenerator(
		    name="multe_pk_gen",
		    sequenceName="T_MULTA_ID_SEQ",
		    allocationSize=1
		)	
	public Long getId() {
		return this.id;	 
	}	      
	public void setId(Long id) {		
		this.id = id;	 
	} 		

	@Column(name="ANNOVERBALE",length=4)
	public String getAnnoVerbale() {
		return this.annoVerbale;
	}

	public void setAnnoVerbale(String annoverbale) {
		this.annoVerbale = annoverbale;
	}


	@Column(name="DATAVERBALE")
	public Timestamp getDataVerbale() {
		return this.dataVerbale;
	}

	public void setDataVerbale(Timestamp dataverbale) {
		this.dataVerbale = dataverbale;
	}


	@Column(name="NOTE",length=200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}


	@Column(name="NUMEROVERBALE",nullable=false, length=50)
	public String getNumeroVerbale() {
		return this.numeroVerbale;
	}

	public void setNumeroVerbale(String numeroverbale) {
		this.numeroVerbale = numeroverbale;
	}


	@Column(name="OP_AGGIORNAMENTO", length=40)
	public String getOpAggiornamento() {
		return this.opAggiornamento;
	}

	public void setOpAggiornamento(String opAggiornamento) {
		this.opAggiornamento = opAggiornamento;
	}


	@Column(name="OP_INSERIMENTO", nullable=false, length=40)
	public String getOpInserimento() {
		return this.opInserimento;
	}

	public void setOpInserimento(String opInserimento) {
		this.opInserimento = opInserimento;
	}


	@Column(name="SERIE",length=50)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}


	@Column(name="TARGA",nullable=false, length=50)
	public String getTarga() {
		return this.targa;
	}

	public void setTarga(String targa) {
		this.targa = targa;
	}


	@Column(name="TIPOVERBALE",length=35)
	public String getTipoVerbale() {
		return this.tipoverbale;
	}

	public void setTipoVerbale(String tipoverbale) {
		this.tipoverbale = tipoverbale;
	}


	@Column(name="TS_AGGIORNAMENTO")
	public Timestamp getTsAggiornamento() {
		return this.tsAggiornamento;
	}

	public void setTsAggiornamento(Timestamp tsAggiornamento) {
		this.tsAggiornamento = tsAggiornamento;
	}


	@Column(name="TS_INSERIMENTO", nullable=false)
	public Timestamp getTsInserimento() {
		return this.tsInserimento;
	}

	public void setTsInserimento(Timestamp tsInserimento) {
		this.tsInserimento = tsInserimento;
	}
   

    //@OneToOne()
    //@JoinColumn(name="ID_PAGAMENTO")
    @Transient
	public Pagamenti getPagamento() {
		return pagamento;
	}


	public void setPagamento(Pagamenti pagamento) {
		this.pagamento = pagamento;
	}



	
	
}
