package it.tasgroup.idp.generazioneiuv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-11-13T13:16:47.641+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://idp.tasgroup.it/GenerazioneIUV/", name = "GenerazioneIUV")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GenerazioneIUV {

    @WebResult(name = "GeneraLottoIUVResponse", targetNamespace = "http://idp.tasgroup.it/GenerazioneIUV/", partName = "parameters")
    @WebMethod(operationName = "GeneraLottoIUV", action = "http://idp.tasgroup.it/GenerazioneIUV/GeneraLottoIUV")
    public GeneraLottoIUVResponseType generaLottoIUV(
        @WebParam(partName = "parameters", name = "GeneraLottoIUVRequest", targetNamespace = "http://idp.tasgroup.it/GenerazioneIUV/")
        GeneraLottoIUVRequest parameters
    );

    @WebResult(name = "GeneraIUVResponse", targetNamespace = "http://idp.tasgroup.it/GenerazioneIUV/", partName = "parameters")
    @WebMethod(operationName = "GeneraIUV", action = "http://idp.tasgroup.it/GenerazioneIUV/GeneraIUV")
    public GeneraIUVResponseType generaIUV(
        @WebParam(partName = "parameters", name = "GeneraIUVRequest", targetNamespace = "http://idp.tasgroup.it/GenerazioneIUV/")
        GeneraIUVRequest parameters
    );
}
