package it.tasgroup.idp.generazioneiuv;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-11-13T13:16:47.663+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "GenerazioneIUV", 
                  wsdlLocation = "classpath:wsdl/GenerazioneIUV.wsdl",
                  targetNamespace = "http://idp.tasgroup.it/GenerazioneIUV/") 
public class GenerazioneIUV_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idp.tasgroup.it/GenerazioneIUV/", "GenerazioneIUV");
    public final static QName GenerazioneIUVSOAP = new QName("http://idp.tasgroup.it/GenerazioneIUV/", "GenerazioneIUVSOAP");
    static {
        URL url = GenerazioneIUV_Service.class.getClassLoader().getResource("wsdl/GenerazioneIUV.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GenerazioneIUV_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GenerazioneIUV.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public GenerazioneIUV_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GenerazioneIUV_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerazioneIUV_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GenerazioneIUV
     */
    @WebEndpoint(name = "GenerazioneIUVSOAP")
    public GenerazioneIUV getGenerazioneIUVSOAP() {
        return super.getPort(GenerazioneIUVSOAP, GenerazioneIUV.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenerazioneIUV
     */
    @WebEndpoint(name = "GenerazioneIUVSOAP")
    public GenerazioneIUV getGenerazioneIUVSOAP(WebServiceFeature... features) {
        return super.getPort(GenerazioneIUVSOAP, GenerazioneIUV.class, features);
    }

}
