
package it.tasgroup.iris.comunication.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ComunicationPortType", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/")
public interface ComunicationPortType {


    /**
     * 
     * @param utente
     * @return
     *     returns java.util.List<it.tasgroup.iris.comunication.ws.impl.UtenteCanaleType>
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/getCanaliComunicazione")
    @WebResult(name = "UtenteCanaleResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCanaliComunicazione", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.GetCanaliComunicazione")
    @ResponseWrapper(localName = "getCanaliComunicazioneResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.GetCanaliComunicazioneResponse")
    public List<UtenteCanaleType> getCanaliComunicazione(
        @WebParam(name = "Utente", targetNamespace = "")
        UtenteType utente);

    /**
     * 
     * @param messaggio
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/sendMessageAgain")
    @RequestWrapper(localName = "sendMessageAgain", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SendMessageAgain")
    @ResponseWrapper(localName = "sendMessageAgainResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SendMessageAgainResponse")
    public void sendMessageAgain(
        @WebParam(name = "Messaggio", targetNamespace = "")
        List<MessaggioType> messaggio);

    /**
     * 
     * @return
     *     returns java.util.List<it.tasgroup.iris.comunication.ws.impl.CanaleType>
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/getCanaliConfigurazione")
    @WebResult(name = "CanaleResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCanaliConfigurazione", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.GetCanaliConfigurazione")
    @ResponseWrapper(localName = "getCanaliConfigurazioneResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.GetCanaliConfigurazioneResponse")
    public List<CanaleType> getCanaliConfigurazione();

    /**
     * 
     * @param tipoCanaleResponse
     * @param parametroCanale
     * @param subscriber
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/subscribeCanali")
    @RequestWrapper(localName = "subscribeCanali", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SubscribeCanali")
    @ResponseWrapper(localName = "subscribeCanaliResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SubscribeCanaliResponse")
    public void subscribeCanali(
        @WebParam(name = "Subscriber", targetNamespace = "")
        UtenteType subscriber,
        @WebParam(name = "TipoCanaleResponse", targetNamespace = "")
        TipoCanaleType tipoCanaleResponse,
        @WebParam(name = "ParametroCanale", targetNamespace = "")
        ParametroCanaleType parametroCanale);

    /**
     * 
     * @return
     *     returns java.util.List<it.tasgroup.iris.comunication.ws.impl.TipoMessaggioType>
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/getTipoMessaggio")
    @WebResult(name = "TipoMessaggioResponse", targetNamespace = "")
    @RequestWrapper(localName = "getTipoMessaggio", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.GetTipoMessaggio")
    @ResponseWrapper(localName = "getTipoMessaggioResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.GetTipoMessaggioResponse")
    public List<TipoMessaggioType> getTipoMessaggio();

    /**
     * 
     * @param tipoMessaggio
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/updateTipoMessaggio")
    @RequestWrapper(localName = "updateTipoMessaggio", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.UpdateTipoMessaggio")
    @ResponseWrapper(localName = "updateTipoMessaggioResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.UpdateTipoMessaggioResponse")
    public void updateTipoMessaggio(
        @WebParam(name = "TipoMessaggio", targetNamespace = "")
        TipoMessaggioType tipoMessaggio);

    /**
     * 
     * @param searchLogMessaggi
     * @return
     *     returns java.util.List<it.tasgroup.iris.comunication.ws.impl.LogMessaggioType>
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/elencoLogMessaggi")
    @WebResult(name = "LogMessaggiResponse", targetNamespace = "")
    @RequestWrapper(localName = "elencoLogMessaggi", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.ElencoLogMessaggi")
    @ResponseWrapper(localName = "elencoLogMessaggiResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.ElencoLogMessaggiResponse")
    public List<LogMessaggioType> elencoLogMessaggi(
        @WebParam(name = "searchLogMessaggi", targetNamespace = "")
        SearchLogMessaggiType searchLogMessaggi);

    /**
     * 
     * @param canale
     * @return
     *     returns it.tasgroup.iris.comunication.ws.impl.ValidoType
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/validaConfigurazioneCanale")
    @WebResult(name = "ValidoResponse", targetNamespace = "")
    @RequestWrapper(localName = "validaConfigurazioneCanale", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.ValidaConfigurazioneCanale")
    @ResponseWrapper(localName = "validaConfigurazioneCanaleResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.ValidaConfigurazioneCanaleResponse")
    public ValidoType validaConfigurazioneCanale(
        @WebParam(name = "Canale", targetNamespace = "")
        CanaleType canale);

    /**
     * 
     * @param tipoCanaleResponse
     * @param parametroCanale
     * @param subscriber
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/unsubscribeCanali")
    @RequestWrapper(localName = "unsubscribeCanali", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SubscribeCanali")
    @ResponseWrapper(localName = "unsubscribeCanaliResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SubscribeCanaliResponse")
    public void unsubscribeCanali(
        @WebParam(name = "Subscriber", targetNamespace = "")
        UtenteType subscriber,
        @WebParam(name = "TipoCanaleResponse", targetNamespace = "")
        TipoCanaleType tipoCanaleResponse,
        @WebParam(name = "ParametroCanale", targetNamespace = "")
        ParametroCanaleType parametroCanale);

    /**
     * 
     * @param canale
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/updateCanaliComunicazione")
    @RequestWrapper(localName = "updateCanaliComunicazione", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.UpdateCanaliComunicazione")
    @ResponseWrapper(localName = "updateCanaliComunicazioneResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.UpdateCanaliComunicazioneResponse")
    public void updateCanaliComunicazione(
        @WebParam(name = "Canale", targetNamespace = "")
        CanaleType canale);

    /**
     * 
     * @param messaggioLogico
     * @param utenti
     */
    @WebMethod(action = "http://localhost:8080/comunicationws/services/sendMessage")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", className = "it.tasgroup.iris.comunication.ws.impl.SendMessageResponse")
    public void sendMessage(
        @WebParam(name = "MessaggioLogico", targetNamespace = "")
        MessaggioLogicoType messaggioLogico,
        @WebParam(name = "Utenti", targetNamespace = "")
        List<UtenteType> utenti);

}
