
package it.tasgroup.iris.comunication.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ComunicazioneServiceImplService", targetNamespace = "http://impl.ws.comunication.iris.tasgroup.it/", wsdlLocation = "file:/C:/java/jboss-5.1.0.GA_noconf/bin/comunication.wsdl")
public class ComunicazioneServiceImplService
    extends Service
{

    private final static URL COMUNICAZIONESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.tasgroup.iris.comunication.ws.impl.ComunicazioneServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.tasgroup.iris.comunication.ws.impl.ComunicazioneServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/java/jboss-5.1.0.GA_noconf/bin/comunication.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/java/jboss-5.1.0.GA_noconf/bin/comunication.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMUNICAZIONESERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ComunicazioneServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComunicazioneServiceImplService() {
        super(COMUNICAZIONESERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.ws.comunication.iris.tasgroup.it/", "ComunicazioneServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ComunicationPortType
     */
    @WebEndpoint(name = "ComunicazioneServiceImplPort")
    public ComunicationPortType getComunicazioneServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.comunication.iris.tasgroup.it/", "ComunicazioneServiceImplPort"), ComunicationPortType.class);
    }

}
