package it.nch.is.fo.sistemienti;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 14-ago-2009 15.50.22 by Hibernate Tools 3.2.4.GA

/**
 * JltsilId generated by hbm2java
 */
@Embeddable
public class SistemaEnteId implements java.io.Serializable {

	private String idEnte;
	private String idSystem;

	public SistemaEnteId() {
	}

	public SistemaEnteId(String idEnte, String idSystem) {
		this.idEnte = idEnte;
		this.idSystem = idSystem;
	}

	@Column(name="ID_ENTE")
	public String getIdEnte() {
		return this.idEnte;
	}
	public void setIdEnte(String idEnte) {
		this.idEnte = idEnte;
	}

	@Column(name="ID_SYSTEM")
	public String getIdSystem() {
		return this.idSystem;
	}
	public void setIdSystem(String idSystem) {
		this.idSystem = idSystem;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEnte == null) ? 0 : idEnte.hashCode());
		result = prime * result
				+ ((idSystem == null) ? 0 : idSystem.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SistemaEnteId other = (SistemaEnteId) obj;
		if (idEnte == null) {
			if (other.idEnte != null)
				return false;
		} else if (!idEnte.equals(other.idEnte))
			return false;
		if (idSystem == null) {
			if (other.idSystem != null)
				return false;
		} else if (!idSystem.equals(other.idSystem))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "SistemaEnteId [idEnte=" + idEnte + ", idSystem=" + idSystem
				+ "]";
	}


}
