package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematicirt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-12-17T16:55:22.883+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", name = "PagamentiTelematiciRT")
@XmlSeeAlso({gov.telematici.pagamenti.ws.ppthead.ObjectFactory.class, gov.telematici.pagamenti.ws.ObjectFactory.class})
public interface PagamentiTelematiciRT {

    @WebResult(name = "paaInviaRichiestaRevocaRisposta", targetNamespace = "")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRichiestaRevocaRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRichiestaRevocaRisposta")
    @RequestWrapper(localName = "paaInviaRichiestaRevoca", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "gov.telematici.pagamenti.ws.PaaInviaRichiestaRevoca")
    @WebMethod(action = "paaInviaRichiestaRevoca")
    @ResponseWrapper(localName = "paaInviaRichiestaRevocaRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "gov.telematici.pagamenti.ws.PaaInviaRichiestaRevocaRisposta")
    public gov.telematici.pagamenti.ws.TipoInviaRichiestaRevocaRisposta paaInviaRichiestaRevoca(
        @WebParam(name = "identificativoDominio", targetNamespace = "")
        java.lang.String identificativoDominio,
        @WebParam(name = "identificativoUnivocoVersamento", targetNamespace = "")
        java.lang.String identificativoUnivocoVersamento,
        @WebParam(name = "codiceContestoPagamento", targetNamespace = "")
        java.lang.String codiceContestoPagamento,
        @WebParam(name = "rr", targetNamespace = "")
        byte[] rr
    );

    @WebResult(name = "paaInviaEsitoStornoRisposta", targetNamespace = "")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaEsitoStornoRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaEsitoStornoRisposta")
    @RequestWrapper(localName = "paaInviaEsitoStorno", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "gov.telematici.pagamenti.ws.PaaInviaEsitoStorno")
    @WebMethod(action = "paaInviaEsitoStorno")
    @ResponseWrapper(localName = "paaInviaEsitoStornoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "gov.telematici.pagamenti.ws.PaaInviaEsitoStornoRisposta")
    public gov.telematici.pagamenti.ws.TipoInviaEsitoStornoRisposta paaInviaEsitoStorno(
        @WebParam(name = "identificativoIntermediarioPA", targetNamespace = "")
        java.lang.String identificativoIntermediarioPA,
        @WebParam(name = "identificativoStazioneIntermediarioPA", targetNamespace = "")
        java.lang.String identificativoStazioneIntermediarioPA,
        @WebParam(name = "identificativoDominio", targetNamespace = "")
        java.lang.String identificativoDominio,
        @WebParam(name = "identificativoUnivocoVersamento", targetNamespace = "")
        java.lang.String identificativoUnivocoVersamento,
        @WebParam(name = "codiceContestoPagamento", targetNamespace = "")
        java.lang.String codiceContestoPagamento,
        @WebParam(name = "er", targetNamespace = "")
        byte[] er
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "paaInviaRTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRTRisposta")
    @WebMethod(action = "paaInviaRT")
    public gov.telematici.pagamenti.ws.PaaInviaRTRisposta paaInviaRT(
        @WebParam(partName = "bodyrichiesta", name = "paaInviaRT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.PaaInviaRT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );
}
