CREATE VIEW mygov_export_rendicontazione AS

SELECT export.mygov_ente_id as mygov_ente_id, 
       export.de_nome_flusso as nome_flusso_import_ente, 
       export.num_riga_flusso as riga_flusso_import_ente, 
       export.cod_iud as codice_iud, 
       export.cod_rp_silinviarp_id_univoco_versamento as codice_iuv, 
       export.de_e_versione_oggetto as versione_oggetto,
       export.cod_e_dom_id_dominio as identificativo_dominio, 
       export.cod_e_dom_id_stazione_richiedente as identificativo_stazione_richiedente, 
       export.cod_e_id_messaggio_ricevuta as identificativo_messaggio_ricevuta, 
       export.dt_e_data_ora_messaggio_ricevuta as data_ora_messaggio_ricevuta, 
       export.cod_e_riferimento_messaggio_richiesta as riferimento_messaggio_richiesta, 
       export.dt_e_riferimento_data_richiesta as riferimento_data_richiesta, 
       cod_e_istit_att_id_univ_att_tipo_id_univoco as tipo_identificativo_univoco_attestante, 
       export.cod_e_istit_att_id_univ_att_codice_id_univoco as codice_identificativo_univoco_attestante, 
       export.de_e_istit_att_denominazione_attestante as denominazione_attestante, 
       export.cod_e_istit_att_codice_unit_oper_attestante as codice_unit_oper_attestante, 
       export.de_e_istit_att_denom_unit_oper_attestante as denom_unit_oper_attestante, 
       export.de_e_istit_att_indirizzo_attestante as indirizzo_attestante, 
       export.de_e_istit_att_civico_attestante as civico_attestante, 
       export.cod_e_istit_att_cap_attestante as cap_attestante, 
       export.de_e_istit_att_localita_attestante as localita_attestante, 
       export.de_e_istit_att_provincia_attestante as provincia_attestante, 
       export.cod_e_istit_att_nazione_attestante as nazione_attestante, 
       export.cod_e_ente_benef_id_univ_benef_tipo_id_univoco as tipo_identificativo_univoco_beneficiario, 
       export.cod_e_ente_benef_id_univ_benef_codice_id_univoco as codice_identificativo_univoco_beneficiario, 
       export.de_e_ente_benef_denominazione_beneficiario as denominazione_beneficiario, 
       export.cod_e_ente_benef_codice_unit_oper_beneficiario as codice_unit_oper_beneficiario, 
       export.de_e_ente_benef_denom_unit_oper_beneficiario as denom_unit_oper_beneficiario, 
       export.de_e_ente_benef_indirizzo_beneficiario as indirizzo_beneficiario, 
       export.de_e_ente_benef_civico_beneficiario as civico_beneficiario, 
       export.cod_e_ente_benef_cap_beneficiario as cap_beneficiario, 
       export.de_e_ente_benef_localita_beneficiario as localita_beneficiario, 
       export.de_e_ente_benef_provincia_beneficiario as provincia_beneficiario, 
       export.cod_e_ente_benef_nazione_beneficiario as nazione_beneficiario, 
       export.cod_e_sogg_vers_id_univ_vers_tipo_id_univoco as tipo_identificativo_univoco_versante, 
       export.cod_e_sogg_vers_id_univ_vers_codice_id_univoco as codice_identificativo_univoco_versante, 
       export.cod_e_sogg_vers_anagrafica_versante as anagrafica_versante, 
       export.de_e_sogg_vers_indirizzo_versante as indirizzo_versante, 
       export.de_e_sogg_vers_civico_versante as civico_versante, 
       export.cod_e_sogg_vers_cap_versante as cap_versante, 
       export.de_e_sogg_vers_localita_versante as localita_versante, 
       export.de_e_sogg_vers_provincia_versante as provincia_versante, 
       export.cod_e_sogg_vers_nazione_versante as nazione_versante, 
       export.de_e_sogg_vers_email_versante as email_versante, 
       export.cod_e_sogg_pag_id_univ_pag_tipo_id_univoco as tipo_identificativo_univoco_pagatore, 
       export.cod_e_sogg_pag_id_univ_pag_codice_id_univoco as codice_identificativo_univoco_pagatore, 
       export.cod_e_sogg_pag_anagrafica_pagatore as anagrafica_pagatore, 
       export.de_e_sogg_pag_indirizzo_pagatore as indirizzo_pagatore, 
       export.de_e_sogg_pag_civico_pagatore as civico_pagatore, 
       export.cod_e_sogg_pag_cap_pagatore as cap_pagatore, 
       export.de_e_sogg_pag_localita_pagatore as localita_pagatore, 
       export.de_e_sogg_pag_provincia_pagatore as provincia_pagatore, 
       export.cod_e_sogg_pag_nazione_pagatore as nazione_pagatore, 
       export.de_e_sogg_pag_email_pagatore as email_pagatore, 
       export.cod_e_dati_pag_codice_esito_pagamento as codice_esito_pagamento, 
       export.num_e_dati_pag_importo_totale_pagato as importo_totale_pagato, 
       export.cod_e_dati_pag_id_univoco_versamento as identificativo_univoco_versamento, 
       export.cod_e_dati_pag_codice_contesto_pagamento as codice_contesto_pagamento, 
       export.num_e_dati_pag_dati_sing_pag_singolo_importo_pagato as singolo_importo_pagato, 
       export.de_e_dati_pag_dati_sing_pag_esito_singolo_pagamento as esito_singolo_pagamento, 
       export.dt_e_dati_pag_dati_sing_pag_data_esito_singolo_pagamento as data_esito_singolo_pagamento, 
       export.cod_e_dati_pag_dati_sing_pag_id_univoco_riscoss as identificativo_univoco_riscossione, 
       export.de_e_dati_pag_dati_sing_pag_causale_versamento as causale_versamento, 
       export.de_e_dati_pag_dati_sing_pag_dati_specifici_riscossione as dati_specifici_riscossione,

       rendicontazione.cod_identificativo_flusso as identificativo_flusso_rendicontazione,
       rendicontazione.dt_data_ora_flusso as data_ora_flusso_rendicontazione,
       rendicontazione.cod_identificativo_univoco_regolamento as identificativo_univoco_regolamento,
       rendicontazione.dt_data_regolamento as data_regolamento,
       --ISTITUTO MITTENTE SI POTREBBE CABLARE POSTE
       --rendicontazione.cod_ist_mitt_id_univ_mitt_tipo_identificativo_univoco as tipo_identificativo_univoco_mittente,
       --rendicontazione.cod_ist_mitt_id_univ_mitt_codice_identificativo_univoco as codice_identificativo_univoco_mittente,
       --rendicontazione.de_ist_mitt_denominazione_mittente as denominazione_mittente,
       --rendicontazione.cod_ist_ricev_id_univ_ricev_tipo_identificativo_univoco as tipo_identificativo_univoco_ricevente,
       --rendicontazione.cod_ist_ricev_id_univ_ricev_codice_identificativo_univoco as codice_identificativo_univoco_ricevente,
       --rendicontazione.de_ist_ricev_denominazione_ricevente as denominazione_ricevente,
       rendicontazione.num_numero_totale_pagamenti as numero_totale_pagamenti,
       rendicontazione.num_importo_totale_pagamenti as importo_totale_pagamenti
       --cod_dati_sing_pagam_identificativo_univoco_versamento
       --num_dati_sing_pagam_singolo_importo_pagato
       --cod_dati_sing_pagam_codice_esito_singolo_pagamento
       --dt_dati_sing_pagam_data_esito_singolo_pagamento
       
  FROM mygov_flusso_export export INNER JOIN mygov_flusso_rendicontazione rendicontazione 
      ON (export.cod_e_istit_att_id_univ_att_codice_id_univoco = rendicontazione.identificativo_psp
     AND  export.cod_e_dati_pag_dati_sing_pag_id_univoco_riscoss = rendicontazione.cod_dati_sing_pagam_identificativo_univoco_riscossione);
