package it.tasgroup.idp.xmlbillerservices.ws.richiestapagamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-16T16:07:02.563+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "RichiestaPagamentoService", 
                  wsdlLocation = "file:/home/user/projects/iris_be/IdpSchemiBillerServices/src/main/resources/wsdl/RichiestaPagamento.wsdl",
                  targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento") 
public class RichiestaPagamentoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento", "RichiestaPagamentoService");
    public final static QName RichiestaPagamentoPort = new QName("http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento", "RichiestaPagamentoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/projects/paytas-be/ebmonitor/IdpSchemiBillerServices/src/main/resources/wsdl/RichiestaPagamento.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RichiestaPagamentoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/user/projects/paytas-be/ebmonitor/IdpSchemiBillerServices/src/main/resources/wsdl/RichiestaPagamento.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RichiestaPagamentoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RichiestaPagamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RichiestaPagamentoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RichiestaPagamentoPortType
     */
    @WebEndpoint(name = "RichiestaPagamentoPort")
    public RichiestaPagamentoPortType getRichiestaPagamentoPort() {
        return super.getPort(RichiestaPagamentoPort, RichiestaPagamentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RichiestaPagamentoPortType
     */
    @WebEndpoint(name = "RichiestaPagamentoPort")
    public RichiestaPagamentoPortType getRichiestaPagamentoPort(WebServiceFeature... features) {
        return super.getPort(RichiestaPagamentoPort, RichiestaPagamentoPortType.class, features);
    }

}
