package it.tasgroup.idp.xmlbillerservices.ws.richiestapagamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-16T16:07:02.558+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento", name = "RichiestaPagamentoPortType")
@XmlSeeAlso({it.tasgroup.idp.xmlbillerservices.pendenze.ObjectFactory.class, it.tasgroup.idp.xmlbillerservices.header.ObjectFactory.class, it.tasgroup.idp.xmlbillerservices.common.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RichiestaPagamentoPortType {

    @WebResult(name = "RichiestaPagamentoResponse", targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento", partName = "response")
    @WebMethod(operationName = "RichiestaPagamento", action = "http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento/RichiestaPagamentoMultiEnteOTF")
    public RichiestaPagamentoResponse richiestaPagamento(
        @WebParam(partName = "request", name = "RichiestaPagamento", targetNamespace = "http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento")
        RichiestaPagamento request
    );
}
