package it.aci.gtart.ws.pagamento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-16T11:53:15.974+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "NuovoPagamentoWSService", 
                  wsdlLocation = "file:/home/user/projects/paytas-be/ebmonitor/DRV_CART/resources/wsdl/NotificaGTART.wsdl",
                  targetNamespace = "http://pagamento.ws.gtart.aci.it/") 
public class NuovoPagamentoWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pagamento.ws.gtart.aci.it/", "NuovoPagamentoWSService");
    public final static QName NuovoPagamentoWSPort = new QName("http://pagamento.ws.gtart.aci.it/", "NuovoPagamentoWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/projects/paytas-be/ebmonitor/DRV_CART/resources/wsdl/NotificaGTART.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NuovoPagamentoWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/user/projects/paytas-be/ebmonitor/DRV_CART/resources/wsdl/NotificaGTART.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NuovoPagamentoWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NuovoPagamentoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NuovoPagamentoWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns NuovoPagamentoWS
     */
    @WebEndpoint(name = "NuovoPagamentoWSPort")
    public NuovoPagamentoWS getNuovoPagamentoWSPort() {
        return super.getPort(NuovoPagamentoWSPort, NuovoPagamentoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NuovoPagamentoWS
     */
    @WebEndpoint(name = "NuovoPagamentoWSPort")
    public NuovoPagamentoWS getNuovoPagamentoWSPort(WebServiceFeature... features) {
        return super.getPort(NuovoPagamentoWSPort, NuovoPagamentoWS.class, features);
    }

}
