//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.12 at 04:22:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.tasgroup.idp.ndp.rt;
