--  
--  FK
-- 

--  CFG_COMMISSIONE_PAGAMENTO
ALTER TABLE `CFG_COMMISSIONE_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_GATEWAY_PAGAMENTO` FOREIGN KEY
		(`ID_CFG_GATEWAY_PAGAMENTO`)
	REFERENCES `CFG_GATEWAY_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION	
	;
ALTER TABLE `CFG_COMMISSIONE_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_TIPO_COMMISSIONE` FOREIGN KEY
		(`ID_CFG_TIPO_COMMISSIONE`)
	REFERENCES `CFG_TIPO_COMMISSIONE`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION	
	;
	
--  CFG_GATEWAY_PAGAMENTO
ALTER TABLE `CFG_GATEWAY_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_CANALE_PAGAMENTO` FOREIGN KEY
		(`ID_CFG_CANALE_PAGAMENTO`)
	REFERENCES `CFG_CANALE_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `CFG_GATEWAY_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_DOCUMENTO_PAGAMENTO` FOREIGN KEY
		(`ID_CFG_DOCUMENTO_PAGAMENTO`)
	REFERENCES `CFG_DOCUMENTO_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `CFG_GATEWAY_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_FORNITORE_GATEWAY` FOREIGN KEY
		(`ID_CFG_FORNITORE_GATEWAY`)
	REFERENCES `CFG_FORNITORE_GATEWAY`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `CFG_GATEWAY_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_MODALITA_PAGAMENTO` FOREIGN KEY
		(`ID_CFG_MODALITA_PAGAMENTO`)
	REFERENCES `CFG_MODALITA_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `CFG_GATEWAY_PAGAMENTO` 
	ADD CONSTRAINT `FK_CFG_STRUMENTO_PAGAMENTO` FOREIGN KEY
		(`ID_CFG_STRUMENTO_PAGAMENTO`)
	REFERENCES `CFG_STRUMENTO_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
	
--  CFG_TRIBUTIENTE_GATEWAY
ALTER TABLE `CFG_TRIBUTIENTE_GATEWAY`
	ADD CONSTRAINT `FK_CFG_TRIBUTIENTE_GATEWAY_1` FOREIGN KEY
		(`ID_ENTE`, `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`, `CD_TRB_ENTE`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;
ALTER TABLE `CFG_TRIBUTIENTE_GATEWAY`
	ADD CONSTRAINT `FK_CFG_TRIBUTIENTE_GATEWAY_2` FOREIGN KEY
		(`ID_CFG_FORNITORE_GATEWAY`)
	REFERENCES `CFG_FORNITORE_GATEWAY`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;
ALTER TABLE `CFG_TRIBUTIENTE_GATEWAY`
	ADD CONSTRAINT `FK_CFG_TRIBUTIENTE_GATEWAY_3` FOREIGN KEY
		(`ID_CFG_GATEWAY_PAGAMENTO`)
	REFERENCES `CFG_GATEWAY_PAGAMENTO`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;
	
--  DOCUMENTI_PAGAMENTO
ALTER TABLE `DOCUMENTI_PAGAMENTO` 
	ADD CONSTRAINT `FK_DOCPAG_DISTINTA` FOREIGN KEY
		(`ID_DISTINTA_PAGAMENTO`)
	REFERENCES `DISTINTE_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `DOCUMENTI_PAGAMENTO` 
	ADD CONSTRAINT `FK_DOCPAG_GATEWAY` FOREIGN KEY
		(`ID_CFG_GATEWAY_PAGAMENTO`)
	REFERENCES `CFG_GATEWAY_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `DOCUMENTI_PAGAMENTO` 
	ADD CONSTRAINT `FK_DOCPAG_INTESTATARI` FOREIGN KEY
		(`INTESTATARIO`)
	REFERENCES `INTESTATARI`
		(`INTESTATARIO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `DOCUMENTI_PAGAMENTO` 
	ADD CONSTRAINT `FK_DOC_REPOSITORY` FOREIGN KEY
		(`ID_DOCUMENTO_REPOSITORY`)
	REFERENCES `DOCUMENTI_REPOSITORY`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  CONDIZIONI_DOCUMENTO
ALTER TABLE `CONDIZIONI_DOCUMENTO` 
	ADD CONSTRAINT `FK_CONDIZIONI` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `CONDIZIONI_DOCUMENTO` 
	ADD CONSTRAINT `FK_DOCUMENTI_PAGAMENTO` FOREIGN KEY
		(`ID_DOCUMENTO`)
	REFERENCES `DOCUMENTI_PAGAMENTO`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  ESITI_PENDENZA
ALTER TABLE `ESITI_PENDENZA` 
	ADD CONSTRAINT `FK_ID_EGOV` FOREIGN KEY
		(`E2EMSGID`,
		 `SENDERID`,
		 `SENDERSYS`)
	REFERENCES `PENDENZE_CART`
		(`E2EMSGID`,
		 `SENDERID`,
		 `SENDERSYS`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  ESITI_CART
ALTER TABLE `ESITI_CART` 
	ADD CONSTRAINT `FK_ESITO_EGOV` FOREIGN KEY
		(`E2EMSGID`,
		 `SENDERID`,
		 `SENDERSYS`)
	REFERENCES `PENDENZE_CART`
		(`E2EMSGID`,
		 `SENDERID`,
		 `SENDERSYS`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  ERRORI_ESITI_PENDENZA
ALTER TABLE `ERRORI_ESITI_PENDENZA` 
	ADD CONSTRAINT `FK_ID_ESIT_P` FOREIGN KEY
		(`ID_ESITO_PENDENZA`)
	REFERENCES `ESITI_PENDENZA`
		(`ID_ESITO_PENDENZA`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  PAGAMENTI_ONLINE
ALTER TABLE `PAGAMENTI_ONLINE` 
	ADD CONSTRAINT `FK_DISTPAGA_PAGAMENTIONLINE` FOREIGN KEY
		(`ID_DISTINTE_PAGAMENTO`)
	REFERENCES `DISTINTE_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  BOZZE_BONIFICI_RIACCREDITO
ALTER TABLE `BOZZE_BONIFICI_RIACCREDITO` 
	ADD CONSTRAINT `FK_BOZZE_COPD` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
	
--  CASELLARIO_DISPO
-- ALTER TABLE `CASELLARIO_DISPO` 
--	ADD CONSTRAINT `FK_DISTINTEPAGA_CASELLDISPO` FOREIGN KEY
--		(`ID_DISTINTE_PAGAMENTO`)
--	REFERENCES `DISTINTE_PAGAMENTO`
--		(`ID`)
--	ON DELETE NO ACTION
--	ON UPDATE NO ACTION
--	;
ALTER TABLE `CASELLARIO_DISPO` 
	ADD CONSTRAINT `FK_DISTINTERIACCR_CASELLDISPO` FOREIGN KEY
		(`ID_DISTINTE_RIACCREDITO`)
	REFERENCES `DISTINTE_RIACCREDITO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
	
--  BONIFICI_RIACCREDITO
ALTER TABLE `BONIFICI_RIACCREDITO` 
	ADD CONSTRAINT `FK_DISTINTE_BONI` FOREIGN KEY
		(`ID_DISTINTE_RIACCREDITO`)
	REFERENCES `DISTINTE_RIACCREDITO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
	
--  RENDICONTAZIONI
ALTER TABLE `RENDICONTAZIONI` 
	ADD CONSTRAINT `FK_CASELLARIOINFO_RCT` FOREIGN KEY
		(`ID_CASELLARIO_INFO`)
	REFERENCES `CASELLARIO_INFO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
	
--  ESITI_BONIFICI_RIACCREDITO
ALTER TABLE `ESITI_BONIFICI_RIACCREDITO` 
	ADD CONSTRAINT `FK_BONI_ESITI` FOREIGN KEY
		(`ID_BONIFICI_RIACCREDITO`)
	REFERENCES `BONIFICI_RIACCREDITO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `ESITI_BONIFICI_RIACCREDITO` 
	ADD CONSTRAINT `FK_RCT_ESITI` FOREIGN KEY
		(`ID_RENDICONTAZIONE`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  AEA
-- ALTER TABLE `AEA` 
--	ADD CONSTRAINT `FK_DISTPAG_AEA` FOREIGN KEY
--		(`ID_DISTINTE_PAGAMENTO`)
--	REFERENCES `DISTINTE_PAGAMENTO`
--		(`ID`)
--	ON DELETE NO ACTION
--	ON UPDATE NO ACTION
--	;
-- ALTER TABLE `AEA` 
--	ADD CONSTRAINT `FK_INTEST_AEA` FOREIGN KEY
--		(`INTESTATARIO`)
--	REFERENCES `INTESTATARI`
--		(`INTESTATARIO`)
--	ON DELETE NO ACTION
--	ON UPDATE NO ACTION
--	;
-- ALTER TABLE `AEA` 
--	ADD CONSTRAINT `FK_REVOCA_AEA` FOREIGN KEY
--		(`ID_REVOCA`)
--	REFERENCES `AEA`
--		(`ID`)
--	ON DELETE NO ACTION
--	ON UPDATE NO ACTION
--	;

--  ESITI_BB
ALTER TABLE `ESITI_BB` 
	ADD CONSTRAINT `FK_RCT_ESITIBB` FOREIGN KEY
		(`ID_RENDICONTAZIONE`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  INCASSI_BONIFICI_RH
ALTER TABLE `INCASSI_BONIFICI_RH` 
	ADD CONSTRAINT `FK_RCT_INCASSIBONI` FOREIGN KEY
		(`ID_RENDICONTAZIONE`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  PAGAMENTI
ALTER TABLE `PAGAMENTI` 
	ADD CONSTRAINT `FK_COPD_PAGA` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `PAGAMENTI` 
	ADD CONSTRAINT `FK_DISTPAGA_PAGAMENTI` FOREIGN KEY
		(`ID_DISTINTE_PAGAMENTO`)
	REFERENCES `DISTINTE_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `PAGAMENTI` 
	ADD CONSTRAINT `FK_ENTR_PAGA` FOREIGN KEY
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  DISTINTE_PAGAMENTO
ALTER TABLE `DISTINTE_PAGAMENTO` 
	ADD CONSTRAINT `FK_DOC_REPOSITORY2` FOREIGN KEY
		(`ID_DOCUMENTO_REPOSITORY`)
	REFERENCES `DOCUMENTI_REPOSITORY`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `DISTINTE_PAGAMENTO` 
	ADD CONSTRAINT `FK_GTW_DISTPAGA` FOREIGN KEY
		(`ID_CFG_GATEWAY_PAGAMENTO`)
	REFERENCES `CFG_GATEWAY_PAGAMENTO`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  JLTALPE
ALTER TABLE `JLTALPE` 
	ADD CONSTRAINT `FKJLTALPE208186` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;
ALTER TABLE `JLTALPE` 
	ADD CONSTRAINT `FKJLTALPE804250` FOREIGN KEY
		(`ID_PENDENZA`)
	REFERENCES `JLTPEND`
		(`ID_PENDENZA`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  JLTCOPD
ALTER TABLE `JLTCOPD` 
	ADD CONSTRAINT `FKJLTCOPD741786` FOREIGN KEY
		(`ID_PENDENZA`)
	REFERENCES `JLTPEND`
		(`ID_PENDENZA`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;
ALTER TABLE `JLTCOPD` 
	ADD CONSTRAINT `FKJLTCOPD_ENTI` FOREIGN KEY
		(`ID_ENTE`)
	REFERENCES `JLTENTI`
		(`ID_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  JLTDEPD
ALTER TABLE `JLTDEPD` 
	ADD CONSTRAINT `FKJLTDEPD721605` FOREIGN KEY
		(`ID_PENDENZA`)
	REFERENCES `JLTPEND`
		(`ID_PENDENZA`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  JLTPEND
ALTER TABLE `JLTPEND` 
	ADD CONSTRAINT `FKJLTPEND866120` FOREIGN KEY
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `JLTPEND` 
	ADD CONSTRAINT `FKJLTTRPA1234` FOREIGN KEY
		(`ID_TRIBUTO`)
	REFERENCES `JLTTRPA`
		(`ID_TRIBUTO`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;
	
--  JLTVOPD
ALTER TABLE `JLTVOPD` 
	ADD CONSTRAINT `FKJLTVOPD836679` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  PROMEMORIA
ALTER TABLE `PROMEMORIA` 
	ADD CONSTRAINT `FKPROMEMORIA523135` FOREIGN KEY
		(`DESTINATARIO`)
	REFERENCES `INTESTATARI`
		(`INTESTATARIO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  AREA
ALTER TABLE `AREA` 
	ADD CONSTRAINT `FKAREA37591` FOREIGN KEY
		(`APPLICAZIONE`)
	REFERENCES `APPLICAZIONI`
		(`CODAPPLICAZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  INTESTATARI
ALTER TABLE `INTESTATARI` 
	ADD CONSTRAINT `FKINTESTATAR607450` FOREIGN KEY
		(`ID_INDIRIZZIPOSTALI`)
	REFERENCES `INDIRIZZIPOSTALI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  FUNZIONI
ALTER TABLE `FUNZIONI` 
	ADD CONSTRAINT `FKFUNZIONI926746` FOREIGN KEY
		(`CODSERVIZIO`)
	REFERENCES `SERVIZI`
		(`CODSERVIZIO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  INTEST_OPER
ALTER TABLE `INTEST_OPER` 
	ADD CONSTRAINT `FKINTEST_OPE282515` FOREIGN KEY
		(`OPERATORE`)
	REFERENCES `OPERATORI`
		(`OPERATORE`)
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	;
ALTER TABLE `INTEST_OPER` 
	ADD CONSTRAINT `FKINTEST_OPE988871` FOREIGN KEY
		(`INTESTATARIO`)
	REFERENCES `INTESTATARI`
		(`INTESTATARIO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  FUNZIONIOPERATORI
ALTER TABLE `FUNZIONIOPERATORI` 
	ADD CONSTRAINT `FK_FUNZIONE` FOREIGN KEY
		(`CODFUNZIONE`)
	REFERENCES `FUNZIONI`
		(`CODFUNZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `FUNZIONIOPERATORI`
	ADD CONSTRAINT `FK_INTESTATARIO` FOREIGN KEY
		(`INTESTATARIO`)
	REFERENCES `INTESTATARI`
		(`INTESTATARIO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `FUNZIONIOPERATORI` 
	ADD CONSTRAINT `FK_OPERATORE` FOREIGN KEY
		(`OPERATORE`)
	REFERENCES `OPERATORI`
		(`OPERATORE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  JLTENTR
ALTER TABLE `JLTENTR` 
	ADD CONSTRAINT `FKJLTENTR388822` FOREIGN KEY
		(`ID_TRIBUTO`)
	REFERENCES `JLTTRPA`
		(`ID_TRIBUTO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `JLTENTR` 
	ADD CONSTRAINT `FKJLTENTR509643` FOREIGN KEY
		(`ID_ENTE`)
	REFERENCES `JLTENTI`
		(`ID_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `JLTENTR` 
	ADD CONSTRAINT `FKJLTENTR866119` FOREIGN KEY
		(`ID_ENTE`,
		 `ID_SYSTEM`)
	REFERENCES `JLTSIL`
		(`ID_ENTE`,
		 `ID_SYSTEM`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  JLTTRTM
ALTER TABLE `JLTTRTM` 
	ADD CONSTRAINT `FKJLTTRTM255522` FOREIGN KEY
		(`TP_ENTE`)
	REFERENCES `JLTENTP`
		(`TP_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `JLTTRTM` 
	ADD CONSTRAINT `FKJLTTRTM938117` FOREIGN KEY
		(`ID_TRIBUTO`)
	REFERENCES `JLTTRPA`
		(`ID_TRIBUTO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  JLTENTI
ALTER TABLE `JLTENTI` 
	ADD CONSTRAINT `FKJLTENTI804808` FOREIGN KEY
		(`TP_ENTE`)
	REFERENCES `JLTENTP`
		(`TP_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  JLTSIL
ALTER TABLE `JLTSIL` 
	ADD CONSTRAINT `FKJLTSIL502531` FOREIGN KEY
		(`ID_ENTE`)
	REFERENCES `JLTENTI`
		(`ID_ENTE`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;

--  CONTOTECNICO
ALTER TABLE `CONTOTECNICO` 
	ADD CONSTRAINT `FK_INTESTATARIO2` FOREIGN KEY
		(`INTESTATARIO`)
	REFERENCES `INTESTATARI`
		(`INTESTATARIO`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  RID
-- ALTER TABLE `RID` 
--	ADD CONSTRAINT `FK_DISTPAG_RID` FOREIGN KEY
--		(`ID_DISTINTE_PAGAMENTO`)
--	REFERENCES `DISTINTE_PAGAMENTO`
--		(`ID`)
--	ON DELETE NO ACTION
--	ON UPDATE NO ACTION
--	;

--  ESITI_RCT
ALTER TABLE `ESITI_RCT` 
	ADD CONSTRAINT `FK_RCT_ESITIRCT` FOREIGN KEY
		(`ID_RENDICONTAZIONI`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE RESTRICT
	;

--  IRIS_GATEWAY_SHOP_CART
ALTER TABLE `IRIS_GATEWAY_SHOP_CART` 
	ADD CONSTRAINT `FK_CONDIZIONI_PAGAMENTO` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `IRIS_GATEWAY_SHOP_CART` 
	ADD CONSTRAINT `FK_TOKEN` FOREIGN KEY
		(`TOKEN`)
	REFERENCES `IRIS_GATEWAY_SESSION`
		(`TOKEN`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  IRIS_GATEWAY_SESSION
ALTER TABLE `IRIS_GATEWAY_SESSION` 
	ADD CONSTRAINT `FK_CFG_IRIS_GATEWAY_CLIENT` FOREIGN KEY
		(`GTW_CLIENT_ID`)
	REFERENCES `CFG_IRIS_GATEWAY_CLIENT`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;

--  IRIS_GATEWAY_CLIENT_SHOP_CART
ALTER TABLE `IRIS_GATEWAY_CLIENT_SHOP_CART` 
	ADD CONSTRAINT `FK_CFG_IRIS_GATEWAY_CLIENT2` FOREIGN KEY
		(`GTW_CLIENT_ID`)
	REFERENCES `CFG_IRIS_GATEWAY_CLIENT`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `IRIS_GATEWAY_CLIENT_SHOP_CART` 
	ADD CONSTRAINT `FK_CONDIZIONI_PAGAMENTO2` FOREIGN KEY
		(`ID_CONDIZIONE`)
	REFERENCES `JLTCOPD`
		(`ID_CONDIZIONE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `IRIS_GATEWAY_CLIENT_SHOP_CART` 
	ADD CONSTRAINT `FK_SESSIONE` FOREIGN KEY
		(`SESSION_ID`)
	REFERENCES `SESSIONI`
		(`SESSIONID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  GEC_UTENTI_CANALI
ALTER TABLE `GEC_UTENTI_CANALI` 
	ADD CONSTRAINT `FK_GEC_UTENTI_CANALI` FOREIGN KEY
		(`ID_CANALE`)
	REFERENCES `GEC_CANALI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  GEC_MESSAGGI_LOGICI
ALTER TABLE `GEC_MESSAGGI_LOGICI` 
	ADD CONSTRAINT `FK_MESSAGGI_LOGICI_TIPO` FOREIGN KEY
		(`TIPO_MESSAGGIO`)
	REFERENCES `GEC_TIPO_MESSAGGI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  GEC_LOG_INVIO_MESSAGGI
ALTER TABLE `GEC_LOG_INVIO_MESSAGGI` 
	ADD CONSTRAINT `FK_GEC_LOG_INVIO_MESSAGGI_CANALI` FOREIGN KEY
		(`ID_CANALE`)
	REFERENCES `GEC_CANALI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `GEC_LOG_INVIO_MESSAGGI` 
	ADD CONSTRAINT `FK_GEC_LOG_INVIO_MESSAGGI_LOGICI` FOREIGN KEY
		(`ID_MESSAGGI_LOGICI`)
	REFERENCES `GEC_MESSAGGI_LOGICI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  NOTIFICHE_PAGAMENTI
ALTER TABLE `NOTIFICHE_PAGAMENTI` 
	ADD CONSTRAINT `FK_IDENTE_CDTRB` FOREIGN KEY
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE RESTRICT
	;
ALTER TABLE `NOTIFICHE_PAGAMENTI` 
	ADD CONSTRAINT `FK_PAGA_NOTIFICHE` FOREIGN KEY
		(`ID_PAGAMENTO`)
	REFERENCES `PAGAMENTI`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  RIPARTENZE_CASELLARIO_INFO
ALTER TABLE `RIPARTENZE_CASELLARIO_INFO` 
	ADD CONSTRAINT `FK_RIPARTENZE_CASELLARIO_INFO_1` FOREIGN KEY
		(`ID_RENDICONTAZIONE`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;
ALTER TABLE `RIPARTENZE_CASELLARIO_INFO` 
	ADD CONSTRAINT `FK_RIPARTENZE_RIPARTENZE_CASELLARIO_INFO_2` FOREIGN KEY
		(`ID_CASELLARIO`)
	REFERENCES `CASELLARIO_INFO`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  ESITI_CBILL
ALTER TABLE `ESITI_CBILL` 
	ADD CONSTRAINT `FK_RCT_ESITI_CBILL` FOREIGN KEY
		(`ID_RENDICONTAZIONE`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  ESITI_NDP
ALTER TABLE `ESITI_NDP` 
	ADD CONSTRAINT `FK_RCT_ESITI_NDP` FOREIGN KEY
		(`ID_RENDICONTAZIONI`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  IBAN
ALTER TABLE `IBAN` 
	ADD CONSTRAINT `FK_IBAN` FOREIGN KEY
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`,
		 `CD_TRB_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;
ALTER TABLE `IBAN` 
	ADD CONSTRAINT `FK_SIL` FOREIGN KEY 
		(`ID_ENTE`,
		 `ID_SYSTEM`)
	REFERENCES `JLTSIL`
		(`ID_ENTE`,
		 `ID_SYSTEM`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  GDE_EVENTI
ALTER TABLE `GDE_EVENTI` 
	ADD CONSTRAINT `FK_GDE_EVENTI_2` FOREIGN KEY
		(`ID_EGOV`)
	REFERENCES `GDE_INFOSPCOOP`
		(`ID_EGOV`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	;
ALTER TABLE `GDE_EVENTI` 
	ADD CONSTRAINT `CHK_GDE_EVENTI_1` CHECK 
		(CATEGORIA_EVENTO IN ('INTERFACCIA','INTERNO'))
	;

--  RIVERSAMENTI
ALTER TABLE `RIVERSAMENTI` 
	ADD CONSTRAINT `FK_RIVERSAMENTI` FOREIGN KEY
		(`ID_INCASSI_BONIFICI_RH`)
	REFERENCES `INCASSI_BONIFICI_RH`
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  MOVIMENTI_ACCREDITO
ALTER TABLE `MOVIMENTI_ACCREDITO` 
	ADD CONSTRAINT `FK_MOVIMENTI_ACCREDITO_1` FOREIGN KEY
		(`ID_RENDICONTAZIONE`)
	REFERENCES `RENDICONTAZIONI`
		(`ID`)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	;

--  DATI_ANAGRAFICI_VERSANTE
--  ALTER TABLE `DATI_ANAGRAFICI_VERSANTE` 
--    ADD CONSTRAINT `FK_DISTINTE_PAGAMENTO_3` FOREIGN KEY 
--  	(`ID_DISTINTE_PAGAMENTO`) 
--    REFERENCES `DISTINTE_PAGAMENTO` 
--      (`ID`);

--  DATI_ANAGRAFICI_DEST
ALTER TABLE  `DATI_ANAGRAFICI_DEST` 
  ADD CONSTRAINT `FK_DESTINATARI` FOREIGN KEY 
	(`ID_DESTINATARIO`) 
  REFERENCES `JLTDEPD` 
    (`ID_DESTINATARIO`);

--  IUVMAP
ALTER TABLE  `IUVMAP` 
  ADD CONSTRAINT `FK_IUVMAP_1` FOREIGN KEY 
	(`ID_ENTE`,`CD_TRB_ENTE`) 
  REFERENCES `JLTENTR` 
    (`ID_ENTE`,`CD_TRB_ENTE`);

--  CFG_NOTIFICA_PAGAMENTO
ALTER TABLE `CFG_NOTIFICA_PAGAMENTO`
	ADD CONSTRAINT `FK_JLTENTR_3` FOREIGN KEY
		(`ID_ENTE`, `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`, `CD_TRB_ENTE`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

--  NOTIFICHE_CART
ALTER TABLE `NOTIFICHE_CART`
	ADD CONSTRAINT `FK_NOTIFICHE_CART_1` FOREIGN KEY
		(`ID_ENTE`, `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`, `CD_TRB_ENTE`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

--  TRIBUTI_OPER
ALTER TABLE `TRIBUTI_OPER`
	ADD CONSTRAINT `FKTRIB_INTEST_OPE` FOREIGN KEY
		(`INTESTATARIO`,`OPERATORE`,`TP_OPERATORE`)
	REFERENCES `INTEST_OPER`
		(`INTESTATARIO`,`OPERATORE`,`TP_OPERATORE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;
ALTER TABLE `TRIBUTI_OPER`
	ADD CONSTRAINT `FKTRIB_OPE_ENTR` FOREIGN KEY
		(`ID_ENTE`, `CD_TRB_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`, `CD_TRB_ENTE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

--  SSIL_GESTIONI
ALTER TABLE `SSIL_GESTIONI` 
	ADD CONSTRAINT `FK_SSIL_GESTIONI_1` FOREIGN KEY 
		(`ID_MESSAGGIO`)
	REFERENCES `SSIL_MESSAGGI` 
		(`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	;

--  GDE_EVENTI
ALTER TABLE `GDE_EVENTI` 
	ADD CONSTRAINT `fk_gde_eventi_1` FOREIGN KEY 
		(`id_egov`)
	REFERENCES `GDE_INFOSPCOOP` 
		(`id_egov`)
	;

--  GDE_CFG_TRIBUTIENTE_PLUGIN
ALTER TABLE `CFG_TRIBUTIENTE_PLUGIN`
	ADD CONSTRAINT `FK_CFG_TRIBUTIENTE_PLUGIN_01` FOREIGN KEY
		(`ID_ENTE`)
	REFERENCES `JLTENTR`
		(`ID_ENTE`)
;

-- INFO_PRENOTAZIONI
ALTER TABLE `INFO_PRENOTAZIONI`
  ADD CONSTRAINT `FK_PRENOTAZIONI` FOREIGN KEY (`ID_PRENOTAZIONE`)
  REFERENCES `PRENOTAZIONI` (`ID`)
;  

-- REVOCHE_PAGAMENTO
ALTER TABLE `REVOCHE_PAGAMENTO`
        ADD CONSTRAINT `FK_REVOCHE_PAGAMENTO_01` FOREIGN KEY
                (`ID_PAGAMENTI`)
        REFERENCES `PAGAMENTI`
                (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE NO ACTION
;


-- PRENOTA_AVVISI_DIGITALI
ALTER TABLE `PRENOTA_AVVISI_DIGITALI`
        ADD CONSTRAINT `FK_PRENOTA_AVVISI_DIGITALI_01` FOREIGN KEY
                (`ID_CONDIZIONE`)
        REFERENCES `JLTCOPD`
                (`ID_CONDIZIONE`)
;
ALTER TABLE `PRENOTA_AVVISI_DIGITALI`
        ADD CONSTRAINT `FK_PRENOTA_AVVISI_DIGITALI_02` FOREIGN KEY
                (`ID_ENTE`)
        REFERENCES `JLTENTI`
                (`ID_ENTE`)
;
ALTER TABLE `PRENOTA_AVVISI_DIGITALI`
        ADD CONSTRAINT `FK_PRENOTA_AVVISI_DIGITALI_03` FOREIGN KEY
                (`ID_EVENTO_SMS`)
        REFERENCES `GEV_EVENTI`
                (`ID`)
;
ALTER TABLE `PRENOTA_AVVISI_DIGITALI`
        ADD CONSTRAINT `FK_PRENOTA_AVVISI_DIGITALI_04` FOREIGN KEY
                (`ID_EVENTO_EMAIL`)
        REFERENCES `GEV_EVENTI`
                (`ID`)
;

-- AVVISI_DIGITALI_FILE
ALTER TABLE `AVVISI_DIGITALI_FILE`
		ADD CONSTRAINT `FK_AVVISI_DIGITALI_FILE_1` FOREIGN KEY
				(`ID_CASELLARIO_DISPO`)
		REFERENCES `CASELLARIO_DISPO`
				(`ID`)
;
ALTER TABLE `AVVISI_DIGITALI_FILE`
        ADD CONSTRAINT `FK_AVVISI_DIGITALI_FILE_2` FOREIGN KEY
                (`ID_ENTE`)
        REFERENCES `JLTENTI`
                (`ID_ENTE`)
;
-- ESITI_AVVISI_DIGITALI_FILE
ALTER TABLE `ESITI_AVVISI_DIGITALI_FILE`
		ADD CONSTRAINT `FK_ESITI_AVVISI_DIGIT_FILE_1` FOREIGN KEY
				(`ID_CASELLARIO_INFO`)
		REFERENCES `CASELLARIO_INFO`
				(`ID`)
;
--
-- aggiornamento informazioni DB
--
INSERT INTO APPLICATION_INFO (PRODUCT_NAME,PRODUCT_DB_VERSION,TS_AGGIORNAMENTO,VERSION)
VALUES (
	'INIT.STRUCT',
	'02.paytas.foreign-keys',
	CURRENT_TIMESTAMP,
	0
);

