CREATE OR REPLACE VIEW `ENTI` AS SELECT * FROM `JLTENTI`;
CREATE OR REPLACE VIEW `TRIBUTIENTI` AS SELECT * FROM `JLTENTR`;
CREATE OR REPLACE VIEW `TRIBUTI` AS SELECT * FROM `JLTTRPA`;
CREATE OR REPLACE VIEW `CONDIZIONI` AS SELECT * FROM  `JLTCOPD`;

--
-- aggiornamento informazioni DB
--
INSERT INTO APPLICATION_INFO (PRODUCT_NAME,PRODUCT_DB_VERSION,TS_AGGIORNAMENTO,VERSION)
VALUES (
	'INIT.STRUCT',
	'01.paytas.alias',
	CURRENT_TIMESTAMP,
	0
);