
-- PROVINCE

INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('88'           ,'SAN MARINO'    ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AG'           ,'AGRIGENTO'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AL'           ,'ALESSANDRIA'   ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AN'           ,'ANCONA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AO'           ,'AOSTA'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AP'           ,'ASCOLI PICENO' ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AQ'           ,'L''AQUILA'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AR'           ,'AREZZO'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AT'           ,'ASTI'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('AV'           ,'AVELLINO'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BA'           ,'BARI'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BG'           ,'BERGAMO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BI'           ,'BIELLA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BL'           ,'BELLUNO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BN'           ,'BENEVENTO'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BO'           ,'BOLOGNA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BR'           ,'BRINDISI'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BS'           ,'BRESCIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BT'           ,'BARLETTA  ANDRIA  TRANI','SCRIPT',CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('BZ'           ,'BOLZANO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CA'           ,'CAGLIARI'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CB'           ,'CAMPOBASSO'    ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CE'           ,'CASERTA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CH'           ,'CHIETI'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CI'           ,'CARBONIA IGLESIAS','SCRIPT',		CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CL'           ,'CALTANISSETTA' ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CN'           ,'CUNEO'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CO'           ,'COMO'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CR'           ,'CREMONA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CS'           ,'COSENZA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CT'           ,'CATANIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('CZ'           ,'CATANZARO'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('EE'           ,'PROVINCIA ESTERA','SCRIPT'       ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('EN'           ,'ENNA'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('FC'           ,'FORLI'' CESENA','SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('FE'           ,'FERRARA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('FG'           ,'FOGGIA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('FI'           ,'FIRENZE'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('FM'           ,'FERMO'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('FR'           ,'FROSINONE'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('GE'           ,'GENOVA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('GO'           ,'GORIZIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('GR'           ,'GROSSETO'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('IM'           ,'IMPERIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('IS'           ,'ISERNIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('KR'           ,'CROTONE'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('LC'           ,'LECCO'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('LE'           ,'LECCE'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('LI'           ,'LIVORNO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('LO'           ,'LODI'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('LT'           ,'LATINA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('LU'           ,'LUCCA'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MC'           ,'MACERATA'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA  , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MD'           ,'MEDIO CAMPIDANO','SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('ME'           ,'MESSINA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MI'           ,'MILANO'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MN'           ,'MANTOVA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MO'           ,'MODENA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MS'           ,'MASSA'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MT'           ,'MATERA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('MZ'           ,'MONZA - BRIANZA','SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('NA'           ,'NAPOLI'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('NO'           ,'NOVARA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('NU'           ,'NUORO'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('OG'           ,'OGLIASTRA'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('OR'           ,'ORISTANO'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('OT'           ,'OLBIA TEMPIO'  ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PA'           ,'PALERMO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PC'           ,'PIACENZA'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PD'           ,'PADOVA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PE'           ,'PESCARA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PG'           ,'PERUGIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PI'           ,'PISA'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PN'           ,'PORDENONE'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PO'           ,'PRATO'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PR'           ,'PARMA'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PT'           ,'PISTOIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PU'           ,'PESARO URBINO' ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PV'           ,'PAVIA'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('PZ'           ,'POTENZA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RA'           ,'RAVENNA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA  , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RC'           ,'REGGIO CALABRIA','SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RE'           ,'REGGIO EMILIA' ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RG'           ,'RAGUSA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RI'           ,'RIETI'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RM'           ,'ROMA'          ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RN'           ,'RIMINI'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('RO'           ,'ROVIGO'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SA'           ,'SALERNO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SI'           ,'SIENA'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SO'           ,'SONDRIO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SP'           ,'LA SPEZIA'     ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SR'           ,'SIRACUSA'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SS'           ,'SASSARI'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('SV'           ,'SAVONA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TA'           ,'TARANTO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TE'           ,'TERAMO'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TN'           ,'TRENTO'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TO'           ,'TORINO'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TP'           ,'TRAPANI'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TR'           ,'TERNI'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TS'           ,'TRIESTE'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('TV'           ,'TREVISO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('UD'           ,'UDINE'         ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VA'           ,'VARESE'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VB'           ,'VERBANO CUSIO OSSOLA','SCRIPT'  ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VC'           ,'VERCELLI'      ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VE'           ,'VENEZIA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VI'           ,'VICENZA'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VR'           ,'VERONA'        ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VT'           ,'VITERBO'       ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;
INSERT INTO PROVINCE
( COD_PROVINCIA , DESC_PROVINCIA , OP_INSERIMENTO , TS_INSERIMENTO  , OP_AGGIORNAMENTO , TS_AGGIORNAMENTO , VERSION ) VALUES
('VV'           ,'VIBO VALENTIA' ,'SCRIPT'        ,CURRENT_TIMESTAMP,NULL              ,NULL              ,0        )
;


INSERT INTO ID_TABLE_GEN (ID_NAME,ID_VALUE) VALUES ('TRIBUTO_STRUTTURATO', 1);

-- ------------------------------------------------------------------------------
INSERT INTO APPLICATION_INFO
	(PRODUCT_NAME,PRODUCT_DB_VERSION,TS_AGGIORNAMENTO,VERSION)
VALUES (
	'INIT.DATA',
	'paytas.init.data',
	CURRENT_TIMESTAMP,
	0                  -- (0.comune, 1.paytas, 2.rt, 3.bpel)
);
