<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RichiestaPagamento" 
	targetNamespace="http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:tns="http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:idpAP="http://idp.tasgroup.it/xmlbillerservices/Pendenze" >
	
    <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                targetNamespace="http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento">
    <xsd:import namespace="http://idp.tasgroup.it/xmlbillerservices/Pendenze" schemaLocation="Pendenze.xsd"/>
                                
	<xsd:element name="RichiestaPagamento">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="idpAP:IdpAllineamentoPendenzeMultiOTF"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="RichiestaPagamentoResponse">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="idpAP:IdpMultiEsitoOTF"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element></xsd:schema></wsdl:types>
    <wsdl:message name="RichiestaPagamentoRequest">
    	<wsdl:part name="request" element="tns:RichiestaPagamento"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="RichiestaPagamentoResponse">
    	<wsdl:part name="response" element="tns:RichiestaPagamentoResponse"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="RichiestaPagamentoPortType">
    	<wsdl:operation name="RichiestaPagamento">
    		<wsdl:input message="tns:RichiestaPagamentoRequest"></wsdl:input>
    		<wsdl:output message="tns:RichiestaPagamentoResponse"></wsdl:output>
    	</wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RichiestaPagamentoBinding"
    	type="tns:RichiestaPagamentoPortType">
    	<soap:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
    	<wsdl:operation name="RichiestaPagamento">
    		<soap:operation
    			soapAction="http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamento/RichiestaPagamentoMultiEnteOTF" />
    		<wsdl:input>
    			<soap:body use="literal" />
    		</wsdl:input>
    		<wsdl:output>
    			<soap:body use="literal" />
    		</wsdl:output>
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RichiestaPagamentoService">
		<wsdl:port name="RichiestaPagamentoPort" binding="tns:RichiestaPagamentoBinding">
			<soap:address location="http://idp.tasgroup.it/xmlbillerservices/ws/RichiestaPagamentoService" />
		</wsdl:port>
	</wsdl:service></wsdl:definitions>