package it.nch.is.fo.profilo;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 28-ago-2006 15.37.21 by Hibernate Tools 3.1.0.beta5

/**
 * FunzioniintestatariId generated by hbm2java
 */
@Embeddable
public class FunzioniintestatariId implements java.io.Serializable {

	// Fields    

	private String codfunzione;

	private String corporate;

	// Constructors

	/** default constructor */
	public FunzioniintestatariId() {
	}

	/** full constructor */
	public FunzioniintestatariId(String codfunzione, String corporate) {
		this.codfunzione = codfunzione;
		this.corporate = corporate;
	}

	// Property accessors
	@Column(name="CODFUNZIONE")
	public String getCodfunzione() {
		return this.codfunzione;
	}

	public void setCodfunzione(String codfunzione) {
		this.codfunzione = codfunzione;
	}

	@Column(name="INTESTATARIO")
	public String getCorporate() {
		return this.corporate;
	}

	public void setCorporate(String corporate) {
		this.corporate = corporate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FunzioniintestatariId))
			return false;
		FunzioniintestatariId castOther = (FunzioniintestatariId) other;

		return ((this.getCodfunzione() == castOther.getCodfunzione()) || (this
				.getCodfunzione() != null
				&& castOther.getCodfunzione() != null && this.getCodfunzione()
				.equals(castOther.getCodfunzione())))
				&& ((this.getCorporate() == castOther.getCorporate()) || (this
						.getCorporate() != null
						&& castOther.getCorporate() != null && this
						.getCorporate().equals(castOther.getCorporate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodfunzione() == null ? 0 : this.getCodfunzione()
						.hashCode());
		result = 37
				* result
				+ (getCorporate() == null ? 0 : this.getCorporate()
						.hashCode());
		return result;
	}

}
