package it.nch.is.fo.profilo;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 7-ago-2006 15.43.20 by Hibernate Tools 3.1.0.beta5

/**
 * IntestatarioperatoriId generated by hbm2java
 */
@Embeddable
public class IntestatarioperatoriId implements java.io.Serializable {

	// Fields    

	private String intestatario;

	private String operatore;

	// Constructors

	/** default constructor */
	public IntestatarioperatoriId() {
	}

	/** full constructor */
	public IntestatarioperatoriId(String intestatario, String operatore) {
		this.intestatario = intestatario;
		this.operatore = operatore;
	}

	// Property accessors
	@Column(name="INTESTATARIO",nullable=false)
	public String getIntestatario() {
		return this.intestatario;
	}

	public void setIntestatario(String intestatario) {
		this.intestatario = intestatario;
	}

	@Column(name="OPERATORE",nullable=false)
	public String getOperatore() {
		return this.operatore;
	}

	public void setOperatore(String operatore) {
		this.operatore = operatore;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IntestatarioperatoriId))
			return false;
		IntestatarioperatoriId castOther = (IntestatarioperatoriId) other;

		return ((this.getIntestatario() == castOther.getIntestatario()) || (this
				.getIntestatario() != null
				&& castOther.getIntestatario() != null && this
				.getIntestatario().equals(castOther.getIntestatario())))
				&& ((this.getOperatore() == castOther.getOperatore()) || (this
						.getOperatore() != null
						&& castOther.getOperatore() != null && this
						.getOperatore().equals(castOther.getOperatore())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIntestatario() == null ? 0 : this.getIntestatario()
						.hashCode());
		result = 37 * result
				+ (getOperatore() == null ? 0 : this.getOperatore().hashCode());
		return result;
	}

}
