#!/bin/bash
#
# Batches :  batch-DepositoAvvisiDigitali
#
# chkconfig: 345 95 2
# description:  batch-DepositoAvvisiDigitali Statup Script
#
BATCH_INIT_DIR=__TAG_BATCH_ROOT_PATH__/init.d
SCRIPT_NAME="batch-DepositoAvvisiDigitali"
SW_MW="$SCRIPT_NAME"

_execute() {
	/bin/sh $BATCH_INIT_DIR/$SCRIPT_NAME $1
}

# See how we were called.
case "$1" in
  start)
	echo -n "Starting : $SW_MW "
	_execute $1
	echo
        ;;
  stop)
	echo -n "Stopping : $SW_MW "
	_execute $1
	echo
        ;;
  status)
	echo -n "Status : $SW_MW "
	_execute $1
	echo
        ;;
  enable)
	echo -n "Enabling Cluster Control : $SW_MW"
	_execute $1
	echo
	;;
  disable)
	echo -n "Disabling Cluster Control : $SW_MW"
	_execute $1
	echo
	;;
  *)
        echo $"Usage: $SW_MW {start|stop|status|enable|disable}"
        exit
esac
