package it.tasgroup.idp.autorizzazionepagamento;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-11-13T13:16:48.029+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AutorizzazionePagamento", 
                  wsdlLocation = "classpath:wsdl/AutorizzazionePagamento.wsdl",
                  targetNamespace = "http://idp.tasgroup.it/AutorizzazionePagamento/") 
public class AutorizzazionePagamento_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idp.tasgroup.it/AutorizzazionePagamento/", "AutorizzazionePagamento");
    public final static QName AutorizzazionePagamentoSOAP = new QName("http://idp.tasgroup.it/AutorizzazionePagamento/", "AutorizzazionePagamentoSOAP");
    static {
        URL url = AutorizzazionePagamento_Service.class.getClassLoader().getResource("wsdl/AutorizzazionePagamento.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AutorizzazionePagamento_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/AutorizzazionePagamento.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public AutorizzazionePagamento_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutorizzazionePagamento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutorizzazionePagamento_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AutorizzazionePagamento
     */
    @WebEndpoint(name = "AutorizzazionePagamentoSOAP")
    public AutorizzazionePagamento getAutorizzazionePagamentoSOAP() {
        return super.getPort(AutorizzazionePagamentoSOAP, AutorizzazionePagamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizzazionePagamento
     */
    @WebEndpoint(name = "AutorizzazionePagamentoSOAP")
    public AutorizzazionePagamento getAutorizzazionePagamentoSOAP(WebServiceFeature... features) {
        return super.getPort(AutorizzazionePagamentoSOAP, AutorizzazionePagamento.class, features);
    }

}
