package it.tasgroup.idp.util;

public interface StatoEnum {
	//stati delle pendenze
	String DA_ELABORARE = "DA ELABORARE";
	String DA_ELABORARE_MASSIVO = "DA ELABORARE_MASSIVO";
	String IN_CORSO = "IN CORSO";
	String COMPLETO = "COMPLETO";
	String ELABORATO_OK = "ELABORATO OK";
	String ELABORATO_KO = "ELABORATO_KO";
	String DA_SPEDIRE = "DA SPEDIRE";
	String DA_SPEDIRE_WS = "DA SPEDIRE WS";
	String IN_SPEDIZIONE = "IN_SPEDIZIONE";
	String RISPOSTA_INVIATA = "RISPOSTA INVIATA";
	String RISPOSTA_INVIATA_WS = "RISPOSTA INVIATA WS";
	String RISPOSTA_NON_INVIATA = "RISPOSTA NON INVIATA";
	String DA_REINVIARE = "DA_REINVIARE";
	String RIFIUTATO = "RIFIUTATO";
	String INVIATO = "INVIATO";
	String REINVIATO = "REINVIATO";
	String NON_INVIATO = "NON_INVIATO";
	String NON_VALIDO_XSDSCHEMA = "NON_VALIDO_XSDSCHEMA";
    
	//stati dei massivi
	String ESITO_KO_DA_CREARE = "ESITO_KO_DA_CREARE";
	String ESITO_OK_DA_CREARE = "ESITO_OK_DA_CREARE";
	
	//stati delle rendicontazioni
	String ACCETTATO = "ACCETTATO";
	String RICEVUTO = "RICEVUTO";
	String SCARTATO = "RIFIUTATO";
	String ESITATO = "ESITATO";
	String PARZIALMENTE_RICONCILIATO = "PARZ RICONCILIATO";
	String RICONCILIATO = "RICONCILIATO";
	//stati dei bonifici
	String INSERITO = "INSERITO";
	String CREATO = "CREATO";
	String DA_CREARE = "DA_CREARE";
	
	//stati dei pagamenti e/o notifiche
	String NOTIFICHE_INSERITO = "INSERITO";
	String NOTIFICHE_CREATO = "CREATO";
	String NOTIFICHE_DA_CREARE = "DA_CREARE";
	String NOTIFICHE_PAG_NOTIFICATO = "NOTIFICATO";
	String NOTIFICHE_INVIATO = "INVIATO";
	
	//stati dei pagamenti e/o notifiche (nuova versione 3 notifiche)
	String NOTIFICHE_ESEGUITO = "ESEGUITO";
	String NOTIFICHE_REGOLATO = "REGOLATO";
	String NOTIFICHE_REGOLATO_FLAG2 = "REGOLATO_FLAG2";
	String NOTIFICHE_NOTIFICATO = "NOTIFICATO";
	String NOTIFICHE_INCASSO = "INCASSO";
	

	String NOTIFICHE_CREATO_PER_ESEGUITO = "NEW ESEGUITO"; //NON PIU USATI
	String NOTIFICHE_CREATO_PER_REGOLATO = "NEW REGOLATO"; // NON PIU USATI
	String NOTIFICHE_CREATO_PER_INCASSO = "NEW INCASSO";   // NON PIU USATI	
	
	//Stato utilizzato quando arriva l'esito del bonifico
	String PAGATO="PAGATO";
	
	//stati delle rendicontazioni ente
	String RCT_ENTE_INSERITO = "INSERITO";
	String RCT_ENTE_CREATO = "CREATO";
	String RCT_ENTE_DA_CREARE = "DA_CREARE";
	String RCT_ENTE_RENDICONTATO = "RENDICONTATO";

	//serviceNameType
	String SERVICE_NAME_TYPE_ALL_PENDENZE = "IdpAllineamentoPendenze";
	String SERVICE_NAME_TYPE_ALL_MASSIVO_PENDENZE = "IdpAllineamentoMassivoPendenze";
	String SERVICE_NAME_NOTIFICHE = "IdpInformativaPagamento";
	//msgType
	String MSG_TYPE_ALL_PENDENZE = "ALL_PEND";
	String MSG_TYPE_ALL_MASSIVO_PENDENZE = "ALL_MASSIVO";
	String MSG_TYPE_ALL_PENDENZE_SYNC = "ALL_PEND_SYNC";
	String MSG_TYPE_ALL_PENDENZE_OTF = "ALL_PEND_OTF";
	String MSG_TYPE_ALL_PENDENZE_SSIL = "ALL_PEND_SSIL";

	//stati delle disposizioni rid
	String ESEGUITO_SBF = "ESEGUITO SBF";
	String ESEGUITO_SBF_DESC = "ESEGUITO SALVO BUON FINE";

	String DISPONIBILE = "DISPONIBILE";
}
