package it.toscana.rete.cart.servizi.iris_1_1.ws.idpinformativapagamento;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2019-05-08T20:00:13.474+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "VerificaStatoPagamentoService", 
                  wsdlLocation = "classpath:wsdl/InvioNotificaPagamento.wsdl",
                  targetNamespace = "http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy") 
public class VerificaStatoPagamentoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", "VerificaStatoPagamentoService");
    public final static QName VerificaStatoPagamento = new QName("http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", "VerificaStatoPagamento");
    static {
        URL url = VerificaStatoPagamentoService.class.getClassLoader().getResource("wsdl/InvioNotificaPagamento.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(VerificaStatoPagamentoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/InvioNotificaPagamento.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public VerificaStatoPagamentoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VerificaStatoPagamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificaStatoPagamentoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns VerificaStatoPagamento
     */
    @WebEndpoint(name = "VerificaStatoPagamento")
    public VerificaStatoPagamento getVerificaStatoPagamento() {
        return super.getPort(VerificaStatoPagamento, VerificaStatoPagamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificaStatoPagamento
     */
    @WebEndpoint(name = "VerificaStatoPagamento")
    public VerificaStatoPagamento getVerificaStatoPagamento(WebServiceFeature... features) {
        return super.getPort(VerificaStatoPagamento, VerificaStatoPagamento.class, features);
    }

}
