package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnagraficaStato generated by hbm2java
 */
@Entity
@Table(name = "mygov_anagrafica_stato")
public class AnagraficaStato implements java.io.Serializable {

	private Long id;
	private String codStato;
	private String deStato;
	private String deTipoStato;
	private Date dtCreazione;
	private Date dtUltimaModifica;

	public AnagraficaStato() {
	}

	public AnagraficaStato(String codStato, String deStato, String deTipoStato, Date dtCreazione,
			Date dtUltimaModifica) {
		this.codStato = codStato;
		this.deStato = deStato;
		this.deTipoStato = deTipoStato;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_anagrafica_stato_mygov_anagrafica_stato_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_anagrafica_stato_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "cod_stato", nullable = false, length = 80)
	public String getCodStato() {
		return this.codStato;
	}

	public void setCodStato(String codStato) {
		this.codStato = codStato;
	}

	@Column(name = "de_stato", nullable = false, length = 100)
	public String getDeStato() {
		return this.deStato;
	}

	public void setDeStato(String deStato) {
		this.deStato = deStato;
	}

	@Column(name = "de_tipo_stato", nullable = false, length = 80)
	public String getDeTipoStato() {
		return this.deTipoStato;
	}

	public void setDeTipoStato(String deTipoStato) {
		this.deTipoStato = deTipoStato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

}
