package it.regioneveneto.mygov.payment.mypivot.domain.po;

// Generated 15-feb-2016 16.34.08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExportRendicontazione generated by hbm2java
 */
@Entity
@Table(name = "mygov_export_rendicontazione")
public class ExportRendicontazione implements java.io.Serializable {

	private ExportRendicontazioneId id;
	private String nomeFlussoImportEnte;
	private String rigaFlussoImportEnte;
	private String codiceIud;
	private String versioneOggetto;
	private String identificativoDominio;
	private String identificativoStazioneRichiedente;
	private String identificativoMessaggioRicevuta;
	private String dataOraMessaggioRicevuta;
	private String riferimentoMessaggioRichiesta;
	private String riferimentoDataRichiesta;
	private String tipoIdentificativoUnivocoAttestante;
	private String codiceIdentificativoUnivocoAttestante;
	private String denominazioneAttestante;
	private String codiceUnitOperAttestante;
	private String denomUnitOperAttestante;
	private String indirizzoAttestante;
	private String civicoAttestante;
	private String capAttestante;
	private String localitaAttestante;
	private String provinciaAttestante;
	private String nazioneAttestante;
	private String tipoIdentificativoUnivocoBeneficiario;
	private String codiceIdentificativoUnivocoBeneficiario;
	private String denominazioneBeneficiario;
	private String codiceUnitOperBeneficiario;
	private String denomUnitOperBeneficiario;
	private String indirizzoBeneficiario;
	private String civicoBeneficiario;
	private String capBeneficiario;
	private String localitaBeneficiario;
	private String provinciaBeneficiario;
	private String nazioneBeneficiario;
	private String tipoIdentificativoUnivocoVersante;
	private String codiceIdentificativoUnivocoVersante;
	private String anagraficaVersante;
	private String indirizzoVersante;
	private String civicoVersante;
	private String capVersante;
	private String localitaVersante;
	private String provinciaVersante;
	private String nazioneVersante;
	private String emailVersante;
	private String tipoIdentificativoUnivocoPagatore;
	private String codiceIdentificativoUnivocoPagatore;
	private String anagraficaPagatore;
	private String indirizzoPagatore;
	private String civicoPagatore;
	private String capPagatore;
	private String localitaPagatore;
	private String provinciaPagatore;
	private String nazionePagatore;
	private String emailPagatore;
	private String codiceEsitoPagamento;
	private String importoTotalePagato;
	private String identificativoUnivocoVersamento;
	private String codiceContestoPagamento;
	private String singoloImportoPagato;
	private String esitoSingoloPagamento;
	private Date dtDataEsitoSingoloPagamento;
	private String deDataEsitoSingoloPagamento;
	private String causaleVersamento;
	private String datiSpecificiRiscossione;
	private String tipoDovuto;
	private String identificativoFlussoRendicontazione;
	private String dataOraFlussoRendicontazione;
	private String identificativoUnivocoRegolamento;
	private Date dtDataRegolamento;
	private String deDataRegolamento;
	private String numeroTotalePagamenti;
	private String importoTotalePagamenti;
	private String dataAcquisizione;
	private String verificaTotale;

	public ExportRendicontazione() {
	}

	public ExportRendicontazione(ExportRendicontazioneId id) {
		this.id = id;
	}

	public ExportRendicontazione(ExportRendicontazioneId id, String nomeFlussoImportEnte, String rigaFlussoImportEnte, String codiceIud,
			String versioneOggetto, String identificativoDominio, String identificativoStazioneRichiedente, String identificativoMessaggioRicevuta,
			String dataOraMessaggioRicevuta, String riferimentoMessaggioRichiesta, String riferimentoDataRichiesta, String tipoIdentificativoUnivocoAttestante,
			String codiceIdentificativoUnivocoAttestante, String denominazioneAttestante, String codiceUnitOperAttestante, String denomUnitOperAttestante,
			String indirizzoAttestante, String civicoAttestante, String capAttestante, String localitaAttestante, String provinciaAttestante,
			String nazioneAttestante, String tipoIdentificativoUnivocoBeneficiario, String codiceIdentificativoUnivocoBeneficiario,
			String denominazioneBeneficiario, String codiceUnitOperBeneficiario, String denomUnitOperBeneficiario, String indirizzoBeneficiario,
			String civicoBeneficiario, String capBeneficiario, String localitaBeneficiario, String provinciaBeneficiario, String nazioneBeneficiario,
			String tipoIdentificativoUnivocoVersante, String codiceIdentificativoUnivocoVersante, String anagraficaVersante, String indirizzoVersante,
			String civicoVersante, String capVersante, String localitaVersante, String provinciaVersante, String nazioneVersante, String emailVersante,
			String tipoIdentificativoUnivocoPagatore, String codiceIdentificativoUnivocoPagatore, String anagraficaPagatore, String indirizzoPagatore,
			String civicoPagatore, String capPagatore, String localitaPagatore, String provinciaPagatore, String nazionePagatore, String emailPagatore,
			String codiceEsitoPagamento, String importoTotalePagato, String identificativoUnivocoVersamento, String codiceContestoPagamento,
			String singoloImportoPagato, String esitoSingoloPagamento, Date dtDataEsitoSingoloPagamento, String deDataEsitoSingoloPagamento,
			String causaleVersamento, String datiSpecificiRiscossione, String tipoDovuto, String identificativoFlussoRendicontazione,
			String dataOraFlussoRendicontazione, String identificativoUnivocoRegolamento, Date dtDataRegolamento, String deDataRegolamento,
			String numeroTotalePagamenti, String importoTotalePagamenti, String dataAcquisizione, String verificaTotale) {
		this.id = id;
		this.nomeFlussoImportEnte = nomeFlussoImportEnte;
		this.rigaFlussoImportEnte = rigaFlussoImportEnte;
		this.codiceIud = codiceIud;
		this.versioneOggetto = versioneOggetto;
		this.identificativoDominio = identificativoDominio;
		this.identificativoStazioneRichiedente = identificativoStazioneRichiedente;
		this.identificativoMessaggioRicevuta = identificativoMessaggioRicevuta;
		this.dataOraMessaggioRicevuta = dataOraMessaggioRicevuta;
		this.riferimentoMessaggioRichiesta = riferimentoMessaggioRichiesta;
		this.riferimentoDataRichiesta = riferimentoDataRichiesta;
		this.tipoIdentificativoUnivocoAttestante = tipoIdentificativoUnivocoAttestante;
		this.codiceIdentificativoUnivocoAttestante = codiceIdentificativoUnivocoAttestante;
		this.denominazioneAttestante = denominazioneAttestante;
		this.codiceUnitOperAttestante = codiceUnitOperAttestante;
		this.denomUnitOperAttestante = denomUnitOperAttestante;
		this.indirizzoAttestante = indirizzoAttestante;
		this.civicoAttestante = civicoAttestante;
		this.capAttestante = capAttestante;
		this.localitaAttestante = localitaAttestante;
		this.provinciaAttestante = provinciaAttestante;
		this.nazioneAttestante = nazioneAttestante;
		this.tipoIdentificativoUnivocoBeneficiario = tipoIdentificativoUnivocoBeneficiario;
		this.codiceIdentificativoUnivocoBeneficiario = codiceIdentificativoUnivocoBeneficiario;
		this.denominazioneBeneficiario = denominazioneBeneficiario;
		this.codiceUnitOperBeneficiario = codiceUnitOperBeneficiario;
		this.denomUnitOperBeneficiario = denomUnitOperBeneficiario;
		this.indirizzoBeneficiario = indirizzoBeneficiario;
		this.civicoBeneficiario = civicoBeneficiario;
		this.capBeneficiario = capBeneficiario;
		this.localitaBeneficiario = localitaBeneficiario;
		this.provinciaBeneficiario = provinciaBeneficiario;
		this.nazioneBeneficiario = nazioneBeneficiario;
		this.tipoIdentificativoUnivocoVersante = tipoIdentificativoUnivocoVersante;
		this.codiceIdentificativoUnivocoVersante = codiceIdentificativoUnivocoVersante;
		this.anagraficaVersante = anagraficaVersante;
		this.indirizzoVersante = indirizzoVersante;
		this.civicoVersante = civicoVersante;
		this.capVersante = capVersante;
		this.localitaVersante = localitaVersante;
		this.provinciaVersante = provinciaVersante;
		this.nazioneVersante = nazioneVersante;
		this.emailVersante = emailVersante;
		this.tipoIdentificativoUnivocoPagatore = tipoIdentificativoUnivocoPagatore;
		this.codiceIdentificativoUnivocoPagatore = codiceIdentificativoUnivocoPagatore;
		this.anagraficaPagatore = anagraficaPagatore;
		this.indirizzoPagatore = indirizzoPagatore;
		this.civicoPagatore = civicoPagatore;
		this.capPagatore = capPagatore;
		this.localitaPagatore = localitaPagatore;
		this.provinciaPagatore = provinciaPagatore;
		this.nazionePagatore = nazionePagatore;
		this.emailPagatore = emailPagatore;
		this.codiceEsitoPagamento = codiceEsitoPagamento;
		this.importoTotalePagato = importoTotalePagato;
		this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
		this.codiceContestoPagamento = codiceContestoPagamento;
		this.singoloImportoPagato = singoloImportoPagato;
		this.esitoSingoloPagamento = esitoSingoloPagamento;
		this.dtDataEsitoSingoloPagamento = dtDataEsitoSingoloPagamento;
		this.deDataEsitoSingoloPagamento = deDataEsitoSingoloPagamento;
		this.causaleVersamento = causaleVersamento;
		this.datiSpecificiRiscossione = datiSpecificiRiscossione;
		this.tipoDovuto = tipoDovuto;
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
		this.dataOraFlussoRendicontazione = dataOraFlussoRendicontazione;
		this.identificativoUnivocoRegolamento = identificativoUnivocoRegolamento;
		this.dtDataRegolamento = dtDataRegolamento;
		this.deDataRegolamento = deDataRegolamento;
		this.numeroTotalePagamenti = numeroTotalePagamenti;
		this.importoTotalePagamenti = importoTotalePagamenti;
		this.dataAcquisizione = dataAcquisizione;
		this.verificaTotale = verificaTotale;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codiceIpaEnte", column = @Column(name = "codice_ipa_ente", length = 80)),
			@AttributeOverride(name = "codiceIuv", column = @Column(name = "codice_iuv", length = 35)),
			@AttributeOverride(name = "identificativoUnivocoRiscossione", column = @Column(name = "identificativo_univoco_riscossione", length = 35)) })
	public ExportRendicontazioneId getId() {
		return this.id;
	}

	public void setId(ExportRendicontazioneId id) {
		this.id = id;
	}

	@Column(name = "nome_flusso_import_ente", length = 50)
	public String getNomeFlussoImportEnte() {
		return this.nomeFlussoImportEnte;
	}

	public void setNomeFlussoImportEnte(String nomeFlussoImportEnte) {
		this.nomeFlussoImportEnte = nomeFlussoImportEnte;
	}

	@Column(name = "riga_flusso_import_ente", length = 12)
	public String getRigaFlussoImportEnte() {
		return this.rigaFlussoImportEnte;
	}

	public void setRigaFlussoImportEnte(String rigaFlussoImportEnte) {
		this.rigaFlussoImportEnte = rigaFlussoImportEnte;
	}

	@Column(name = "codice_iud", length = 35)
	public String getCodiceIud() {
		return this.codiceIud;
	}

	public void setCodiceIud(String codiceIud) {
		this.codiceIud = codiceIud;
	}

	@Column(name = "versione_oggetto", length = 16)
	public String getVersioneOggetto() {
		return this.versioneOggetto;
	}

	public void setVersioneOggetto(String versioneOggetto) {
		this.versioneOggetto = versioneOggetto;
	}

	@Column(name = "identificativo_dominio", length = 35)
	public String getIdentificativoDominio() {
		return this.identificativoDominio;
	}

	public void setIdentificativoDominio(String identificativoDominio) {
		this.identificativoDominio = identificativoDominio;
	}

	@Column(name = "identificativo_stazione_richiedente", length = 35)
	public String getIdentificativoStazioneRichiedente() {
		return this.identificativoStazioneRichiedente;
	}

	public void setIdentificativoStazioneRichiedente(String identificativoStazioneRichiedente) {
		this.identificativoStazioneRichiedente = identificativoStazioneRichiedente;
	}

	@Column(name = "identificativo_messaggio_ricevuta", length = 35)
	public String getIdentificativoMessaggioRicevuta() {
		return this.identificativoMessaggioRicevuta;
	}

	public void setIdentificativoMessaggioRicevuta(String identificativoMessaggioRicevuta) {
		this.identificativoMessaggioRicevuta = identificativoMessaggioRicevuta;
	}

	@Column(name = "data_ora_messaggio_ricevuta", length = 19)
	public String getDataOraMessaggioRicevuta() {
		return this.dataOraMessaggioRicevuta;
	}

	public void setDataOraMessaggioRicevuta(String dataOraMessaggioRicevuta) {
		this.dataOraMessaggioRicevuta = dataOraMessaggioRicevuta;
	}

	@Column(name = "riferimento_messaggio_richiesta", length = 35)
	public String getRiferimentoMessaggioRichiesta() {
		return this.riferimentoMessaggioRichiesta;
	}

	public void setRiferimentoMessaggioRichiesta(String riferimentoMessaggioRichiesta) {
		this.riferimentoMessaggioRichiesta = riferimentoMessaggioRichiesta;
	}

	@Column(name = "riferimento_data_richiesta", length = 10)
	public String getRiferimentoDataRichiesta() {
		return this.riferimentoDataRichiesta;
	}

	public void setRiferimentoDataRichiesta(String riferimentoDataRichiesta) {
		this.riferimentoDataRichiesta = riferimentoDataRichiesta;
	}

	@Column(name = "tipo_identificativo_univoco_attestante", length = 1)
	public String getTipoIdentificativoUnivocoAttestante() {
		return this.tipoIdentificativoUnivocoAttestante;
	}

	public void setTipoIdentificativoUnivocoAttestante(String tipoIdentificativoUnivocoAttestante) {
		this.tipoIdentificativoUnivocoAttestante = tipoIdentificativoUnivocoAttestante;
	}

	@Column(name = "codice_identificativo_univoco_attestante", length = 35)
	public String getCodiceIdentificativoUnivocoAttestante() {
		return this.codiceIdentificativoUnivocoAttestante;
	}

	public void setCodiceIdentificativoUnivocoAttestante(String codiceIdentificativoUnivocoAttestante) {
		this.codiceIdentificativoUnivocoAttestante = codiceIdentificativoUnivocoAttestante;
	}

	@Column(name = "denominazione_attestante", length = 70)
	public String getDenominazioneAttestante() {
		return this.denominazioneAttestante;
	}

	public void setDenominazioneAttestante(String denominazioneAttestante) {
		this.denominazioneAttestante = denominazioneAttestante;
	}

	@Column(name = "codice_unit_oper_attestante", length = 35)
	public String getCodiceUnitOperAttestante() {
		return this.codiceUnitOperAttestante;
	}

	public void setCodiceUnitOperAttestante(String codiceUnitOperAttestante) {
		this.codiceUnitOperAttestante = codiceUnitOperAttestante;
	}

	@Column(name = "denom_unit_oper_attestante", length = 70)
	public String getDenomUnitOperAttestante() {
		return this.denomUnitOperAttestante;
	}

	public void setDenomUnitOperAttestante(String denomUnitOperAttestante) {
		this.denomUnitOperAttestante = denomUnitOperAttestante;
	}

	@Column(name = "indirizzo_attestante", length = 70)
	public String getIndirizzoAttestante() {
		return this.indirizzoAttestante;
	}

	public void setIndirizzoAttestante(String indirizzoAttestante) {
		this.indirizzoAttestante = indirizzoAttestante;
	}

	@Column(name = "civico_attestante", length = 16)
	public String getCivicoAttestante() {
		return this.civicoAttestante;
	}

	public void setCivicoAttestante(String civicoAttestante) {
		this.civicoAttestante = civicoAttestante;
	}

	@Column(name = "cap_attestante", length = 16)
	public String getCapAttestante() {
		return this.capAttestante;
	}

	public void setCapAttestante(String capAttestante) {
		this.capAttestante = capAttestante;
	}

	@Column(name = "localita_attestante", length = 35)
	public String getLocalitaAttestante() {
		return this.localitaAttestante;
	}

	public void setLocalitaAttestante(String localitaAttestante) {
		this.localitaAttestante = localitaAttestante;
	}

	@Column(name = "provincia_attestante", length = 35)
	public String getProvinciaAttestante() {
		return this.provinciaAttestante;
	}

	public void setProvinciaAttestante(String provinciaAttestante) {
		this.provinciaAttestante = provinciaAttestante;
	}

	@Column(name = "nazione_attestante", length = 2)
	public String getNazioneAttestante() {
		return this.nazioneAttestante;
	}

	public void setNazioneAttestante(String nazioneAttestante) {
		this.nazioneAttestante = nazioneAttestante;
	}

	@Column(name = "tipo_identificativo_univoco_beneficiario", length = 1)
	public String getTipoIdentificativoUnivocoBeneficiario() {
		return this.tipoIdentificativoUnivocoBeneficiario;
	}

	public void setTipoIdentificativoUnivocoBeneficiario(String tipoIdentificativoUnivocoBeneficiario) {
		this.tipoIdentificativoUnivocoBeneficiario = tipoIdentificativoUnivocoBeneficiario;
	}

	@Column(name = "codice_identificativo_univoco_beneficiario", length = 35)
	public String getCodiceIdentificativoUnivocoBeneficiario() {
		return this.codiceIdentificativoUnivocoBeneficiario;
	}

	public void setCodiceIdentificativoUnivocoBeneficiario(String codiceIdentificativoUnivocoBeneficiario) {
		this.codiceIdentificativoUnivocoBeneficiario = codiceIdentificativoUnivocoBeneficiario;
	}

	@Column(name = "denominazione_beneficiario", length = 70)
	public String getDenominazioneBeneficiario() {
		return this.denominazioneBeneficiario;
	}

	public void setDenominazioneBeneficiario(String denominazioneBeneficiario) {
		this.denominazioneBeneficiario = denominazioneBeneficiario;
	}

	@Column(name = "codice_unit_oper_beneficiario", length = 35)
	public String getCodiceUnitOperBeneficiario() {
		return this.codiceUnitOperBeneficiario;
	}

	public void setCodiceUnitOperBeneficiario(String codiceUnitOperBeneficiario) {
		this.codiceUnitOperBeneficiario = codiceUnitOperBeneficiario;
	}

	@Column(name = "denom_unit_oper_beneficiario", length = 70)
	public String getDenomUnitOperBeneficiario() {
		return this.denomUnitOperBeneficiario;
	}

	public void setDenomUnitOperBeneficiario(String denomUnitOperBeneficiario) {
		this.denomUnitOperBeneficiario = denomUnitOperBeneficiario;
	}

	@Column(name = "indirizzo_beneficiario", length = 70)
	public String getIndirizzoBeneficiario() {
		return this.indirizzoBeneficiario;
	}

	public void setIndirizzoBeneficiario(String indirizzoBeneficiario) {
		this.indirizzoBeneficiario = indirizzoBeneficiario;
	}

	@Column(name = "civico_beneficiario", length = 16)
	public String getCivicoBeneficiario() {
		return this.civicoBeneficiario;
	}

	public void setCivicoBeneficiario(String civicoBeneficiario) {
		this.civicoBeneficiario = civicoBeneficiario;
	}

	@Column(name = "cap_beneficiario", length = 16)
	public String getCapBeneficiario() {
		return this.capBeneficiario;
	}

	public void setCapBeneficiario(String capBeneficiario) {
		this.capBeneficiario = capBeneficiario;
	}

	@Column(name = "localita_beneficiario", length = 35)
	public String getLocalitaBeneficiario() {
		return this.localitaBeneficiario;
	}

	public void setLocalitaBeneficiario(String localitaBeneficiario) {
		this.localitaBeneficiario = localitaBeneficiario;
	}

	@Column(name = "provincia_beneficiario", length = 2)
	public String getProvinciaBeneficiario() {
		return this.provinciaBeneficiario;
	}

	public void setProvinciaBeneficiario(String provinciaBeneficiario) {
		this.provinciaBeneficiario = provinciaBeneficiario;
	}

	@Column(name = "nazione_beneficiario", length = 2)
	public String getNazioneBeneficiario() {
		return this.nazioneBeneficiario;
	}

	public void setNazioneBeneficiario(String nazioneBeneficiario) {
		this.nazioneBeneficiario = nazioneBeneficiario;
	}

	@Column(name = "tipo_identificativo_univoco_versante", length = 1)
	public String getTipoIdentificativoUnivocoVersante() {
		return this.tipoIdentificativoUnivocoVersante;
	}

	public void setTipoIdentificativoUnivocoVersante(String tipoIdentificativoUnivocoVersante) {
		this.tipoIdentificativoUnivocoVersante = tipoIdentificativoUnivocoVersante;
	}

	@Column(name = "codice_identificativo_univoco_versante", length = 35)
	public String getCodiceIdentificativoUnivocoVersante() {
		return this.codiceIdentificativoUnivocoVersante;
	}

	public void setCodiceIdentificativoUnivocoVersante(String codiceIdentificativoUnivocoVersante) {
		this.codiceIdentificativoUnivocoVersante = codiceIdentificativoUnivocoVersante;
	}

	@Column(name = "anagrafica_versante", length = 70)
	public String getAnagraficaVersante() {
		return this.anagraficaVersante;
	}

	public void setAnagraficaVersante(String anagraficaVersante) {
		this.anagraficaVersante = anagraficaVersante;
	}

	@Column(name = "indirizzo_versante", length = 70)
	public String getIndirizzoVersante() {
		return this.indirizzoVersante;
	}

	public void setIndirizzoVersante(String indirizzoVersante) {
		this.indirizzoVersante = indirizzoVersante;
	}

	@Column(name = "civico_versante", length = 16)
	public String getCivicoVersante() {
		return this.civicoVersante;
	}

	public void setCivicoVersante(String civicoVersante) {
		this.civicoVersante = civicoVersante;
	}

	@Column(name = "cap_versante", length = 16)
	public String getCapVersante() {
		return this.capVersante;
	}

	public void setCapVersante(String capVersante) {
		this.capVersante = capVersante;
	}

	@Column(name = "localita_versante", length = 35)
	public String getLocalitaVersante() {
		return this.localitaVersante;
	}

	public void setLocalitaVersante(String localitaVersante) {
		this.localitaVersante = localitaVersante;
	}

	@Column(name = "provincia_versante", length = 35)
	public String getProvinciaVersante() {
		return this.provinciaVersante;
	}

	public void setProvinciaVersante(String provinciaVersante) {
		this.provinciaVersante = provinciaVersante;
	}

	@Column(name = "nazione_versante", length = 2)
	public String getNazioneVersante() {
		return this.nazioneVersante;
	}

	public void setNazioneVersante(String nazioneVersante) {
		this.nazioneVersante = nazioneVersante;
	}

	@Column(name = "email_versante", length = 256)
	public String getEmailVersante() {
		return this.emailVersante;
	}

	public void setEmailVersante(String emailVersante) {
		this.emailVersante = emailVersante;
	}

	@Column(name = "tipo_identificativo_univoco_pagatore", length = 1)
	public String getTipoIdentificativoUnivocoPagatore() {
		return this.tipoIdentificativoUnivocoPagatore;
	}

	public void setTipoIdentificativoUnivocoPagatore(String tipoIdentificativoUnivocoPagatore) {
		this.tipoIdentificativoUnivocoPagatore = tipoIdentificativoUnivocoPagatore;
	}

	@Column(name = "codice_identificativo_univoco_pagatore", length = 35)
	public String getCodiceIdentificativoUnivocoPagatore() {
		return this.codiceIdentificativoUnivocoPagatore;
	}

	public void setCodiceIdentificativoUnivocoPagatore(String codiceIdentificativoUnivocoPagatore) {
		this.codiceIdentificativoUnivocoPagatore = codiceIdentificativoUnivocoPagatore;
	}

	@Column(name = "anagrafica_pagatore", length = 70)
	public String getAnagraficaPagatore() {
		return this.anagraficaPagatore;
	}

	public void setAnagraficaPagatore(String anagraficaPagatore) {
		this.anagraficaPagatore = anagraficaPagatore;
	}

	@Column(name = "indirizzo_pagatore", length = 70)
	public String getIndirizzoPagatore() {
		return this.indirizzoPagatore;
	}

	public void setIndirizzoPagatore(String indirizzoPagatore) {
		this.indirizzoPagatore = indirizzoPagatore;
	}

	@Column(name = "civico_pagatore", length = 16)
	public String getCivicoPagatore() {
		return this.civicoPagatore;
	}

	public void setCivicoPagatore(String civicoPagatore) {
		this.civicoPagatore = civicoPagatore;
	}

	@Column(name = "cap_pagatore", length = 16)
	public String getCapPagatore() {
		return this.capPagatore;
	}

	public void setCapPagatore(String capPagatore) {
		this.capPagatore = capPagatore;
	}

	@Column(name = "localita_pagatore", length = 35)
	public String getLocalitaPagatore() {
		return this.localitaPagatore;
	}

	public void setLocalitaPagatore(String localitaPagatore) {
		this.localitaPagatore = localitaPagatore;
	}

	@Column(name = "provincia_pagatore", length = 35)
	public String getProvinciaPagatore() {
		return this.provinciaPagatore;
	}

	public void setProvinciaPagatore(String provinciaPagatore) {
		this.provinciaPagatore = provinciaPagatore;
	}

	@Column(name = "nazione_pagatore", length = 2)
	public String getNazionePagatore() {
		return this.nazionePagatore;
	}

	public void setNazionePagatore(String nazionePagatore) {
		this.nazionePagatore = nazionePagatore;
	}

	@Column(name = "email_pagatore", length = 256)
	public String getEmailPagatore() {
		return this.emailPagatore;
	}

	public void setEmailPagatore(String emailPagatore) {
		this.emailPagatore = emailPagatore;
	}

	@Column(name = "codice_esito_pagamento", length = 1)
	public String getCodiceEsitoPagamento() {
		return this.codiceEsitoPagamento;
	}

	public void setCodiceEsitoPagamento(String codiceEsitoPagamento) {
		this.codiceEsitoPagamento = codiceEsitoPagamento;
	}

	@Column(name = "importo_totale_pagato", length = 15)
	public String getImportoTotalePagato() {
		return this.importoTotalePagato;
	}

	public void setImportoTotalePagato(String importoTotalePagato) {
		this.importoTotalePagato = importoTotalePagato;
	}

	@Column(name = "identificativo_univoco_versamento", length = 35)
	public String getIdentificativoUnivocoVersamento() {
		return this.identificativoUnivocoVersamento;
	}

	public void setIdentificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
		this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
	}

	@Column(name = "codice_contesto_pagamento", length = 35)
	public String getCodiceContestoPagamento() {
		return this.codiceContestoPagamento;
	}

	public void setCodiceContestoPagamento(String codiceContestoPagamento) {
		this.codiceContestoPagamento = codiceContestoPagamento;
	}

	@Column(name = "singolo_importo_pagato", length = 15)
	public String getSingoloImportoPagato() {
		return this.singoloImportoPagato;
	}

	public void setSingoloImportoPagato(String singoloImportoPagato) {
		this.singoloImportoPagato = singoloImportoPagato;
	}

	@Column(name = "esito_singolo_pagamento", length = 35)
	public String getEsitoSingoloPagamento() {
		return this.esitoSingoloPagamento;
	}

	public void setEsitoSingoloPagamento(String esitoSingoloPagamento) {
		this.esitoSingoloPagamento = esitoSingoloPagamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_esito_singolo_pagamento", length = 13)
	public Date getDtDataEsitoSingoloPagamento() {
		return this.dtDataEsitoSingoloPagamento;
	}

	public void setDtDataEsitoSingoloPagamento(Date dtDataEsitoSingoloPagamento) {
		this.dtDataEsitoSingoloPagamento = dtDataEsitoSingoloPagamento;
	}

	@Column(name = "de_data_esito_singolo_pagamento", length = 10)
	public String getDeDataEsitoSingoloPagamento() {
		return this.deDataEsitoSingoloPagamento;
	}

	public void setDeDataEsitoSingoloPagamento(String deDataEsitoSingoloPagamento) {
		this.deDataEsitoSingoloPagamento = deDataEsitoSingoloPagamento;
	}

	@Column(name = "causale_versamento", length = 1024)
	public String getCausaleVersamento() {
		return this.causaleVersamento;
	}

	public void setCausaleVersamento(String causaleVersamento) {
		this.causaleVersamento = causaleVersamento;
	}

	@Column(name = "dati_specifici_riscossione", length = 140)
	public String getDatiSpecificiRiscossione() {
		return this.datiSpecificiRiscossione;
	}

	public void setDatiSpecificiRiscossione(String datiSpecificiRiscossione) {
		this.datiSpecificiRiscossione = datiSpecificiRiscossione;
	}

	@Column(name = "tipo_dovuto", length = 64)
	public String getTipoDovuto() {
		return this.tipoDovuto;
	}

	public void setTipoDovuto(String tipoDovuto) {
		this.tipoDovuto = tipoDovuto;
	}

	@Column(name = "identificativo_flusso_rendicontazione", length = 35)
	public String getIdentificativoFlussoRendicontazione() {
		return this.identificativoFlussoRendicontazione;
	}

	public void setIdentificativoFlussoRendicontazione(String identificativoFlussoRendicontazione) {
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
	}

	@Column(name = "data_ora_flusso_rendicontazione", length = 19)
	public String getDataOraFlussoRendicontazione() {
		return this.dataOraFlussoRendicontazione;
	}

	public void setDataOraFlussoRendicontazione(String dataOraFlussoRendicontazione) {
		this.dataOraFlussoRendicontazione = dataOraFlussoRendicontazione;
	}

	@Column(name = "identificativo_univoco_regolamento", length = 35)
	public String getIdentificativoUnivocoRegolamento() {
		return this.identificativoUnivocoRegolamento;
	}

	public void setIdentificativoUnivocoRegolamento(String identificativoUnivocoRegolamento) {
		this.identificativoUnivocoRegolamento = identificativoUnivocoRegolamento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_regolamento", length = 13)
	public Date getDtDataRegolamento() {
		return this.dtDataRegolamento;
	}

	public void setDtDataRegolamento(Date dtDataRegolamento) {
		this.dtDataRegolamento = dtDataRegolamento;
	}

	@Column(name = "de_data_regolamento", length = 10)
	public String getDeDataRegolamento() {
		return this.deDataRegolamento;
	}

	public void setDeDataRegolamento(String deDataRegolamento) {
		this.deDataRegolamento = deDataRegolamento;
	}

	@Column(name = "numero_totale_pagamenti", length = 15)
	public String getNumeroTotalePagamenti() {
		return this.numeroTotalePagamenti;
	}

	public void setNumeroTotalePagamenti(String numeroTotalePagamenti) {
		this.numeroTotalePagamenti = numeroTotalePagamenti;
	}

	@Column(name = "importo_totale_pagamenti", length = 21)
	public String getImportoTotalePagamenti() {
		return this.importoTotalePagamenti;
	}

	public void setImportoTotalePagamenti(String importoTotalePagamenti) {
		this.importoTotalePagamenti = importoTotalePagamenti;
	}

	@Column(name = "data_acquisizione", length = 10)
	public String getDataAcquisizione() {
		return this.dataAcquisizione;
	}

	public void setDataAcquisizione(String dataAcquisizione) {
		this.dataAcquisizione = dataAcquisizione;
	}

	@Column(name = "verifica_totale", length = 3)
	public String getVerificaTotale() {
		return this.verificaTotale;
	}

	public void setVerificaTotale(String verificaTotale) {
		this.verificaTotale = verificaTotale;
	}

}
