package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlussoRendicontazioneId generated by hbm2java
 */
@Embeddable
public class FlussoRendicontazioneId implements java.io.Serializable {

	private long mygovEnteId;
	private String codDatiSingPagamIdentificativoUnivocoVersamento;
	private String codDatiSingPagamIdentificativoUnivocoRiscossione;
	private int indiceDatiSingoloPagamento;

	public FlussoRendicontazioneId() {
	}

	public FlussoRendicontazioneId(long mygovEnteId, String codDatiSingPagamIdentificativoUnivocoVersamento,
			String codDatiSingPagamIdentificativoUnivocoRiscossione, int indiceDatiSingoloPagamento) {
		this.mygovEnteId = mygovEnteId;
		this.codDatiSingPagamIdentificativoUnivocoVersamento = codDatiSingPagamIdentificativoUnivocoVersamento;
		this.codDatiSingPagamIdentificativoUnivocoRiscossione = codDatiSingPagamIdentificativoUnivocoRiscossione;
		this.indiceDatiSingoloPagamento = indiceDatiSingoloPagamento;
	}

	@Column(name = "mygov_ente_id", nullable = false)
	public long getMygovEnteId() {
		return this.mygovEnteId;
	}

	public void setMygovEnteId(long mygovEnteId) {
		this.mygovEnteId = mygovEnteId;
	}

	@Column(name = "cod_dati_sing_pagam_identificativo_univoco_versamento", nullable = false, length = 35)
	public String getCodDatiSingPagamIdentificativoUnivocoVersamento() {
		return this.codDatiSingPagamIdentificativoUnivocoVersamento;
	}

	public void setCodDatiSingPagamIdentificativoUnivocoVersamento(
			String codDatiSingPagamIdentificativoUnivocoVersamento) {
		this.codDatiSingPagamIdentificativoUnivocoVersamento = codDatiSingPagamIdentificativoUnivocoVersamento;
	}

	@Column(name = "cod_dati_sing_pagam_identificativo_univoco_riscossione", nullable = false, length = 35)
	public String getCodDatiSingPagamIdentificativoUnivocoRiscossione() {
		return this.codDatiSingPagamIdentificativoUnivocoRiscossione;
	}

	public void setCodDatiSingPagamIdentificativoUnivocoRiscossione(
			String codDatiSingPagamIdentificativoUnivocoRiscossione) {
		this.codDatiSingPagamIdentificativoUnivocoRiscossione = codDatiSingPagamIdentificativoUnivocoRiscossione;
	}

	@Column(name = "indice_dati_singolo_pagamento", nullable = false)
	public int getIndiceDatiSingoloPagamento() {
		return this.indiceDatiSingoloPagamento;
	}

	public void setIndiceDatiSingoloPagamento(int indiceDatiSingoloPagamento) {
		this.indiceDatiSingoloPagamento = indiceDatiSingoloPagamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlussoRendicontazioneId))
			return false;
		FlussoRendicontazioneId castOther = (FlussoRendicontazioneId) other;

		return (this.getMygovEnteId() == castOther.getMygovEnteId())
				&& ((this.getCodDatiSingPagamIdentificativoUnivocoVersamento() == castOther
						.getCodDatiSingPagamIdentificativoUnivocoVersamento())
						|| (this.getCodDatiSingPagamIdentificativoUnivocoVersamento() != null
								&& castOther.getCodDatiSingPagamIdentificativoUnivocoVersamento() != null
								&& this.getCodDatiSingPagamIdentificativoUnivocoVersamento()
										.equals(castOther.getCodDatiSingPagamIdentificativoUnivocoVersamento())))
				&& ((this.getCodDatiSingPagamIdentificativoUnivocoRiscossione() == castOther
						.getCodDatiSingPagamIdentificativoUnivocoRiscossione())
						|| (this.getCodDatiSingPagamIdentificativoUnivocoRiscossione() != null
								&& castOther.getCodDatiSingPagamIdentificativoUnivocoRiscossione() != null
								&& this.getCodDatiSingPagamIdentificativoUnivocoRiscossione()
										.equals(castOther.getCodDatiSingPagamIdentificativoUnivocoRiscossione())))
				&& (this.getIndiceDatiSingoloPagamento() == castOther.getIndiceDatiSingoloPagamento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMygovEnteId();
		result = 37 * result + (getCodDatiSingPagamIdentificativoUnivocoVersamento() == null ? 0
				: this.getCodDatiSingPagamIdentificativoUnivocoVersamento().hashCode());
		result = 37 * result + (getCodDatiSingPagamIdentificativoUnivocoRiscossione() == null ? 0
				: this.getCodDatiSingPagamIdentificativoUnivocoRiscossione().hashCode());
		result = 37 * result + this.getIndiceDatiSingoloPagamento();
		return result;
	}

}
