package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InfoMappingTesoreria generated by hbm2java
 */
@Entity
@Table(name = "mygov_info_mapping_tesoreria")
public class InfoMappingTesoreria implements java.io.Serializable {

	private Long id;
	private ManageFlusso manageFlusso;
	private Integer posDeAnnoBolletta;
	private Integer posCodBolletta;
	private Integer posDtContabile;
	private Integer posDeDenominazione;
	private Integer posDeCausale;
	private Integer posNumImporto;
	private Integer posDtValuta;
	private Date dtCreazione;
	private Date dtUltimaModifica;

	public InfoMappingTesoreria() {
	}

	public InfoMappingTesoreria(ManageFlusso manageFlusso, Date dtCreazione, Date dtUltimaModifica) {
		this.manageFlusso = manageFlusso;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	public InfoMappingTesoreria(ManageFlusso manageFlusso, Integer posDeAnnoBolletta, Integer posCodBolletta,
			Integer posDtContabile, Integer posDeDenominazione, Integer posDeCausale, Integer posNumImporto,
			Integer posDtValuta, Date dtCreazione, Date dtUltimaModifica) {
		this.manageFlusso = manageFlusso;
		this.posDeAnnoBolletta = posDeAnnoBolletta;
		this.posCodBolletta = posCodBolletta;
		this.posDtContabile = posDtContabile;
		this.posDeDenominazione = posDeDenominazione;
		this.posDeCausale = posDeCausale;
		this.posNumImporto = posNumImporto;
		this.posDtValuta = posDtValuta;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_info_mapping_tesoreria_mygov_info_mapping_tes_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_info_mapping_tesoreria_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_manage_flusso_id", nullable = false)
	public ManageFlusso getManageFlusso() {
		return this.manageFlusso;
	}

	public void setManageFlusso(ManageFlusso manageFlusso) {
		this.manageFlusso = manageFlusso;
	}

	@Column(name = "pos_de_anno_bolletta")
	public Integer getPosDeAnnoBolletta() {
		return this.posDeAnnoBolletta;
	}

	public void setPosDeAnnoBolletta(Integer posDeAnnoBolletta) {
		this.posDeAnnoBolletta = posDeAnnoBolletta;
	}

	@Column(name = "pos_cod_bolletta")
	public Integer getPosCodBolletta() {
		return this.posCodBolletta;
	}

	public void setPosCodBolletta(Integer posCodBolletta) {
		this.posCodBolletta = posCodBolletta;
	}

	@Column(name = "pos_dt_contabile")
	public Integer getPosDtContabile() {
		return this.posDtContabile;
	}

	public void setPosDtContabile(Integer posDtContabile) {
		this.posDtContabile = posDtContabile;
	}

	@Column(name = "pos_de_denominazione")
	public Integer getPosDeDenominazione() {
		return this.posDeDenominazione;
	}

	public void setPosDeDenominazione(Integer posDeDenominazione) {
		this.posDeDenominazione = posDeDenominazione;
	}

	@Column(name = "pos_de_causale")
	public Integer getPosDeCausale() {
		return this.posDeCausale;
	}

	public void setPosDeCausale(Integer posDeCausale) {
		this.posDeCausale = posDeCausale;
	}

	@Column(name = "pos_num_importo")
	public Integer getPosNumImporto() {
		return this.posNumImporto;
	}

	public void setPosNumImporto(Integer posNumImporto) {
		this.posNumImporto = posNumImporto;
	}

	@Column(name = "pos_dt_valuta")
	public Integer getPosDtValuta() {
		return this.posDtValuta;
	}

	public void setPosDtValuta(Integer posDtValuta) {
		this.posDtValuta = posDtValuta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

}
