package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OperatoreEnteTipoDovuto generated by hbm2java
 */
@Entity
@Table(name = "mygov_operatore_ente_tipo_dovuto")
public class OperatoreEnteTipoDovuto implements java.io.Serializable {

	private Long id;
	private EnteTipoDovuto enteTipoDovuto;
	private String codFedUserId;
	private boolean flgAttivo;

	public OperatoreEnteTipoDovuto() {
	}

	public OperatoreEnteTipoDovuto(String codFedUserId, boolean flgAttivo) {
		this.codFedUserId = codFedUserId;
		this.flgAttivo = flgAttivo;
	}

	public OperatoreEnteTipoDovuto(EnteTipoDovuto enteTipoDovuto, String codFedUserId, boolean flgAttivo) {
		this.enteTipoDovuto = enteTipoDovuto;
		this.codFedUserId = codFedUserId;
		this.flgAttivo = flgAttivo;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_op_ente_tipo_dovuto_mygov_op_ente_tipo_dovuto_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_operatore_ente_tipo_dovuto_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_ente_tipo_dovuto_id")
	public EnteTipoDovuto getEnteTipoDovuto() {
		return this.enteTipoDovuto;
	}

	public void setEnteTipoDovuto(EnteTipoDovuto enteTipoDovuto) {
		this.enteTipoDovuto = enteTipoDovuto;
	}

	@Column(name = "cod_fed_user_id", nullable = false, length = 128)
	public String getCodFedUserId() {
		return this.codFedUserId;
	}

	public void setCodFedUserId(String codFedUserId) {
		this.codFedUserId = codFedUserId;
	}

	@Column(name = "flg_attivo", nullable = false)
	public boolean isFlgAttivo() {
		return this.flgAttivo;
	}

	public void setFlgAttivo(boolean flgAttivo) {
		this.flgAttivo = flgAttivo;
	}

}
