package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PrenotazioneFlussoRiconciliazione generated by hbm2java
 */
@Entity
@Table(name = "mygov_prenotazione_flusso_riconciliazione")
public class PrenotazioneFlussoRiconciliazione implements java.io.Serializable {

	private Long id;
	private int version;
	private Ente ente;
	private Utente utente;
	private AnagraficaStato anagraficaStato;
	private String codRequestToken;
	private String deNomeFileGenerato;
	private Long numDimensioneFileGenerato;
	private String codCodiceClassificazione;
	private String deTipoDovuto;
	private String codIdUnivocoVersamento;
	private String codIdUnivocoRendicontazione;
	private Date dtDataUltimoAggiornamentoDa;
	private Date dtDataUltimoAggiornamentoA;
	private Date dtDataEsecuzioneDa;
	private Date dtDataEsecuzioneA;
	private Date dtDataEsitoDa;
	private Date dtDataEsitoA;
	private Date dtDataRegolamentoDa;
	private Date dtDataRegolamentoA;
	private Date dtDataContabileDa;
	private Date dtDataContabileA;
	private Date dtDataValutaDa;
	private Date dtDataValutaA;
	private String codIdUnivocoDovuto;
	private String codIdUnivocoRiscossione;
	private String codIdUnivocoPagatore;
	private String deAnagraficaPagatore;
	private String codIdUnivocoVersante;
	private String deAnagraficaVersante;
	private String deDenominazioneAttestante;
	private String deOrdinante;
	private String codIdRegolamento;
	private String codContoTesoreria;
	private String deImportoTesoreria;
	private String deCausale;
	private Date dtCreazione;
	private Date dtUltimaModifica;
	private String versioneTracciato;

	public PrenotazioneFlussoRiconciliazione() {
	}

	public PrenotazioneFlussoRiconciliazione(Ente ente, Utente utente, AnagraficaStato anagraficaStato,
			String codRequestToken, String codCodiceClassificazione, Date dtCreazione, Date dtUltimaModifica,
			String versioneTracciato) {
		this.ente = ente;
		this.utente = utente;
		this.anagraficaStato = anagraficaStato;
		this.codRequestToken = codRequestToken;
		this.codCodiceClassificazione = codCodiceClassificazione;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.versioneTracciato = versioneTracciato;
	}

	public PrenotazioneFlussoRiconciliazione(Ente ente, Utente utente, AnagraficaStato anagraficaStato,
			String codRequestToken, String deNomeFileGenerato, Long numDimensioneFileGenerato,
			String codCodiceClassificazione, String deTipoDovuto, String codIdUnivocoVersamento,
			String codIdUnivocoRendicontazione, Date dtDataUltimoAggiornamentoDa, Date dtDataUltimoAggiornamentoA,
			Date dtDataEsecuzioneDa, Date dtDataEsecuzioneA, Date dtDataEsitoDa, Date dtDataEsitoA,
			Date dtDataRegolamentoDa, Date dtDataRegolamentoA, Date dtDataContabileDa, Date dtDataContabileA,
			Date dtDataValutaDa, Date dtDataValutaA, String codIdUnivocoDovuto, String codIdUnivocoRiscossione,
			String codIdUnivocoPagatore, String deAnagraficaPagatore, String codIdUnivocoVersante,
			String deAnagraficaVersante, String deDenominazioneAttestante, String deOrdinante, String codIdRegolamento,
			String codContoTesoreria, String deImportoTesoreria, String deCausale, Date dtCreazione,
			Date dtUltimaModifica, String versioneTracciato) {
		this.ente = ente;
		this.utente = utente;
		this.anagraficaStato = anagraficaStato;
		this.codRequestToken = codRequestToken;
		this.deNomeFileGenerato = deNomeFileGenerato;
		this.numDimensioneFileGenerato = numDimensioneFileGenerato;
		this.codCodiceClassificazione = codCodiceClassificazione;
		this.deTipoDovuto = deTipoDovuto;
		this.codIdUnivocoVersamento = codIdUnivocoVersamento;
		this.codIdUnivocoRendicontazione = codIdUnivocoRendicontazione;
		this.dtDataUltimoAggiornamentoDa = dtDataUltimoAggiornamentoDa;
		this.dtDataUltimoAggiornamentoA = dtDataUltimoAggiornamentoA;
		this.dtDataEsecuzioneDa = dtDataEsecuzioneDa;
		this.dtDataEsecuzioneA = dtDataEsecuzioneA;
		this.dtDataEsitoDa = dtDataEsitoDa;
		this.dtDataEsitoA = dtDataEsitoA;
		this.dtDataRegolamentoDa = dtDataRegolamentoDa;
		this.dtDataRegolamentoA = dtDataRegolamentoA;
		this.dtDataContabileDa = dtDataContabileDa;
		this.dtDataContabileA = dtDataContabileA;
		this.dtDataValutaDa = dtDataValutaDa;
		this.dtDataValutaA = dtDataValutaA;
		this.codIdUnivocoDovuto = codIdUnivocoDovuto;
		this.codIdUnivocoRiscossione = codIdUnivocoRiscossione;
		this.codIdUnivocoPagatore = codIdUnivocoPagatore;
		this.deAnagraficaPagatore = deAnagraficaPagatore;
		this.codIdUnivocoVersante = codIdUnivocoVersante;
		this.deAnagraficaVersante = deAnagraficaVersante;
		this.deDenominazioneAttestante = deDenominazioneAttestante;
		this.deOrdinante = deOrdinante;
		this.codIdRegolamento = codIdRegolamento;
		this.codContoTesoreria = codContoTesoreria;
		this.deImportoTesoreria = deImportoTesoreria;
		this.deCausale = deCausale;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
		this.versioneTracciato = versioneTracciato;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_pren_flus_ric_mygov_pren_flus_ric_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "mygov_prenotazione_flusso_riconciliazione_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_ente_id", nullable = false)
	public Ente getEnte() {
		return this.ente;
	}

	public void setEnte(Ente ente) {
		this.ente = ente;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mygov_utente_id", nullable = false)
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mygov_anagrafica_stato_id", nullable = false)
	public AnagraficaStato getAnagraficaStato() {
		return this.anagraficaStato;
	}

	public void setAnagraficaStato(AnagraficaStato anagraficaStato) {
		this.anagraficaStato = anagraficaStato;
	}

	@Column(name = "cod_request_token", nullable = false)
	public String getCodRequestToken() {
		return this.codRequestToken;
	}

	public void setCodRequestToken(String codRequestToken) {
		this.codRequestToken = codRequestToken;
	}

	@Column(name = "de_nome_file_generato", length = 256)
	public String getDeNomeFileGenerato() {
		return this.deNomeFileGenerato;
	}

	public void setDeNomeFileGenerato(String deNomeFileGenerato) {
		this.deNomeFileGenerato = deNomeFileGenerato;
	}

	@Column(name = "num_dimensione_file_generato")
	public Long getNumDimensioneFileGenerato() {
		return this.numDimensioneFileGenerato;
	}

	public void setNumDimensioneFileGenerato(Long numDimensioneFileGenerato) {
		this.numDimensioneFileGenerato = numDimensioneFileGenerato;
	}

	@Column(name = "cod_codice_classificazione", nullable = false)
	public String getCodCodiceClassificazione() {
		return this.codCodiceClassificazione;
	}

	public void setCodCodiceClassificazione(String codCodiceClassificazione) {
		this.codCodiceClassificazione = codCodiceClassificazione;
	}

	@Column(name = "de_tipo_dovuto")
	public String getDeTipoDovuto() {
		return this.deTipoDovuto;
	}

	public void setDeTipoDovuto(String deTipoDovuto) {
		this.deTipoDovuto = deTipoDovuto;
	}

	@Column(name = "cod_id_univoco_versamento")
	public String getCodIdUnivocoVersamento() {
		return this.codIdUnivocoVersamento;
	}

	public void setCodIdUnivocoVersamento(String codIdUnivocoVersamento) {
		this.codIdUnivocoVersamento = codIdUnivocoVersamento;
	}

	@Column(name = "cod_id_univoco_rendicontazione")
	public String getCodIdUnivocoRendicontazione() {
		return this.codIdUnivocoRendicontazione;
	}

	public void setCodIdUnivocoRendicontazione(String codIdUnivocoRendicontazione) {
		this.codIdUnivocoRendicontazione = codIdUnivocoRendicontazione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_ultimo_aggiornamento_da", length = 13)
	public Date getDtDataUltimoAggiornamentoDa() {
		return this.dtDataUltimoAggiornamentoDa;
	}

	public void setDtDataUltimoAggiornamentoDa(Date dtDataUltimoAggiornamentoDa) {
		this.dtDataUltimoAggiornamentoDa = dtDataUltimoAggiornamentoDa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_ultimo_aggiornamento_a", length = 13)
	public Date getDtDataUltimoAggiornamentoA() {
		return this.dtDataUltimoAggiornamentoA;
	}

	public void setDtDataUltimoAggiornamentoA(Date dtDataUltimoAggiornamentoA) {
		this.dtDataUltimoAggiornamentoA = dtDataUltimoAggiornamentoA;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_esecuzione_da", length = 13)
	public Date getDtDataEsecuzioneDa() {
		return this.dtDataEsecuzioneDa;
	}

	public void setDtDataEsecuzioneDa(Date dtDataEsecuzioneDa) {
		this.dtDataEsecuzioneDa = dtDataEsecuzioneDa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_esecuzione_a", length = 13)
	public Date getDtDataEsecuzioneA() {
		return this.dtDataEsecuzioneA;
	}

	public void setDtDataEsecuzioneA(Date dtDataEsecuzioneA) {
		this.dtDataEsecuzioneA = dtDataEsecuzioneA;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_esito_da", length = 13)
	public Date getDtDataEsitoDa() {
		return this.dtDataEsitoDa;
	}

	public void setDtDataEsitoDa(Date dtDataEsitoDa) {
		this.dtDataEsitoDa = dtDataEsitoDa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_esito_a", length = 13)
	public Date getDtDataEsitoA() {
		return this.dtDataEsitoA;
	}

	public void setDtDataEsitoA(Date dtDataEsitoA) {
		this.dtDataEsitoA = dtDataEsitoA;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_regolamento_da", length = 13)
	public Date getDtDataRegolamentoDa() {
		return this.dtDataRegolamentoDa;
	}

	public void setDtDataRegolamentoDa(Date dtDataRegolamentoDa) {
		this.dtDataRegolamentoDa = dtDataRegolamentoDa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_regolamento_a", length = 13)
	public Date getDtDataRegolamentoA() {
		return this.dtDataRegolamentoA;
	}

	public void setDtDataRegolamentoA(Date dtDataRegolamentoA) {
		this.dtDataRegolamentoA = dtDataRegolamentoA;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_contabile_da", length = 13)
	public Date getDtDataContabileDa() {
		return this.dtDataContabileDa;
	}

	public void setDtDataContabileDa(Date dtDataContabileDa) {
		this.dtDataContabileDa = dtDataContabileDa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_contabile_a", length = 13)
	public Date getDtDataContabileA() {
		return this.dtDataContabileA;
	}

	public void setDtDataContabileA(Date dtDataContabileA) {
		this.dtDataContabileA = dtDataContabileA;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_valuta_da", length = 13)
	public Date getDtDataValutaDa() {
		return this.dtDataValutaDa;
	}

	public void setDtDataValutaDa(Date dtDataValutaDa) {
		this.dtDataValutaDa = dtDataValutaDa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_data_valuta_a", length = 13)
	public Date getDtDataValutaA() {
		return this.dtDataValutaA;
	}

	public void setDtDataValutaA(Date dtDataValutaA) {
		this.dtDataValutaA = dtDataValutaA;
	}

	@Column(name = "cod_id_univoco_dovuto", length = 35)
	public String getCodIdUnivocoDovuto() {
		return this.codIdUnivocoDovuto;
	}

	public void setCodIdUnivocoDovuto(String codIdUnivocoDovuto) {
		this.codIdUnivocoDovuto = codIdUnivocoDovuto;
	}

	@Column(name = "cod_id_univoco_riscossione", length = 35)
	public String getCodIdUnivocoRiscossione() {
		return this.codIdUnivocoRiscossione;
	}

	public void setCodIdUnivocoRiscossione(String codIdUnivocoRiscossione) {
		this.codIdUnivocoRiscossione = codIdUnivocoRiscossione;
	}

	@Column(name = "cod_id_univoco_pagatore", length = 35)
	public String getCodIdUnivocoPagatore() {
		return this.codIdUnivocoPagatore;
	}

	public void setCodIdUnivocoPagatore(String codIdUnivocoPagatore) {
		this.codIdUnivocoPagatore = codIdUnivocoPagatore;
	}

	@Column(name = "de_anagrafica_pagatore", length = 70)
	public String getDeAnagraficaPagatore() {
		return this.deAnagraficaPagatore;
	}

	public void setDeAnagraficaPagatore(String deAnagraficaPagatore) {
		this.deAnagraficaPagatore = deAnagraficaPagatore;
	}

	@Column(name = "cod_id_univoco_versante", length = 35)
	public String getCodIdUnivocoVersante() {
		return this.codIdUnivocoVersante;
	}

	public void setCodIdUnivocoVersante(String codIdUnivocoVersante) {
		this.codIdUnivocoVersante = codIdUnivocoVersante;
	}

	@Column(name = "de_anagrafica_versante", length = 70)
	public String getDeAnagraficaVersante() {
		return this.deAnagraficaVersante;
	}

	public void setDeAnagraficaVersante(String deAnagraficaVersante) {
		this.deAnagraficaVersante = deAnagraficaVersante;
	}

	@Column(name = "de_denominazione_attestante", length = 70)
	public String getDeDenominazioneAttestante() {
		return this.deDenominazioneAttestante;
	}

	public void setDeDenominazioneAttestante(String deDenominazioneAttestante) {
		this.deDenominazioneAttestante = deDenominazioneAttestante;
	}

	@Column(name = "de_ordinante", length = 1024)
	public String getDeOrdinante() {
		return this.deOrdinante;
	}

	public void setDeOrdinante(String deOrdinante) {
		this.deOrdinante = deOrdinante;
	}

	@Column(name = "cod_id_regolamento", length = 35)
	public String getCodIdRegolamento() {
		return this.codIdRegolamento;
	}

	public void setCodIdRegolamento(String codIdRegolamento) {
		this.codIdRegolamento = codIdRegolamento;
	}

	@Column(name = "cod_conto_tesoreria", length = 12)
	public String getCodContoTesoreria() {
		return this.codContoTesoreria;
	}

	public void setCodContoTesoreria(String codContoTesoreria) {
		this.codContoTesoreria = codContoTesoreria;
	}

	@Column(name = "de_importo_tesoreria", length = 35)
	public String getDeImportoTesoreria() {
		return this.deImportoTesoreria;
	}

	public void setDeImportoTesoreria(String deImportoTesoreria) {
		this.deImportoTesoreria = deImportoTesoreria;
	}

	@Column(name = "de_causale", length = 1024)
	public String getDeCausale() {
		return this.deCausale;
	}

	public void setDeCausale(String deCausale) {
		this.deCausale = deCausale;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@Column(name = "versione_tracciato", nullable = false, length = 35)
	public String getVersioneTracciato() {
		return this.versioneTracciato;
	}

	public void setVersioneTracciato(String versioneTracciato) {
		this.versioneTracciato = versioneTracciato;
	}

}
