package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:36 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RendicontazioneSubsetId generated by hbm2java
 */
@Embeddable
public class RendicontazioneSubsetId implements java.io.Serializable {

	private String codiceIpaEnte;
	private String identificativoFlussoRendicontazione;

	public RendicontazioneSubsetId() {
	}

	public RendicontazioneSubsetId(String codiceIpaEnte, String identificativoFlussoRendicontazione) {
		this.codiceIpaEnte = codiceIpaEnte;
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
	}

	@Column(name = "codice_ipa_ente", length = 80)
	public String getCodiceIpaEnte() {
		return this.codiceIpaEnte;
	}

	public void setCodiceIpaEnte(String codiceIpaEnte) {
		this.codiceIpaEnte = codiceIpaEnte;
	}

	@Column(name = "identificativo_flusso_rendicontazione", length = 35)
	public String getIdentificativoFlussoRendicontazione() {
		return this.identificativoFlussoRendicontazione;
	}

	public void setIdentificativoFlussoRendicontazione(String identificativoFlussoRendicontazione) {
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RendicontazioneSubsetId))
			return false;
		RendicontazioneSubsetId castOther = (RendicontazioneSubsetId) other;

		return ((this.getCodiceIpaEnte() == castOther.getCodiceIpaEnte())
				|| (this.getCodiceIpaEnte() != null && castOther.getCodiceIpaEnte() != null
						&& this.getCodiceIpaEnte().equals(castOther.getCodiceIpaEnte())))
				&& ((this.getIdentificativoFlussoRendicontazione() == castOther
						.getIdentificativoFlussoRendicontazione())
						|| (this.getIdentificativoFlussoRendicontazione() != null
								&& castOther.getIdentificativoFlussoRendicontazione() != null
								&& this.getIdentificativoFlussoRendicontazione()
										.equals(castOther.getIdentificativoFlussoRendicontazione())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodiceIpaEnte() == null ? 0 : this.getCodiceIpaEnte().hashCode());
		result = 37 * result + (getIdentificativoFlussoRendicontazione() == null ? 0
				: this.getIdentificativoFlussoRendicontazione().hashCode());
		return result;
	}

}
