package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:40 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TesoreriaSubsetId generated by hbm2java
 */
@Embeddable
public class TesoreriaSubsetId implements java.io.Serializable {

	private String codiceIpaEnte;
	private String codiceIuv;
	private String identificativoFlussoRendicontazione;

	public TesoreriaSubsetId() {
	}

	public TesoreriaSubsetId(String codiceIpaEnte, String codiceIuv, String identificativoFlussoRendicontazione) {
		this.codiceIpaEnte = codiceIpaEnte;
		this.codiceIuv = codiceIuv;
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
	}

	@Column(name = "codice_ipa_ente", length = 80)
	public String getCodiceIpaEnte() {
		return this.codiceIpaEnte;
	}

	public void setCodiceIpaEnte(String codiceIpaEnte) {
		this.codiceIpaEnte = codiceIpaEnte;
	}

	@Column(name = "codice_iuv", length = 35)
	public String getCodiceIuv() {
		return this.codiceIuv;
	}

	public void setCodiceIuv(String codiceIuv) {
		this.codiceIuv = codiceIuv;
	}

	@Column(name = "identificativo_flusso_rendicontazione", length = 35)
	public String getIdentificativoFlussoRendicontazione() {
		return this.identificativoFlussoRendicontazione;
	}

	public void setIdentificativoFlussoRendicontazione(String identificativoFlussoRendicontazione) {
		this.identificativoFlussoRendicontazione = identificativoFlussoRendicontazione;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TesoreriaSubsetId))
			return false;
		TesoreriaSubsetId castOther = (TesoreriaSubsetId) other;

		return ((this.getCodiceIpaEnte() == castOther.getCodiceIpaEnte())
				|| (this.getCodiceIpaEnte() != null && castOther.getCodiceIpaEnte() != null
						&& this.getCodiceIpaEnte().equals(castOther.getCodiceIpaEnte())))
				&& ((this.getCodiceIuv() == castOther.getCodiceIuv()) || (this.getCodiceIuv() != null
						&& castOther.getCodiceIuv() != null && this.getCodiceIuv().equals(castOther.getCodiceIuv())))
				&& ((this.getIdentificativoFlussoRendicontazione() == castOther
						.getIdentificativoFlussoRendicontazione())
						|| (this.getIdentificativoFlussoRendicontazione() != null
								&& castOther.getIdentificativoFlussoRendicontazione() != null
								&& this.getIdentificativoFlussoRendicontazione()
										.equals(castOther.getIdentificativoFlussoRendicontazione())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodiceIpaEnte() == null ? 0 : this.getCodiceIpaEnte().hashCode());
		result = 37 * result + (getCodiceIuv() == null ? 0 : this.getCodiceIuv().hashCode());
		result = 37 * result + (getIdentificativoFlussoRendicontazione() == null ? 0
				: this.getIdentificativoFlussoRendicontazione().hashCode());
		return result;
	}

}
