package it.regioneveneto.mygov.payment.mypivot.domain.po;
// Generated Nov 15, 2017 2:45:28 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TipoFlusso generated by hbm2java
 */
@Entity
@Table(name = "mygov_tipo_flusso")
public class TipoFlusso implements java.io.Serializable {

	private Long id;
	private int version;
	private char codTipo;
	private String deTipo;
	private Date dtCreazione;
	private Date dtUltimaModifica;

	public TipoFlusso() {
	}

	public TipoFlusso(char codTipo, String deTipo, Date dtCreazione, Date dtUltimaModifica) {
		this.codTipo = codTipo;
		this.deTipo = deTipo;
		this.dtCreazione = dtCreazione;
		this.dtUltimaModifica = dtUltimaModifica;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "mygov_tipo_flusso_mygov_tipo_flusso_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")

	@Column(name = "mygov_tipo_flusso_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "cod_tipo", nullable = false, length = 1)
	public char getCodTipo() {
		return this.codTipo;
	}

	public void setCodTipo(char codTipo) {
		this.codTipo = codTipo;
	}

	@Column(name = "de_tipo", nullable = false, length = 100)
	public String getDeTipo() {
		return this.deTipo;
	}

	public void setDeTipo(String deTipo) {
		this.deTipo = deTipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_creazione", nullable = false, length = 29)
	public Date getDtCreazione() {
		return this.dtCreazione;
	}

	public void setDtCreazione(Date dtCreazione) {
		this.dtCreazione = dtCreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_modifica", nullable = false, length = 29)
	public Date getDtUltimaModifica() {
		return this.dtUltimaModifica;
	}

	public void setDtUltimaModifica(Date dtUltimaModifica) {
		this.dtUltimaModifica = dtUltimaModifica;
	}

}
