package it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematiciccp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-12-17T16:55:25.220+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP", name = "PagamentiTelematiciCCP")
@XmlSeeAlso({gov.telematici.pagamenti.ws.ppthead.ObjectFactory.class, gov.telematici.pagamenti.ws.ObjectFactory.class, it.gov.digitpa.schemas._2011.pagamenti.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagamentiTelematiciCCP {

    @WebResult(name = "paaAttivaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaAttivaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaAttivaRPTRisposta")
    @WebMethod(action = "paaAttivaRPT")
    public gov.telematici.pagamenti.ws.PaaAttivaRPTRisposta paaAttivaRPT(
        @WebParam(partName = "bodyrichiesta", name = "paaAttivaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.PaaAttivaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );

    @WebResult(name = "paaVerificaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaVerificaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaVerificaRPTRisposta")
    @WebMethod(action = "paaVerificaRPT")
    public gov.telematici.pagamenti.ws.PaaVerificaRPTRisposta paaVerificaRPT(
        @WebParam(partName = "bodyrichiesta", name = "paaVerificaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        gov.telematici.pagamenti.ws.PaaVerificaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );
}
