package it.tasgroup.idp.loader;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-11T14:51:37.659+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "Loader", 
                  wsdlLocation = "file:/home/user/projects/paytas-be/ebmonitor/IdpBillerServicesCore/src/main/resources/wsdl/Loader.wsdl",
                  targetNamespace = "http://idp.tasgroup.it/Loader/") 
public class Loader extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://idp.tasgroup.it/Loader/", "Loader");
    public final static QName LoaderPort = new QName("http://idp.tasgroup.it/Loader/", "loaderPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/user/projects/paytas-be/ebmonitor/IdpBillerServicesCore/src/main/resources/wsdl/Loader.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Loader.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/user/projects/paytas-be/ebmonitor/IdpBillerServicesCore/src/main/resources/wsdl/Loader.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Loader(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Loader(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Loader() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns LoaderService
     */
    @WebEndpoint(name = "loaderPort")
    public LoaderService getLoaderPort() {
        return super.getPort(LoaderPort, LoaderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoaderService
     */
    @WebEndpoint(name = "loaderPort")
    public LoaderService getLoaderPort(WebServiceFeature... features) {
        return super.getPort(LoaderPort, LoaderService.class, features);
    }

}
